<?php
$__information['ndskshortcut_list__pre'] = "Możesz dodać stronę w Kloxo do ulubionych, klikając na [b] dodaj do ulubionych [/b] na łącze [b] poszczególnej strony. [/b] Każdy skrót ma parametr zwany [b] identyfikatorem sortowania [/b]. Ustawiając odpowiedni [b] identyfikator sortowania [/b] na każdym z łączy, a następnie sortując całą listę za pomocą [b] identyfikatora sortowania [/b], możesz dostosować listę w sposób jaki chcesz. Pasek narzędzi na górze odpowiada dokładnie temu w jaki sposób ta lista jest posortowana.";
$__information['sshauthorizedkey_addform_lxlabs_pre'] = "W ten sposób dodasz klucz SSH firmy LxLabs do swoich autoryzowanych kluczy, co pozwoli wsparciu technicznemu firmy LxLabs na zalogowanie się do Twojego serwera bez znajomości hasła. Jest to zalecane jeśli prosiłeś o pomoc z firmy LxLabs.";
$__information['rawlxguardhit_list__pre'] = "Oto lista bezpośrednich połączeń. Jest to przydantne do śledzenia adresów IP jeśli znasz nazwę konta użytkownika np. jeżeli Twoi klienci próbują zalogować się do serwera i zrobią to zbyt wiele razy, to zostaną zablokowani. Ta strona ma funkcję [b] zaawansowanego wyszukiwania [/b], gdzie możesz przeszukiwać listę za pomocą [b] nazwy użytkownika [/b] , i w ten sposób możesz dowiedzieć się jaki jest adres IP klienta, który możesz usunąć ze strony głównych połączeń.";
$__information['login_pre'] = "<p> Witaj w <%programname%>  </p><p>Użyj prawidłowej nazwy użytkownika i hasła, aby uzyskać dostęp do konsoli serwera. </p> ";
$__information['tickethistory_addform__pre'] = "Możesz użyć &#91quote&#93 &#91/quote &#93, aby zacytować trochę tekstu, który zostanie wyświetlony jako prawidłowo sformatowany. Możesz także użyć &#91code&#93 &#91/code&#93 dla fragmentów kodu oraz &#91b&#93 &#91/b&#93 dla pogrubionej czcionki.";
$__information['lxguardwhitelist_addform__pre'] = "Jest zalecane, abyś używał przycisku [b] białej listy [/b] na górze <url:a=list&c=lxguardhitdisplay>strony połączeń</url>, aby dodać adres IP do białej listy. Wpisując ręcznie adres IP możesz się pomylić, co może potem spowodować zdziwienie. Jeśli wpisujesz swój adres IP tutaj, sprawdź dwukrotnie czy jest on poprawny.";
$__information['sshconfig_updateform_update_pre'] = "Jest zalecane, abyś całkowicie wyłączył dostęp za pomocą hasła do tego serwera i zamiast niego użył <url:goback=1&a=list&c=sshauthorizedkey>menedżera autoryzacji kluczy SSH </url>, aby pozwolić poszczególnym osobom na dostęp bez znajomości hasła. Jeżeli jest to hyperVM, a Ty masz zamiar sprzedawać serwery VPS innym osobom, nie będziesz miał możliwości całkowitego wyłączenia dostępu do SSH za pomocą hasła, ponieważ użytkownicy serwerów VPS muszą mieć możliwość zalogowania się do serwera głównego, aby uzyskać dostęp do swoich konsoli. W każdym przypadku, upewnij się, że całkowicie wyłączyłeś dostęp do konsoli root dla tego serwera. Jako zasadę w Kloxo przyjmij wyłączenie dostępu za pomocą hasła do wszystkiego, podczas gdy na hyperVM wyłącz hasło wyłącznie do konsoli root.";
$__information['all_dns_list__pre'] = "Oto lista wszystkich serwerów DNS stworzonych przez właścicieli serwerów VPS. <url:o=general&a=updateform&sa=reversedns> Kliknij tutaj </url>, aby skonfigurować serwery DNS w taki sposób, aby wszyscy Twoi klienci mogli ich używać. Menadżer DNS HyperVM pozwala właścicielowi serwera VPS na stworzenie serwera DNS bezpośrednio w hyperVM i wszystkie dane zostaną zachowane na serwerach usługodawcy serwerów VPS. Inaczej mówiąc pozwala to na utrzymanie serwerów DNS Twoich klientów ze serwerami VPS bezpośrednio na Twoich serwerach.";
$__information['actionlog_list__pre'] = "Logi ostatnich operacji przechowują wszystkie komendy wykonywane przez klienta lub na serwerze VPS. Ważną rzeczą, którą powinieneś zauważyć tutaj, to fakt, że zewnętrzna nazwa użytkownika osoby zalogowanej jest tutaj prawidłowo zapisywana, dlatego nigdy nikomu nie powinieneś udzielać dostępu do swojego głównego konta, a zamiast tego stworzyć <url:a=list&c=auxiliary> zewnętrzną nazwę użytkownika </url> dla każdego ze swoich pracowników.";
$__information['sshauthorizedkey_list__pre'] = "Pamiętaj, że plik ~/.ssh/authorized_keys2 jest przestarzały jeśli chodzi o OpenSSH od wersji 3 i dlatego tylko plik ~/.ssh/authorized_keys jest możliwy do zarządzania. Są to klucze SSH serwerów, które mogą się zalogować do tego serwera bez konieczności podawania hasła. Upewnij się, że ta lista jest jak najkrótsza.";
$__information['updateform_forcedeletepserver_pre'] = "Wymuś usunięcie serwera po prostu usuwa serwer z bazy danych hyperVM/Kloxo. Jest to przydatne, gdy serwer został całkowicie usunięty, a nie jest już dostępny.";
$__information['allowedip_addform__pre'] = "Wskazówka: Ta opcja blokuje tylko dostęp do panelu serwera i nie zablokuje dostępu do bieżących zasobów. Możesz dodać adres IP w postaci puli [b] 192.168.1.*[/b] lub z innych podziałów sieci. Zamiast podawać liczbę, możesz użyć symbolu [b] * [/b] zamiast całej puli adresów. Możesz także dodać poszczególne adresy IP w postaci 192.168.1.2. Pamiętaj, że kropki są wymagane i musisz podać wszystkie cztery pola. Jeśli chcesz zezwolić na dostęp wszystkim, usuń wszystkie dozwolone adresy IP, lub wpisz [b] *.*.*.* [/b]. Inne zapisy adresów IP nie są obsługiwane w tym momencie.";
$__information['blockedip_addform__pre'] = "Wskazówka: Ta opcja blokuje tylko dostęp do panelu serwera a nie do bieżących zasobów. Oto lista zablokowanych adresów IP. Zapis adresów IP jest taki sam jak dozwolonych IP. Powinieneś dodać zablokowane adresy IP tylko wtedy jeśli lista dozwolonych adresów jest pusta. Jeśli lista dozwolonych adresów nie jest pusta, wtedy automatycznie wszystkie adresy IP nie wymienione na tej liście zostaną zablokowane.";
$__information['updateform_portconfig_pre'] = "Ta strona służy przede wszystkim do konfiguracji portów Kloxo/HyperVM. Po dokonaniu tutaj zmian musisz uruchomić ponownie usługę Kloxo/HyperVM, aby zmiany zostały zastosowane. Uruchom tą komendę [b] cd /usr/local/lxlabs/<%program%>/httpdocs ; lphp.exe ../bin/common/misc/defaultport.php [/b], a wszystkie porty zostaną przywrócone do wartości domyślnych. Możesz później uruchomić ponownie Kloxo/HyperVM. Pozostaw wszystkie puste pola, aby przywrócić domyślne porty.";
$__information['updateform_schedule_conf_pre'] = "Pamiętaj, że są tutaj tylko zaplanowane kopie zapasowe tzn. takie kopie zapasowe, których nazwa zaczyna się na <%program%>-scheduled i będą one nadpisywane. Jeśli stworzyłeś kopię zapasową ze swoją własną nazwą to nie zostanie ona nadpisana. Jeśli chcesz, aby ręcznie stworzona kopia zapasowa była nadpisywana, wprowadź początkowy ciąg taki jak [b] <%program%>-scheduled- [/b]";
$__information['updateform_ssl_kloxo_pre'] = "Ta opcja ustawia certyfikat SSL dla <%program%> jako określony certyfikat. Upewnij się, że uruchomiłeś ponownie <%program%> po ustawieniu go tutaj.";
$__information['updateform_ssl_authorized_keys_pre'] = "Oto lista kluczy SSH ze serwerów, które są autoryzowane do zalogowania na Twoje konto bez znajomości hasła. Każde hasło jest przechowywane w osobnej linii. Możesz dodać klucze do serwerów, którym chcesz przydzielić dostęp bez hasła do tego serwera. Powinieneś utrzymywać ten plik w najkrótszej postaci jak to możliwe, aby zredukować szanse na zalogowanie się osób niepowołanych";
$__information['updateform_ssl_hypervm_pre'] = "Ta opcja ustawia certyfikat SSL dla <%program%> jako określony certyfikat. Upewnij się, że uruchomiłeś ponownie <%program%> po ustawieniu go tutaj.";
$__information['updateform_selfbackupconfig_pre'] = "Ta opcja służy przede wszystkim do konfiguracji zdalnej kopii zapasowej bazy danych serwera głównego i niczego poza nią. Zrzut bazy danych jest wykonywany codziennie i zapisywany w lokalnym katalogu na tym serwerze. Jeżeli konto FTP jest tutaj skonfigurowane, plik zostanie wysłany do tego serwera. Jest to głównie przydatne w konfiguracji dużego klastra, gdzie awaria serwera głównego ma większe konsekwencje.";
$__information['lxguard_updateform_update_pre'] = "Lxguard zabezpiecza przed atakami typu brute force monitorując logi SSH i FTP i blokując adresy IP, które mają zbyt wiele nieudanych prób zalogowania się na serwer. Lxguard jest domyślnie włączony i będzie automatycznie blokował hosty. Nie ma możliwości jego wyłączenia. Możesz skonfigurować LxGuard określając [b] próg zablokowanych prób [/b] lub dodając adres IP do białej listy. Jeśli adres IP znajduje się na białej liście to nie zostanie on zablokowany, nawet gdy przekroczy dopuszczalny próg nieudanych prób zalogowania. Aby usunąć ostrzeżenia dotyczące Lxguard zaznacz pole akceptacji poniżej";
$__information['updateform_generalsetting_pre'] = "Adres URL do 'Centrum zgłoszeń' to łącze do Twojego Centrum zgłoszeń, które służy jako domyślne centrum pomocy wbudowane w to oprogramowanie. Adres URL społeczności to łącze klienta, które będzie on widział po swojej lewej stronie i w większości wypadków może kierować do Twojego forum.";
$__information['custombutton_addform__pre'] = "W adresie URL, możesz użyć %nname%, które zostanie podmienione na nazwę klienta. Tylko dla Kloxo, możesz użyć %default_domain% jako domyślną domenę klienta.";
$__information['updateform_download_config_pre'] = "Zazwyczaj ściągając pliki serwer główny tworzy tymczasową sesję, a następnie przekierowuje przeglądarkę bezpośrednio na serwer podrzędny. Ma to na celu oszczędność pasma, ponieważ inaczej pliki będą niepotrzebnie przechodzić przez serwer główny. Jeśli włączysz tą opcję, hyperVM/Kloxo użyje innej trasy dla plików przez serwer główny sam w sobie. Jest to użyteczna opcja jeśli przydzieliłeś serwerom podrzędnym prywatne adresy IP i serwery podrzędne nie są dostępne dla świata zewnętrznego.";
$__information['updateform_login_options_pre'] = " Wskazówka: czas wygaśnięcia sesji nie może być mniejszy niż 100 i jeśli będzie mniejszy, to zostanie automatycznie ustawiony na 100.";
$__information['resourceplan_change_pre'] = "Wskazówka: Jeśli zmienisz parametry tutaj, każde konto, które używa tego pakietu zostanie uaktualnione o nowe parametry. Kliknij <url:a=updateForm&sa=account>tutaj, aby zobaczyć konta używające tego pakietu</url>";
$__information['lxbackup_updateform_backup_pre'] = "Plik kopii zapasowej pojawi się w katalogu __backup na Twoim koncie. Możesz się do niego dostać klikając na zakładkę 'Menedżer plików'. Aby przywrócić kopię zapasową, możesz najpierw wysłać ją na serwer używając zakładki [b] wysyłanie [/b]. Możesz wysłać plik kopii zapasowej bezpośrednio lub z adresu URL http lub ze serwera FTP. Następnie powrócić tutaj i kliknij ikonę [b] katalogu [/b] po prawej stronie od formularza [b] przywracania [/b]. To pozwoli Tobie wskazać określony plik. Następnie kliknij na [b] uruchom proces przywracania [/b]. Zwróć uwagę, że kopia zapasowa <%program%> jest hierarchiczna. Jeśli stworzysz kopię zapasową określonego zasobu, wtedy wszystko znajdujące się pod nim zostanie automatycznie dołączone, dlatego jeśli tworzysz kopię zapasową konta administratora nie musisz tworzyć osobno kopii zapasowej kont klientów.";
$__information['phpini_updateform_edit_admin_pre'] = "Musisz aktywować pole obok [b] Zarządzanie konfiguracją PHP [/b], aby zezwolić Kloxo na całkowite zarządzanie plikiem php.ini. Zauważ, że Twoja stara konfiguracja pliku php.ini zostanie nadpisana. Aby przywrócić Twój stary plik php.ini, po prostu wyłącz [b] Zarządzanie konfiguracją PHP [/b], a następnie przeprowadź aktualizację zatwierdzając zmiany. Jest zalecane, aby Kloxo samoistnie zarządzało Twoją konfiguracją PHP. Zapytaj na naszym forum jeśli potrzebujesz specjalnych funkcji.";
$__information['client_updateform_wall_pre'] = "Wskazówka: Ta wiadomość będzie wysłana tylko do Twoich bezpośrednich klientów (poziom niżej, włączając to konto), którzy mają ustawiony email kontaktowy. ";
$__information['ffile_updateform_upload_pre'] = "Jeśli chcesz wysłać kilka plików/katalogów, utwórz archiwum zip i prześlij je; możesz je rozpakować wewnątrz menedżera plików.  ";
$__information['dskshortcut_a_list__pre'] = "Aby dodać stronę do ulubionych, kliknij na łącze [b] dodaj do ulubionych [/b], które jest widoczne na górze po prawej stronie. Możesz kliknąć na ulubione na liście poniżej i zmienić nazwę wpisu na coś bardziej rozpoznawalnego przez Ciebie. Możesz kliknąć na nagłówek [b] opis [/b], a ta lista zostanie posortowana według tego pola, a następnie odświeży całą ramkę. Bieżąca lista ulubionych w lewym panelu dokładnie odzwierciedla porządek sortowania, który jest widoczny tutaj.";
$__information['ticketconfig_updateform_ticketconfig_pre'] = "Konto mailgate to konto, z którego <%program%> pobierze wszystkie emaile, w określonych odstępach czasowych, a następnie zostaną one przetworzone i dodane do centrum zgłoszeń. Wysyłając emaile <%program%> wyśle pocztę jako pochodzącą z tego adresu, który skonfigurujesz. Adres ma formę [b] konto@domena.pl [/b]. Serwer to serwer POP3, z którego zostaną pobrane emaile jak np. [b] serwer.pl [/b] . Jeśli zaznaczysz pole [b] użyj SSL [/b], wtedy poczta zostania pobrana używając POP3-SSL na porcie 995. Jest zawsze zalecane, abyś używał SSL, ale musisz się upewnić, że zdalny serwer poczty wspiera usługę POP3-SSL na porcie 995. ";
$__information['updateform_mysqlpasswordreset_pre'] = "Ta opcja powinna być używana tylko, gdy zgubiłeś hasło root do bazy danych MySQL. W innych okolicznościach, możesz zmienić hasło klikając <url:a=list&c=dbadmin>tutaj (administrator baz danych)</url>. Pamiętaj o zachowaniu cierpliwości, ponieważ wykonanie tej operacji może zabrać nieco czasu. Ustawi ona nowe hasło root do bazy danych MySQL uruchamiając je z opcją skip-grant-tables. Jeśli ta funkcja nie zadziała, zaloguj się za pomocą SSH i uruchom komendę '[b]sh /script/reset-mysql-root-password[/b]'. ";
$__information['updateform_pserver_s_pre'] = "Oto pula serwerów dla sprzedawców. Pokazuje ona listę serwerów, których Ci sprzedawcy mogą używać tworząc klienta tzn. tworząc nowego klienta sprzedawca będzie miał możliwość przydzielenia serwerów z tej listy dla siebie.";
$__information['general_updateform_disableper_pre'] = "Oto wartość procentowa zużycia konta, po której zostanie ono zablokowane. Domyślna wartość to 110%. Otrzymasz ostrzeżenia, gdy zużycie osiągnie odpowiednio 90,100,110%. ";

$__information['updateform_ftp_conf_pre'] = "Jeśli włączyłeś opcję [b] nie przechowuj lokalnej kopii [/b], plik lokalny będzie usunięty.  " .
        "Możesz tego używać jeśli chcesz oszczędzać miejsce na swoim koncie.<br>" .
        "- Możesz wpisać pełny format tak jak np. [b]  ftps://1.2.3.4:21001 [/b] na 'Serwerze FTP'";

$__information['vv_updateform_skin_logo_pre'] = "Aby wymusić własne logo w panelach klienckich, po prostu wyłącz im uprawnienie 'możliwość zmiany loga' w ustawieniach uprawnień. ";
$__information['pserver_updateform_information_pre'] = "FQDN to bardzo ważne pole i powinno zostać ustawione na nazwę domeny, która prawidłowo wskazuje na ten określony serwer. W momencie ustawienia FQDN, hyperVM/Kloxo użyje tej wartości do dalszej komunikacji sieciowej, a jeśli FQDN jest tutaj ustawione niepoprawnie, komunikacja sieciowa pomiędzy serwerem głównym a podrzędnymi nie powiedzie się. Jeśli pozostawisz to pole puste, hyperVM/Kloxo użyje pierwszego adresu IP na tym serwerze do komunikacji. Ustaw FQDN na nazwę hosta, która umożliwia na dostęp do tego serwera z każdego miejsca.";
$__information['pserver_addform__pre'] = "Jeśli na nowo zainstalowałeś serwer podrzędny, jego hasłem jest admin. Jest zalecane, aby dodać serwery w postaci ich nazw, a nie za pomocą ich adresu IP. Serwer powinien być dostępny z poziomu serwera głównego używając określonej nazwy wpisanej tutaj przez Ciebie np. serwer.domena.pl. Identyfikator najwyższego stopnia to ciąg, który może być użyty do opisania tego serwera i będzie widoczny w polach wyboru.";

// MR -- zmodyfikowane
$__information['updateform_upload_logo_pre'] = "Pozostaw puste pole, aby ustawić logo na domyślny obrazek.<br />".
        "- Aby wymusić własne logo w panelach klienckich, po prostu wyłącz uprawnienie 'możliwość zmiany loga' w ustawieniach uprawnień.<br />".
        "- Prześlij plik loga (przykład: jest widoczny w górnej prawej części panelu administracyjnego), obrazek powinien być we formacie PNG z optymalną wysokością 75 pikseli, podczas gdy szerokość leży w gestii klienta.";

$__information['web_updateform_extra_tag_pre'] = "<b><font color=red> Ostrzeżenie !!!!! </font></b> Cokolwiek wpiszesz tutaj zostanie to bezpośrednio dodane do wirtualnego hosta. Jeśli pojawi się tutaj błąd składni, może to uniemożliwić ponowne uruchomienie serwera WWW. Ta opcja jest dostępna tylko dla użytkownika admin. Po zapisaniu jej tutaj, upewnij się, że serwer działa prawidłowo. ";
$__information['addondomain_list__pre'] = "Wskazówka: <br>* Jeśli chcesz mieć zaparkowaną domenę z pełnym zarządzaniem DNS oraz poczty, utwórz pełną domenę, która ma taką samą ścieżkę główną jak domena docelowa. <br> * Jeśli chcesz mieć przekierowaną domenę z pełnym zarządzaniem DNS oraz poczty, utwórz pełną domenę, a następnie przekieruj jej ścieżkę główną [b] / [/b] do domeny docelowej.";
$__information['redirect_a_list__pre'] = "Ta opcja pozwala na przekierowanie określonego adresu URL w tej domenie na inny. <url:a=updateform&sa=configure_misc> Kliknij tutaj </url> jeśli chcesz wymusić przekierowanie domeny bez przedrostka www typu http://domena.pl na http://www.domena.pl .";
$__information['web_updateform_dirindex_pre'] = "Włączenie opcji [b] indeksowania katalogów [/b] pozwoli Tobie na przeglądanie katalogów Twojej domeny poprzez serwer WWW. Jeśli indeksowanie katalogów jest wyłączone i jeśli plik index.xxx nie został znaleziony w katalogu pojawi się komunikat błędu - brak dostępu.";
$__information['updateform_editmx_pre'] = "Jeśli chcesz skonfigurować zdalny serwer poczty, <url:a=updateform&sa=remotelocalmail> Kliknij tutaj </url>. Możesz ustawić Kloxo w taki sposób, aby serwer poczty był konfigurowany zdalnie, dzięki czemu wszystkie lokalne emaile będą od razu przesyłane na ten serwer. Jeśli nie skonfigurowałeś zdalnej poczty, wtedy wszystkie emaile będą dostarczone lokalnie bez wykonywania żadnych zapytań DNS. ";
$__information['web_updateform_run_stats_pre'] = "Ta opcja pozwala na wymuszenie uruchomienia programu statystyk, dzięki czemu będziesz mógł zobaczyć najnowsze statystyki na stronie statystyk swojej strony WWW. Użyj [b] aktualizuj wszystko [/b], aby uruchomić tą opcję na wszystkich domenach widocznych w górnym menu rozwijalnym.";

$__information['server_alias_a_addform__pre'] = "Możesz dodać aliasy wildcard [b] * [/b], dzięki czemu wszystkie poddomeny będą automatycznie bezpośrednio przekierowywane do tej domeny. ".
         "Kloxo automatycznie doda wpis DNS dla tego aliasu.<br />".
         "- Po skonfigurowaniu poddomeny Catch-all korzystając z (*), możesz dodać właściwą logikę do swojego skryptu, aby wykryć prawidłową poddomenę i podjąć odpowiednie operacje<br />".
         "- Lighttpd może nie działać prawidłowo z wybranymi wildcardami (*). Domyślne strony (default, cp, disable i 'customize') będą kierowały do strony na domenie";
  
$__information['updateform_sesubmit_pre'] = "Twoja domena zostanie dodana do wyszukiwarek z listy poniżej. Adres email użyty tutaj powinien być adresem, który nie jest często używany, ponieważ istnieje duże prawdopodobieństwo, że będziesz otrzymał na niego ogromne ilości niechcianych wiadomości.";
$__information['mmail_updateform_authentication_pre'] = "Twój podstawowy serwer MX jest automatycznie zawarty w SPF i nie musisz go dodawać osobno. Możesz użyć [b] aktualizuj wszystko [/b], aby wprowadzić te zmiany na wszystkich domenach widocznych w menu rozwijalnym.";
$__information['updateform_preview_config_pre'] = "Domena podglądu to domena główna, na którą zostaniesz przekierowany po naciśnięciu przycisku Podgląd strony. Musisz ręcznie dodać zaparkowaną domenę nazywaną domena.pl.domenapodgladu.pl do tej domeny, a potem dodać tutaj domenapogladu.pl. Następnie [b] podgląd domeny bez konfiguracji DNS [/b] zostanie przekierowany na domena.pl.domenapodgladu.pl. Jeśli nie jesteś pewien, pozostaw to pole puste.";
$__information['updateform_stats_protect_pre'] = "Zabezpieczenie strony statystyk to hasło, które jest używane do zabezpieczenia strony statystyk dla Twojej domeny. Jeśli hasło nie zostało wpisane to zabezpieczenie zostanie wyłączone i dzięki temu będziesz miał możliwość bezpośredniego dostępu do statystyk.";
$__information['updateform_installatron_pre'] = "Musisz się wylogować z konta bieżącego użytkownika, a następnie zalogować się jako określony użytkownik, na którego koncie chcesz użyć Installatron. Installatron jest dostępny aktualnie tylko dla użytkownika, który jest bezpośrednio zalogowany.";
$__information['ftpuser_admin'] = "Użyj [b] --direct-- [/b], aby dodać użytkownika FTP, który nie zawiera nazwy domeny.";
$__information['updateform_default_domain_pre'] = "Ta opcja ustawia domenę uznawaną jako domenę główną na tym określonym koncie. Możesz dostać się do ścieżki głównej tej domeny wpisując http://IP/~nazwaklienta. Aby skojarzyć adres IP z domeną, musisz <url: a=list&c=ipaddress>kliknąć tutaj</url>, a następnie wejść wewnątrz adresu IP i kliknąć tam zakładkę 'konfiguracja domeny'. Jeśli chcesz zobaczyć domenę przed ustawieniem serwerów DNS to najlepszym sposobem jest stworzenie wpisu dla domeny w lokalnym pliku /etc/hosts. Ścieżka dla pliku w Windows to c:/windows/system32/drivers/etc/hosts . Zwyczajnie dodaj wpis taki jak np. ten: [b] 192.168.1.32 domena.pl [/b] w osobnej linii, a następnie będziesz mógł uzyskać dostęp do domeny wpisując ją w polu adresu przeglądarki.";
$__information['updateform_blockip_pre'] = "Dodaj jeden adres IP na linię. Jeśli chcesz dodać zakres adresów IP użyj zapisu .*.* . np. 192.168.*.*. Zauważ, że jest to jedyny zapis wspierany przez zakresy adresów IP. Standardowy zapis adresów IP nie jest wspierany. ";
$__information['web_updateform_statsconfig_pre'] = "Każdego dnia, jeśli pliku logu jest większy niż 50 MB, jest on przenoszony do katalogu domowego klienta. Jeśli ustawisz opcję usuwania przetworzonych logów na aktywną, wtedy nie będą one przenoszone, a zamiast tego zostaną usunięte. Przeliczanie Twoich głównych statystyk nie zostanie naruszone.";
$__information['web_updateform_hotlink_protection_pre'] = "Twoja domena i poddomeny będą miały automatycznie dostęp do obrazków i nie będziesz ich musiał osobno dodawać. *.domena.pl jest automatycznie dodana do listy dozwolonych domen, które podasz tutaj. [b] Przekierowanie na obrazek [/b] musi być ścieżką obrazka wewnątrz Twojej domeny, a nie pełnym adresem URL. Powinna mieć taką formę (/img/noaccess.gif). Musisz wpisać domeny jako proste nazwy bez żadnych znaków specjalnych np. domena.pl, mojadomena.pl, mojedomeny.pl.";
$__information['mailqueue_list__pre'] = "Zniknięcie kolejki zabierze nieco więcej czasu, dlatego po kliknięciu Usuń emaile nadal będą widoczne w kolejce jeszcze przez pewien czas. Po prostu odśwież tą stronę za ok. minutę, aby sprawdzić czy emaile zostały już skasowane czy nie.";
$__information['mailqueue_updateform_update_pre'] = "Aby zobaczyć log dla poczty, wróć z powrotem do listy ikon, a następnie przeładuj jeden raz kolejkę emaili, ponieważ tylko log z ostatniej godziny został przetworzony.";
$__information['rubyrails_addform__pre'] = "Aplikacja będzie zwyczajnie dostępna pod adresem http://domena.pl/nazwaaplikacji. Ścieżką będzie /home/client/ror/domain.com/applicationname. Jeśli ustawisz flagę [b] dostępne bezpośrednio [/b], wtedy aplikacja będzie dostępna przez http://domena.pl.";
$__information['installapp_addform__pre'] = "Aby zainstalować aplikację w głównej ścieżce, pozostaw [b] Lokalizację [/b] pustą. Aby zainstalować tą samą aplikację dla innej domeny, użyj pola wyboru na górze, a następnie zmień domenę na inną, a będziesz miał możliwość użycia tego samego formularza z nową domeną tak jak poprzednio. Wiadomość z informacjami o nazwie użytkownika i adresie URL zostanie wysłana na email kontaktowy, który wprowadzisz tutaj.";
$__information['mysqldb_updateform_restore_pre'] = "Możesz użyć tej opcji tylko do odtworzenia kopii zapasowych, które zostały wykonane przez samo Kloxo używając zakładki [b] Pobierz kopię zapasową [/b]. Aby przywrócić zwykły plik zrzutu MySQL, użyj phpMyAdmin.";
$__information['domainipaddress_updateform_update_pre'] = "Ta opcja pozwala na przydzielenie określonego adresu IP dla domeny. Dzięki temu jeśli ktoś użyje adresu http://ip, wtedy pojawi się ścieżka dokumentu głównego dla domeny ustawionej tutaj.";
$__information['updateform_search_engine_pre'] = "Niektóre wyszukiwarki mogą wymagać potwierdzenia Twojego adresu e-mail w celu dodania strony. Nie wpisuj tutaj swojego głównego adresu e-mail, ponieważ możesz otrzymać niechciane wiadomości wiadomości. W celu uzyskania najlepszej pozycji potwórz tą operację co 3-4 tygodnie, jednak nie wcześniej, ponieważ możesz zostać zablokowany.";
$__information['updateform_domainpserver_pre'] = "Oto serwery, na których zostaną skonfigurowane domeny dla tego klienta. Jeśli zmienisz tutaj wartości, automatycznie wszystkie domeny zostaną przeniesione na odpowiednie serwery. Jeśli zmienisz [b] serwer poczty [/b] i klikniesz aktualizuj, wtedy [b] wszystkie [/b] konta pocztowe dla domen tego klienta zostaną przeniesione ze starego serwera na nowy. [b]  Szablon DNS [/b] to nowa konfiguracja serwerów DNS, na które zostaną przełączone wszystkie domeny. Upewnij się, że najpierw stworzysz szablon DNS, który odpowiada nowej konfiguracji, a następnie podasz go tutaj Kloxo. Zobacz więcej na dole odnośnie zmiany serwera. Możesz zrobić hurtową zmianę DNS później przechodząc do [b] Zarządzanie DNS -> Przeładuj [/b] i klikając [b] Aktualizuj wszystko [/b], co spowoduje zmiany szablonu DNS dla wszystkich domen na koncie.";
$__information['sslipaddress_updateform_update_pre'] = "Aby ustawić SSL dla adresu IP, najpierw wyślij/dodaj certyfikat SSL <url:goback=2&a=list&c=sslcert> tutaj </url>";
$__information['domain_addform__pre_docroot'] = "Pozostaw pustą główną ścieżkę dokumentu, a Kloxo automatycznie użyje domena.pl jako ścieżki głównej dokumentu.";
$__information['sslcert_updateform_update_pre_admin'] = "Aby przydzielić certyfikat SSL dla danego adresu IP, <url:goback=1&l[class]=pserver&l[nname]=localhost&a=list&c=ipaddress> kliknij tutaj </url>, a następnie wejdź do menu adresu IP i kliknij zakładkę [b] certyfikaty SSL [/b], a będziesz mógł ustawić jeden z tych certyfikatów dla danego adresu IP.";
// $__information['sslcert_updateform_update_pre'] = "Aby przydzielić certyfikat SSL dla danego adresu IP, <url:goback=2&a=list&c=ipaddress> kliknij tutaj </url>, a następnie wejdź do menu adresu IP i kliknij zakładkę [b] certyfikat SSL [/b], a będziesz mógł ustawić jeden z tych certyfikatów dla danego adresu IP. Administrator będzie musiał przydzielić wyłączny adres IP dla Ciebie, abyś mógł skorzystać z tej opcji.";
$__information['sslcert_updateform_update_pre'] = "Aby przydzielić certyfikat SSL dla danego adresu IP, <url:goback=2&a=list&c=ipaddress> kliknij tutaj </url>, a następnie wejdź do menu adresu IP i kliknij zakładkę [b] certyfikaty SSL [/b], a będziesz mógł ustawić jeden z tych certyfikatów dla danego adresu IP. Administrator będzie musiał przydzielić wyłączny adres IP dla Ciebie, abyś mógł skorzystać z tej opcji.";

$__information['domain_not_customer'] = "Aby dodać domenę, utwórz najpierw klienta, a następnie będziesz mógł dodać domeny na jego koncie. Aby dodać klienta, <url:a=addform&c=client&dta[var]=cttype&dta[val]=customer>kliknij tutaj </url>";
$__information['ipaddress_list__pre'] = "Wyłączny adres IP pozwoli Tobie na kontrolę nad określonym adresem IP. Jest przydatny dla SSL, a także ustawiania adresu IP dla domeny, dzięki czemu określony adres IP będzie wskazywał na domenę. Aby korzystać z wyłącznego adresu IP administrator musi najpierw dodać określony adres do Twojego konta. Aby ustawić SSL lub przydzielić IP dla domeny, kliknij na adres IP, a następnie kliknij na [b] konfiguracja SSL [/b] lub [b] konfiguracja domeny[/b].";
$__information['clientmail_list__pre'] = "Ta opcja pokazuje ilość e-maili wysyłanych przez Twoich klientów przez serwer WWW lub autoryzację SMTP w ciągu ostatnich dwóch dni. Jeśli jest to pełna nazwa konta email taka jak np. [b] uzytkownik@domena.pl [/b], wtedy odpowiada ona poczcie wysyłanej przez serwer SMTP. Jeśli jest to prosta nazwa użytkownika, wtedy odpowiada ona poczcie wysyłanej przez serwer WWW. Jeśli chcesz użyć mod_php na Apache wtedy wszystkie aplikacje internetowe będą uruchamiane jako użytkownik [b] apache [/b] i tylko [b] apache [/b] będzie tutaj wyświetlane. Użyj suPHP na Apache jeśli planujesz hosting dla osób trzecich. W ten sposób będziesz mógł zidentyfikować każdego klienta za pomocą jego systemowej nazwy użytkownika.";
$__information['servermail_updateform_update_pre'] = "To bardzo ważne, aby ustawić tutaj prawidłową rozwiązywalną nazwę hosta, ponieważ wiele publicznych serwerów e-mail jak np. onet.pl będzie odmawiać przyjęcia poczty z Twojego serwera. Możesz uruchomić serwer poczty na dodatkowym porcie podając go tutaj. Pozostaw puste pole, aby wyłączyć dodatkowy port SMTP. Maksymalna liczba wątków SMTP określa graniczną liczbę dopuszczalnych procesów SMTP. Powinieneś ustawić ją na pewną liczbę, np. 10 jeśli otrzymujesz dużą ilość niechcianych wiadomości. Jeśli pozostawisz puste pole, wartość ta będzie ustawiona na NIELIMITOWANĄ, co jest domyślne.";

$__information['updateform_switchprogram_pre'] = "Przełączanie programów zabierze trochę więcej czasu, ponieważ wymagane jest usunięcie starego programu ze systemu, " .
        "następnie instalacja nowego z użyciem yum. Log tej operacji będzie dostępny w pliku shell_exec. " . 
        "Wszystkie Twoje dane zostaną w niewidoczny sposób przeniesione. " .
        "Będziesz musiał odczekać ok. minuty zanim nowe usługi zostaną prawidłowo uruchomione.<br />" .
        "Wskazówka: Aktywacja 'Nie naprawiaj konfiguracji' oznacza nie przeprowadzanie naprawy konfiguracji - jest to ważne dla dużej liczby domen; " .
        "W takim wypadku musisz uruchomić ręcznie 'sh /script/fixweb; sh /script/fixdns ; sh /script/fixmail' w konsoli SSH serwera.";

$__information['updateform_permalink_pre'] = "Kloxo dostarczane jest z konfiguracją odnośników bezpośrednich dla wielu aplikacji. Wybierz aplikację i katalog, w którym ją zainstalowałeś, a Kloxo doda odpowiednią regułę rewrite do konfiguracji Lighttpd. Zwróć uwagę, że dla pewnych aplikacji, odnośniki bezpośrednie są osiągane poprzez ustawienie strony błędu 404, jak np. dla Wordpress.";
$__information['weblastvisit_list__pre'] = "Oto lista ostatnich 50 odwiedzających lub liczba odwiedzających w ciągu ostatnich 20 godzin, którakolwiek jest mniejsza. Czas rzeczywisty określa znacznik czasu unix i znajduje się on tutaj, dzięki czemu masz możliwość prawidłowego sortowania według czasu. Dłuższe wpisy są skracane, aby zmieściły się na ekranie. Możesz je zobaczyć w całości najeżdżając na nie myszką.";
$__information['subweb_a_addform__pre'] = "Oto prosta poddomena. Prosta poddomena ma tylko komponent sieci web i nie możesz dla niej dodać poczty czy zarządzać DNS. Jeśli chcesz dodać pełną poddomenę, użyj [b] przycisku poddomena [/b] na głównej stronie [b] domen [/b]. Ścieżka prostej poddomeny to /home/nazwaklienta/domena/domena.pl/poddomeny/nazwapoddomeny";
$__information['updateform_skeleton_pre'] = "Oto archiwum katalogu skeleton, które zostanie skopiowane do Twojego katalogu domowego po jego utworzeniu. Archiwum zostanie rozpakowane do nowo utworzonego katalogu domeny. Możesz użyć [b] &lt;%domainname%&gt; , &lt;%clientname%&gt; [/b] wewnątrz pliku index.html, a wszystkie zmienne będą poprawnie ustawione na prawidłowe wartości.";
$__information['updateform_lighty_rewrite_pre'] = "Oto niestandardowa reguła rewrite lighttpd, która zostanie bezpośrednio dopisana do pliku konfiguracyjnego bez żadnych zmian. Będzie miała ona postać [b] url.rewrite = ( ... [/b].  ";
$__information['updateform_custom_error_pre'] = "<p> Wskazówka: Wartości, które musisz podać to wirtualne ścieżki do plików, które będą pokazywane w przypadku wystąpienia błędów. Przykład: /pliki_bledow/404.html.</p>";
$__information['domain_updateform_ipaddress_pre'] = "<p> Wskazówka: Upewnij się, że dokonałeś odpowiednich zmian także w konfiguracji serwera nazw.  </p>";
$__information['client_updateform_ipaddress_pre'] = "<p> Wskazówka: Dostępna pula adresów IP jest wybierana z serwerów dostępnych w puli serwerów WWW. </p>";
$__information['domaintemplate_addform__pre'] = "<p> Wskazówka: Maksymalna wartość po prawej wskazuje Twój obecny limit powierzchni dyskowej. Możesz utworzyć szablon z wartościami przekraczającymi Twój obecny limit powierzchni dyskowej, ale nie będziesz miał możliwości ich użycia do utworzenia domen/klientów. </p>";
$__information['spam_updateform_update_pre'] = "<p> Liczba 'punktów', która może mieć wielkość 1-10, jest wartością, po której poczta będzie oznaczana jako SPAM. Jeśli ustawisz ją na niskie wartości, więcej emaili będzie oznaczane jako SPAM. Zbyt niskie wartości mogą spowodować, że właściwe emaile zostaną sklasyfikowane jako SPAM. Zbyt wysokie wartości mogą spowodować przechodzenie wysokiej ilości niechcianych wiadomości przez filtr. </p>";
$__information['web_updateform_enable_frontpage_flag_pre'] = "<p> Hasło Frontpage będzie takie samo jak to użytkownika systemu (główny użytkownik FTP). </p>";
$__information['ffile_show___lx_error_log_pre'] = "Oto log błędów dla Twojej domeny. Ta zawartość pomoże Tobie w rozwiązaniu problemów, jeżeli masz jakiekolwiek problemy dotyczące tej domeny.";
$__information['installappsnapshot_list__pre'] = "Zrzuty baz danych to dokładne kopie bazy danych i plików Twojej aplikacji w określonym czasie. Możesz przywrócić Twoją aplikację do danego zrzutu bazy danych klikając na przycisk [b] przywróć [/b].";
$__information['sshclient_updateform_disabled_pre'] = "Administrator nie aktywował dostępu do konsoli (SSH) dla Ciebie. Otwórz zgłoszenie w centrum zgłoszeń jeśli potrzebujesz dostępu SSH. ";
$__information['sshclient_updateform_warning_pre'] = "Zwróć uwagę, że cała aktywność jest monitorowana i każda próba dostępu do plików nienależących do Ciebie spowoduje blokadę Twojego konta hostingowego, dlatego działaj odpowiedzialne.";
$__information['ffile_show___lx_access_log_pre'] = "Oto log dostępu dla Twojej domeny. Możesz go pobrać klikając na zakładkę [b] pobierz [/b] po prawej stronie. Ten plik zawiera informacje o każdej pojedynczej odsłonie Twojej strony WWW.";
$__information['updateform_disable_url_pre'] = "Wszyscy Twoi klienci będą automatycznie dziedziczyć Twoje parametry blokad adresów URL. Aby wymusić Twoją blokadę adresów URL na nich, po prostu zablokuj im uprawnienie 'Możliwość ustawiania zablokowanych adresów URL' w opcjach uprawnień. Ta opcja to adres URL, na który zostanie przekierowana domena, gdy zostanie ona zablokowana.";
$__information['updateform_dnstemplatelist_pre'] = "Przydzielaj tylko jeden szablon DNS do klienta. Będzie to oznaczać, że Kloxo nie pokaże pola wyboru szablonu DNS podczas dodawania domeny, co nie będzie potem dziwić Twojego klienta.";
$__information['forward_a_addform__pre'] = "Lista przekierowanych adresów to lista adresów email, na które poczta będzie przekierowywana. Jedna kopia takiej poczty będzie zachowywana także na bieżącym koncie pocztowym. Możesz wyłączyć lokalne przechowywanie <url:a=updateform&sa=configuration>klikając tutaj </url>.";

// Dodano w Kloxo wersja 6.1.6 DO ZROBIENIA !! Potrzebne prawidłowe informacje.
$__information['vv_dns_srv_message'] = "Tutaj możesz zarządzać rekordami SRV.";
$__information['vv_dns_ddns_message'] = "Tutaj możesz zarządzać DDNS.";
$__information['vv_dns_mx_message'] = "Tutaj możesz zarządzać rekordami MX. Wpisz '__base__' jeśli chcesz uzyskać nazwę domeny podstawowej.";
$__information['vv_dns_ns_message'] = "Tutaj możesz zarządzać rekordami NS.";
$__information['vv_dns_aaaa_message'] = "Tutaj możesz zarządzać rekordami IPv6. Wpisz '__base__' jeśli chcesz uzyskać nazwę domeny podstawowej.";
$__information['vv_dns_txt_message'] = "Użyj &lt;%domain&gt; jeśli chcesz zawrzeć nazwę domeny wewnątrz rekordu TXT np.'v=spf1 include: &lt;%domain &gt;'.";
$__information['vv_dns_cname_message'] = "Tutaj możesz zarządzać rekordami CNAME.";
$__information['vv_dns_fcname_message'] = "Tutaj możesz zarządzać rekordami FCNAME. [b]FCNAME[/b] oznacza pełny CNAME i pozwoli Tobie, aby poddomena wskazywała na zewnętrzną domenę.";
$__information['vv_dns_a_message'] = "Tutaj możesz zarządzać rekordami A. Wpisz '__base__' jeśli chcesz uzyskać nazwę domeny podstawowej.";
$__information['vv_dns_soa_message'] = "Tutaj możesz zarządzać rekordami SOA.";
$__information['vv_dns_rebuild_message'] = "Tutaj możesz przebudować strefy Twojej domeny ze szablonu DNS.";

// Dodano w Kloxo 6.1.7
// $__information['vv_dns_template_message'] = "[b]Podstawowy i zapasowy serwer DNS[/b]<br />Dozwolone tylko nazwy hosta.";
// Modified on 6.2.0
$__information['vv_dns_template_message'] = "[b]Podstawowy i zapasowy serwer DNS[/b] - 'domyslne.dns' to 'symboliczna' nazwa domeny po wybraniu 'domyslne' dla 'Nazwy szablonu DNS'. " .
	"[b]Przykład[/b] - 'ns1.domyslne.dns' (dla 'Podstawowy serwer DNS') zostanie przekształcone na 'ns1.domena.pl' dla 'domena.pl'";

// Zmieniono w Kloxo wersja 6.1.6
$__information['vv_dns_blank_message'] = "<p>Zarządzanie DNS</p>";

$__emessage['blocked'] = "Twój adres jest zablokowany";
$__emessage['no_server'] = "Nie można się połączyć z serwerem.";
$__emessage['set_emailid'] = "Wpisz swój identyfikator email poprawnie.";
$__emessage['no_socket_connect_to_server'] = "Nie można się połączyć z serwerem [%s]. Jest to najprawdopodobniej spowodowane przez zwykły błąd sieci. Upewnij się, że serwer jest dostępny dla tego poszczególnego węzła uruchamiając [b] telnet identyfikator-serwera-podrzędnego 7779 [/b]   ";
$__emessage['restarting_backend'] = "Trwa ponowne uruchamianie podsystemu. Spróbuj ponownie za 30 sekund.";
$__emessage['quota_exceeded'] = "Limit powierzchni dyskowej przekroczony dla [%s]";
$__emessage['license_no_ipaddress'] = "Publiczny adres IP [%s] tego serwera nie został znaleziony w bazie licencji. Skontaktuj się z działem sprzedaży firmy Lxlabs w celu utworzenia licencji dla tego serwera. </a> ";
$__emessage['ssh_root_password_access'] = "Nie zablokowałeś dostępu użytkownika root za pomocą hasła na tym serwerze. Dostęp użytkownika root za pomocą hasła nie jest konieczny, ponieważ możesz zarządzać autoryzowanymi kluczami SSH za pomocą samego HyperVM. <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=sshconfig> Kliknij tutaj </url>, aby skonfigurować swój serwer SSH.";
$__emessage['already_exists'] = "Nazwa zasobu [%s] już istnieje.";
$__emessage['lxguard_not_configured'] = "Lxguard nie jest skonfigurowany na tym serwerze. <url:k[class]=pserver&k[nname]=localhost&a=show&o=lxguard>Kliknij tutaj, aby skonfigurować Lxguard </url>, ponieważ to bardzo ważne, abyś rozumiał do czego on służy. Lxguard jest krytyczny dla bezpieczeństwa Twojego serwera. W tym samym czasie, może on zablokować dostęp do serwera dla Twojego własnego adresu IP, co może być bardzo frustrujące jeśli nie będziesz wiedział co się dzieje.";
$__emessage['root_cannot_extract_to_existing_dir'] = "Katalog, który podałeś już istnieje. Użytkownik root nie może rozpakowywać archiwum do już istniejącego katalogu. Wprowadź nazwę katalogu, który nie istnieje w systemie.";
$__emessage['no_imagemagick'] = "Nie ma rozszerzenia ImageMagick w systemie. Możesz zainstalować ImageMagick uruchamiając w konsoli serwera polecenie [b] yum -y install imagemagick [/b].";
$__emessage['warn_license_limit'] = "Jesteś bardzo blisko osiągnięcia limitu licencji dla [%s]. Jeśli system przekroczy limit dla [%s], interfejs przestanie działać i nie będziesz mógł zarządzać systemem. Zwiększ ilość licencji na stronie client.lxlabs.com i dokonaj jej aktualizacji <url:o=license&a=show> klikając tutaj </url>";
$__emessage['file_already_exists'] = "Plik [%s] już istnieje.";
$__emessage['contact_set_but_not_correct'] = "Twoje dane kontaktowe nie zawierają prawidłowego adresu email. Kliknij <url:a=updateform&sa=information> tutaj to naprawić.</url> ";
$__emessage['contact_not_set'] = "Twoje dane kontaktowe nie są ustawione prawidłowo. Kliknij <url:a=updateform&sa=information> tutaj, aby to naprawić. </url> ";
$__emessage['you_have_unread_message'] = "Masz [%s] nieprzeczytanych wiadomości. Kliknij <burl:a=list&c=smessage> tutaj, aby je odczytać. </burl>";
$__emessage['you_have_unread_ticket'] = "Masz [%s] nieprzeczytanych zgłoszeń. Kliknij <burl:a=list&c=ticket> tutaj, aby je odczytać. </burl>";
$__emessage['security_warning'] = "Twoje hasło jest obecnie ustawione na hasło domyślne, co stanowi poważne zagrożenie bezpieczeństwa. Zmień hasło natychmiast <url:a=updateform&sa=password> klikając tutaj. </url> ";
$__emessage['ssh_port_not_configured'] = "Port SSH tego serwera nie jest ustawiony. Jest zalecane, aby zmienić go na port inny niż domyślny 22. <url:a=show&o=sshconfig> Kliknij tutaj, aby go zmienić:</url>. Jeśli chcesz zachować SSH na porcie 22 i uniknąć wyświetlania się tego komunikatu, przejdź do wskazanej strony i ustaw go na stałe na 22, dzięki czemu to ostrzeżenie nie będzie ponownie wyświetlane.";
$__emessage['system_is_updating_itself'] = "System w tej chwili uaktualnia się i dlatego nie będziesz miał możliwości dokonywania jakichkolwiek zmian przez kilka minut. Wszystkie operacje nie wymagające zapisywania będą jednak działać poprawnie.";
$__emessage['system_is_locked'] = "Ktoś rozpoczął operację wymagającą modyfikacji systemu na tym określonym obiekcie, która nadal trwa. Nie będziesz miał możliwości dokonywania jakichkolwiekzmian dopóki nie zostanie ona zakończona. Wszystkie operacje nie wymagające zapisywania będą jednak działać poprawnie.";
$__emessage['system_is_locked_by_u'] = "Rozpocząłeś operację wymagającą modyfikacji systemu na tym określonym obiekcie, która nadal trwa. Nie będziesz miał możliwości dokonywania jakichkolwiek zmian dopóki nie zostanie ona zakończona. Wszystkie operacje nie wymagające zapisywania będą jednak działać poprawnie.";
$__emessage['smtp_server_not_running'] = "hyperVM nie może się połączyć z serwerem SMTP na tym serwerze. Oznacza to, że hyperVM nie będzie w stanie wysłać jakichkolwiek emaili. Jest to krytyczne, ponieważ hyperVM monitoruje poprawność działania całego klastra i wysyła email do administratora, w przypadku stwierdzenia jakichkolwiek błędów. Powinieneś upewnić się czy usługa SMTP działa na tym serwerze. Po ponownym uruchomieniu usługi SMTP, odczekaj 5 minut, aby zniknął ten komunikat błędu, ponieważ hyperVM sprawdza dostępność usług tylko co każde 5 minut.";
$__emessage['template_not_owner'] = "Nie jesteś właścicielem tego szablonu";
$__emessage['ipaddress_changed_amidst_session'] = "Adres IP zmienił się w trakcie trwania sesji. Prawdopodobnie jest to próba przechwycenia sesji.";
$__emessage['more_than_one_user'] = "Więcej niż jeden użytkownik jest zalogowany na tym koncie. Kliknij <burl:a=list&c=ssession>tutaj, aby zobaczyć listę nazw użytkowników. </burl> ";
$__emessage['login_error'] = "Logowanie nie powiodło się";
$__emessage['file_exists'] = "plik (pliki) [%s] istnieje (istnieją). Wklejanie anulowano...";
$__emessage['cannot_unzip_in_root'] = "Nie możesz rozpakować plików archiwum zip do katalogu root. Wskaż katalog, do którego mają zostać rozpakowane pliki.";
$__emessage['nouser_email'] = "Email nie pokrywa się z emailem kontaktowym użytkownika";
$__emessage['session_expired'] = "Sesja wygasła";
$__emessage['e_password'] = "Nieprawidłowe hasło";
$__emessage['is_demo'] = "[%s] jest zablokowane w wersji demo.";
$__emessage['user_create'] = "Użytkownik [%s] nie może zostać stworzony. Spróbuj inną nazwę.";
$__emessage['switch_done'] = "Przełączenie serwerów zostało uruchomione w tle. Otrzymasz email, gdy proces przełączania zostanie ukończony.";
$__emessage['mis_changed'] = "Zmiana konfiguracji wyświetlania powiodła się.";
$__emessage['password_sent'] = "Hasło zostało zresetowane i wysłane poprawnie.";
$__emessage['added_successfully'] = "[%s] został prawidłowo dodany.";
$__emessage['backup_has_been_scheduled'] = "Kopia zapasowa wykonuje się obecnie w tle. Otrzymasz email na swój adres kontaktowy po jej zakończeniu.";
$__emessage['update_scheduled'] = "Aktualizacja jest właśnie dokonywana w tle. Możesz odświeżyć tą stronę, aby zobaczyć czy aktualizacja została prawidłowo zakończona.";
$__emessage['restore_has_been_scheduled'] = "Przywracanie dokonuje się obecnie w tle. Otrzymasz email na swój adres kontaktowy po jego zakończeniu.";
$__emessage['same_dns'] = "Serwer główny i podrzędny nie mogą się znajdować na tym samym serwerze.";
$__emessage['user_exists'] = "Użytkownik [%s] już istnieje.";
$__emessage['mysql_error'] = "Błąd MySQL, baza danych zgłasza: [%s]";
$__emessage['this_domain_does_not_resolve_to_this_ip'] = "Aby adres IP wskazywał na domenę, domena musi odpowiadać na ten sam adres IP, w przeciwnym wypadku domena przestanie działać. Domena, którą próbujesz przydzielić do tego adresu IP, nie odpowiada z takim samym IP, więc nie może zostać ustawiona jako domena domyślna dla tego adresu IP.";
$__emessage['dns_conflict'] = "Domena nie została dodana z powodu błędu w ustawieniach DNS. Sprawdź swój szablon DNS i zweryfikuj go. Komunikat ze serwera DNS to [%s]";
$__emessage['add_without_www'] = "Powinieneś dodać tylko domenę główną w formacie domena.pl. Poddomena [b] www [/b] będzie do niej automatycznie dodana. Nie powinieneś dodawać [b] www [/b] tworząc domenę.";
$__emessage['could_not_connect_to_db'] = "Nie można połączyć się z bazą danych: Błąd został zalogowany. Skontaktuj się z administratorem.";
$__emessage['e_no_dbadmin_entries'] = "Nie ma żadnych wpisów baz danych na tym określonym serwerze. Skontaktuj się ze swoim administratorem w celu ich ustawienia.";
$__emessage['please_add_one_domain_for_owner_mode'] = "Musisz mieć co najmniej jedną domenę jeśli chcesz przełączyć się do trybu właściciela domeny. Możesz dodać domenę <url:a=addform&c=domain>klikając tutaj </url>.";
$__emessage['e_no_dbadmin_entries_admin'] = "Nie zostały skonfigurowane wpisy administratora bazy danych na tym określonym serwerze. Musisz wejść do sekcji serwery na tym serwerze, a następnie kliknąć na ikonę Administrator bazy danych, po czym dodać administratora baz danych i jego hasło na tym określonym serwerze i typie bazy danych.";
$__emessage['mail_server_name_not_set'] = "Nazwa identyfikacyjna Twojego serwera poczty nie została ustawiona. Oznacza to, że wiele publicznych serwerów poczty takich jak np. onet.pl będzie odrzucać emaile z Twojego serwera. Kliknij <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=servermail> tutaj, aby ją ustawić. </url>";
$__emessage['dns_template_inconsistency'] = "Szablon DNS, który wybrałeś nie pokrywa się z wyborem Twoich serwerów np. adres IP w konfiguracji DNS mógł zostać zupełnie nie odnaleziony na serwerze WWW. Powróć do poprzedniej strony i utwórz szablon DNS, który ma parametry pokrywające się konfiguracją serwera.";
$__emessage['adding_cron_failed'] = "Dodawanie zadania do harmonogramu zadań (Cron) nie powiodło się z powodu [%s]. Usuń je i dodaj ponownie.";
$__emessage['se_submit_running_background'] = "Dodawanie do wyszukiwarek jest obecnie uruchomione w tle. Otrzymasz wiadomość na swój adres kontaktowy, gdy zostanie ono ukończone.";
$__emessage['err_no_dns_template'] = "Nie zostały utworzone szablony DNS w tym systemie. Musisz dodać co najmniej jeden szablon DNS, aby dodać domenę/klienta. Kliknij <url:a=addform&c=dnstemplate> tutaj, aby dodać szablon DNS. </url></p> ";
$__emessage['certificate_key_file_empty'] = "Certyfikat i plik klucza, który wybrałeś jest pusty. Musisz je najpierw stworzyć lub wysłać przed aktywowaniem SSL";
// wydanie Kloxo 6.1.7
// utworzone przez mustafa.ramadhan@lxcenter.org

$__information['webserver_config'] = 
	"[b]Gałąź PHP[/b] - Wersja PHP bazująca na podwersjach - ".
		"php-fpm dla 'php52' może nie działać; ".
		"sprawdź wynik za pomocą polecenia 'php -v' w konsoli SSH, aby odnaleźć błędy (przeważnie niekompatybilne moduły).<br />".
		"&nbsp;&nbsp;&nbsp;&nbsp;- Najlepiej wykonać ponowne uruchomienie serwera po zmianach, zwłaszcza w przypadku użycia Lighttpd, Nginx lub Apache z 'php-fpm' jako 'typu PHP'.<br />".
	"[b]Typ PHP[/b] - Bazujący na procesach (httpd-prefork/-itk), wątkach (httpd-worker/-event) lub ".
		"bezpiecznym środowisku (suphp/php-fpm/ruid2/itk/fcgid)<br />".
	"[b]Optymalizacja pamięci Apache[/b] - Optymalizacja użycia pamięci - ".
		"ustawia połowę zasobów dla [b]nginx/lighttpd-proxy[/b]; ".
		"wybierz 'default' jeżeli wybrałeś 'php-fpm' jako 'Typ PHP'<br />".
	"[b]Konwersja tabel baz danych MySQL[/b] - MyISAM (używa mniej pamięci; oszczędność 100-200 MB) lub ".
		"InnoDB (wyższa wydajność)<br />".
	"[b]Napraw 'właścicieli' i 'uprawnienia'[/b] - Zabezpiecza przed błędem '500 Wewnętrzny Błąd Serwera' w bezpiecznym środowisku. ".
	"<br /><br />* Dodaj wpis '[b]AddHandler application/x-httpd-php52 .php[/b]' w pliku .htaccess, aby użyć PHP 5.2 jako drugiej wersji PHP razem z PHP 5.3/5.4 jako podstawowego PHP.".
	"<br />* Jeżeli ustawiłeś [b]suphp/suphp_worker/suphp_event[/b], wybierz 'fix-ALL', aby zapobiec błędowi '500 Wewnętrzny Błąd Serwera'";
// Zawartość językowa dla zgłoszenia #656
// utworzona przez Andrew Ying
$__emessage['document_root_may_not_contain_spaces'] = "Ścieżka główna dokumentu nie może zawierać żadnej spacji na końcu ani przed ukośnikiem. Sprawdź to i spróbuj dodać ponownie.";

// wydanie Kloxo 6.2.0
// utworzone przez mustafa.ramadhan@lxcenter.org

$__information['php_config'] = "Po aktywacji tej opcji, Kloxo zainstaluje najpierw plik rpm Xcache/Ioncube/Zend/Suhosin rpm wewnątrz katalogu /home/rpms " .
	"Jeśli nie istnieją spróbuj zainstalować za pomocą yum. Instalacja tych modułów zależy od gałęzi PHP i wersji zainstalowanej w systemie.<br />" .
	"[b]Przykład[/b]: jeśli system używa gałęzi php53u, Kloxo sprawdzi najpierw php53u-xcache i jeśli on nie istnieje to sprawdzi php-xcache. " .
	"Jest ot najprawdopodobniej błąd kompatybilności. Spróbuj komendy 'php -v', aby się upewnić.";

$__information['reverse_dns'] = "Odwrotne DNS działa tylko dla bloku klasy C (256 adresów IP) lub więcej.";