<?php
/*
 *    HyperVM, Server Virtualization GUI for OpenVZ and Xen
 *
 *    Copyright (C) 2000-2009    LxLabs
 *    Copyright (C) 2009-2012    LxCenter
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

$__information['ndskshortcut_list__pre'] = " Możesz dodać stronę w Kloxo do ulubionych, klikając na [b] dodaj do ulubionych [/b] na [b] poszczególnej stronie. [/b] Każdy skrót ma parametr zwany [b] ID sortowania [/b]. Ustawiając odpowiedni [b] ID sortowania [/b] na każdym z linków, a następnie sortując całą listę za pomocą [b] ID sortowania [/b], możesz dostosować listę tak jak chcesz. Pasek narzędzi na górze odpowiada dokładnie temu w jaki sposób ta lista jest posortowana.";
$__information['sshauthorizedkey_addform_lxlabs_pre'] = "W ten sposób dodasz klucz SSH firmy LxLabs do swoich autoryzowanych kluczy, co pozwoli wsparciu technicznemu firmy LxLabs na zalogowanie się do Twojego serwera bez znajomości hasła. Jest to zalecane jeśli prosiłeś o pomoc z firmy LxLabs.";
$__information['rawlxguardhit_list__pre'] = "Oto lista bezpośrednich połączeń. Jest to przydantne do śledzenia adresów IP, jeśli znasz nazwę konta użytkownika np. jeśli Twoi klienci próbują zalogować się do serwera i zrobią to zbyt wiele razy, to zostaną zablokowani. Ta strona ma [b] zaawansowane wyszukiwanie [/b], gdzie możesz przeszukiwać listę za pomocą [b] nazwy użytkownika [/b] , i w ten sposób możesz dowiedzieć się jaki ma on adres IP oraz usunąć go ze strony głównych połączeń.";
$__information['login_pre'] = "<p> Witaj w <%programname%>  </p><p>Użyj prawidłowej nazwy użytkownika i hasła, aby uzyskać dostęp do panelu administracyjnego. </p> ";
$__information['tickethistory_addform__pre'] = "Możesz użyć &#91quote&#93 &#91/quote &#93, aby zacytować trochę tekstu, który zostanie prawidłowo sformatowany. Możesz także użyć &#91code&#93 &#91/code&#93 dla fragmentów kodu, oraz &#91b&#93 &#91/b&#93 dla pogrubionej czcionki.";
$__information['lxguardwhitelist_addform__pre'] = "Jest zalecane, abyś używał przycisku [b] białej listy [/b] na górze <url:a=list&c=lxguardhitdisplay>strony połączeń</url>, aby dodać adres IP do białej listy. Wpisując ręcznie adres IP możesz się pomylić i potem się zdzwić. Jeśli wpisujesz swój adres IP tutaj, sprawdź dwukrotnie czy jest on poprawny.";
$__information['sshconfig_updateform_update_pre'] = "Jest zalecane, abyś całkowicie wyłączył dostęp za pomocą hasła do tego serwera i zamiast niego użył <url:goback=1&a=list&c=sshauthorizedkey>menedżera autoryzacji kluczy SSH </url>, aby pozwolić poszczególnym osobom na dostęp bez znajmości hasła. Jeżeli jest to hyperVM, a Ty masz zamiar sprzedawać serwery VPS innym osobom, nie będziesz miał możliwości całkowitego wyłączenia dostępu do SSH za pomocą hasła, ponieważ użytkownicy serwerów VPS muszą się zalogować do serwera głównego, aby otrzymać dostęp do swoich konsoli. W takim wypadku, upewnij się, że całkowicie wyłączyłeś dostęp do konsoli root dla tego serwera. Więc jako zasadę w Kloxo, przyjmij wyłączenie dostępu za pomocą hasła do wszystkiego, podczas gdy na hyperVM, wyłącz hasło do tylko do konsoli roota.";
$__information['all_dns_list__pre'] = "Oto lista wszystkich serwerów DNS stworzonych przez Twoich klientów VPS. <url:o=general&a=updateform&sa=reversedns> Kliknij tutaj </url>, aby skonfigurować serwery DNS w taki sposób, aby wszyscy klienci mogli ich używać. Menedżer DNS HyperVM pozwala właścielowi serwera VPS na stworzenie serwera DNS bezpośrednio w hyperVM i wszystkie dane zostaną zachowane na serwerach dostawcy. Innymi słowy pozwala to na dostarczanie klientom VPS serwerów DNS na Twoich serwerach.";
$__information['actionlog_list__pre'] = "Logi ostatnich akcji przechowują wszystkie komendy wykonywane przez klienta na serwerze. Ważną rzeczą, którą powinieneś zauważyć tutaj to fakt, że zewnętrzny login osoby zalogowanej jest tutaj prawidłowo logowany, dlatego nigdy nikomu nie powinieneś dawać dostępu do swojego głównego konta, a po prostu stworzyć <url:a=list&c=auxiliary> identyfikatory zewnętrzne </url> dla każdego ze swoich pracowników.";
$__information['sshauthorizedkey_list__pre'] = "Zauważ, że plik ~/.ssh/authorized_keys2 jest przestarzały jeśli chodzi o OpenSSH w wersji 3 i tylko plik ~/.ssh/authorized_keys jest zarządzalny. Są to klucze SSH serwerów, które mogą się zalogować do tego serwera bez podawania hasła. Upewnij się, że przechowujesz tą listę jak najkrótszą.";
$__information['updateform_forcedeletepserver_pre'] = "Wymuś usunięcie serwera po prostu usuwa serwer z bazy danych hyperVM. Jest to przydatne, gdy serwer został całkowicie usunięty i nie jest więcej dostępny.";
$__information['allowedip_addform__pre'] = "Ta opcja blokuje tylko dostęp do panelu serwera i nie zablokuje dostępu do aktualnych zasobów. Możesz dodać adres IP z puli [b] 192.168.1.*[/b]  lub z innych podziałów sieci. Zamiast podawać liczbę, możesz użyć symbolu [b] * [/b] zamiast całej puli adresów. Możesz także dodać poszczególne adresy IP w postaci 192.168.1.2. Zauważ, że kropki są wymagane i musisz podać wszystkie cztery pola. Jeśli chcesz zezwolić na dostęp wszystkim, usuń wszystkie dozwolone adresy IP, lub wpisz [b] *.*.*.* [/b]. Inne zapisy adresów IP nie są wspierane w tym momencie.";
$__information['blockedip_addform__pre'] = "Ta opcja blokuje tylko dostęp do panelu serwera a nie do aktualnych zasobów. Oto lista zablokowanych adresów IP. Zapis adresów IP jest taki sam jak dozwolonych IP. Powinieneś dodać zablokowane adresy IP tylko wtedy jeśli lista dozwolonych adresów jest pusta. Jeśli lista dozowolonych adresów nie jest pusta, wtedy automatycznie wszystkie adresy nie znajdujące się na tej liście zostaną zablokowane.";
$__information['updateform_portconfig_pre'] = "Ta strona służy do konfiguracji portów Kloxo/HyperVM. Po dokonaniu zmian tutaj, musisz uruchomić ponownie usługę Kloxo/HyperVM, aby zmiany uległy zastosowaniu. Uruchom tą komendę [b] cd /usr/local/lxlabs/<%program%>/httpdocs ; lphp.exe ../bin/common/misc/defaultport.php [/b] i wszystkie porty zostaną przywrócone do wartości domyślnych. Możesz później uruchomić ponownie Kloxo/HyperVM. Pozostaw wszystkie pola puste, aby przwrócić wartości domyślne. ";
$__information['updateform_schedule_conf_pre'] = "Zauważ, że są tutaj tylko zaplanowane kopie zapasowe tj. kopie zapasowe, których nazwa zaczyna się na <%program%>-scheduled będą podmieniane. Jeśli stworzyłeś kopię zapasową ze swoją własną nazwą, nie będzie ona podmieniana. Jeśli chcesz, aby ręcznie stworzona kopia zapasowa była podmieniana, wprowadź początkowy ciąg taki jak [b] <%program%>-scheduled- [/b]";
$__information['updateform_ssl_kloxo_pre'] = "Ta opcja ustawia certyfikat SSL dla <%program%> jako określony certyfikat. Upewnij się, że uruchomiłeś ponownie <%program%> po ustawieniu go tutaj.";
$__information['updateform_ssl_authorized_keys_pre'] = "Oto lista kluczy SSH z serwerów, które są autoryzowane do zalogowania na Twoje konto bez znajomości hasła. Każde jest przechowywane w osobnej linii. Możesz dodać klucze do serwerów, które chcesz, aby miały dostęp bez hasła do tego serwera. Powinieś utrzymywać ten plik w postaci najkrótszej jak to możliwe, aby zredukować szanse na zalogowanie się osobom niepowołanym";
$__information['updateform_ssl_hypervm_pre'] = "Ta opcja ustawia certyfikat SSL dla <%program%> jako określony certyfikat. Upewnij się, że uruchomiłeś ponownie <%program%> po ustawieniu go tutaj.";
$__information['updateform_selfbackupconfig_pre'] = " To opcja służy przede wszystkim do konfiguracji zdalnej kopii zapasowej bazy danych serwera głównego i nic poza tym. Zrzut bazy danych jest wykonywany codziennie i zapisywany w lokalnym katalogu na tym serwerze. Jest to głównie przydatne w konfiguracji dużego klastra, gdzie awaria serwera głównego ma większe konsekwencje.";
$__information['lxguard_updateform_update_pre'] = " Lxguard zabezpiecza przed atakami typu brute force monitorując logi SSH i FTP i blokując adresy IP, które mają zbyt wiele nieudanych prób zalogowania na serwer. Lxguard jest domyślnie włączony i będzie automatycznie blokował hosty. Nie ma możliwości jego wyłączenia. Możesz skonfigurować LxGuard określając [b] odstęp zablokowanych prób [/b] lub dodając adres IP do białej listy. Jeśli adres IP jest znajduje się na białej liście, nie zostanie zablokowany, nawet, gdy przekroczy liczbę nieudanych prób logowania. Aby usunąć ostrzeżenia kliknij na pole akceptacji poniżej";
$__information['updateform_generalsetting_pre'] = " Adres URL do 'Centrum zgłoszeń' to link do twojego Centrum zgłoszeń, które służy jako domyślne centrum pomocy wbudowane w oprogramowanie. Adres URL społeczności to link klienta, który będzie on widział po lewej stronie i w większości wypadków skieruje go do forum.";
$__information['custombutton_addform__pre'] = " W adresie URL, możesz użyć %nname%, które zostanie podmienione na nazwę klienta. Tylko dla Kloxo, możesz użyć %default_domain% jako domyślną domenę klienta.";
$__information['updateform_download_config_pre'] = "Zazwyczaj ściągając pliki serwer główny tworzy sesję tymczasowo, a następnie przekierowuje przeglądarkę bezpośrednio na serwer podrzędny. Ma to na celu oszczędność pasmo, ponieważ inaczej pliki będą przechodzić przez serwer główny. Jeśli włączysz tą opcję, hyperVM użyje innej trasy dla plików przez serwer główny sam w sobie. Jest to użyteczne, jeśli przydzieliłeś serwerom podrzędnym lokalne adresy IP i nie są one dostępne z zewnątrz dla reszty świata.";
$__information['updateform_login_options_pre'] = " Wskazówka: czas wygaśnięcia sesji nie może być mniejszy niż 100. Jeśli będzie mniejszy to zostanie automatycznie ustawiony na 100.";
$__information['resourceplan_change_pre'] = " Wskazówka: Jeśli zmienisz wartości tutaj, każde konto, które używa tego pakietu zostanie uaktualnione o nowe parametry. Kliknij <url:a=updateForm&sa=account>tutaj, aby zobaczyć konta używające tego pakietu</url>";
$__information['lxbackup_updateform_backup_pre'] = " Plik kopii zapasowej pojawi się w katalogu __backup na Twoim koncie. Możesz się do niego dostać klikając na zakładkę 'Menedżer plików'. Aby przywrócić kopię zapasową, możesz najpierw wysłać ją na serwer używając zakładki [b] wysyłanie [/b]. Możesz wysłać plik kopii zapasowej bezpośrednio lub adresu URL http lub z serwera FTP. Następnie powrócić tutaj i kliknij na ikonę [b] katalogu [/b] po prawej od formularza [b] przywracania [/b]. To pozwoli Tobie wskazać określony plik. Następnie kliknij na [b] uruchom proces przywracania [/b]. Zauważ, że kopia zapasowa <%program%> jest hierarchiczna. Jeśli stworzysz kopię zapasową danego zasobu, wtedy wszystko znajdujące się pod nim będzie automatycznie dołączone. Jeśli tworzysz kopię zapasową administratora, wtedy nie musisz tworzyć oddzielnie kopii zapasowej klientów.";
$__information['phpini_updateform_edit_admin_pre'] = "Musisz aktywować pole obok [b] Zarządzanie konfiguracją PHP [/b], aby zezwolić na całkowite zarządzanie plikiem php.ini. Zauważ, że Twoja stara konfiguracja pliku php.ini będzie nadpisana. Aby przywrócić Twój stary plik php.ini, po prostu wyłącz [b] Zarządzanie konfiguracją PHP [/b], a następnie przeprowadź aktualizację. Jest zalecane, aby Kloxo całkowicie sterowało Twoją konfiguracją PHP. Zapytaj na naszym forum jeśli potrzebujesz specjalnych funkcji.";
$__information['client_updateform_wall_pre'] = " Wskazówka: Ta wiadomość będzie wysłana tylko do Twoich bezpośrednich poddanych (poziom niżej, włączając to konto), którzy mają ustawiony email kontaktowy. ";
$__information['ffile_updateform_upload_pre'] = " Jeśli chcesz wysłać kilka plików/katalogów, utwórz archiwum zip i wyślij je; możesz je rozpakować wewnątrz menedżera plików.  ";
$__information['dskshortcut_a_list__pre'] = " Aby dodać stronę do ulubionych, kliknij na link [b] dodaj do ulubionych [/b], który pojawia się na górze po prawej stronie. Możesz kliknąć na ulubione poniżej i zmienić nazwę wpisu na coś bardziej rozpoznawalnego przez Ciebie. Możesz kliknąć na nagłówek [b] opis [/b] i ta lista będzie posortowana według tego pola a następnie odświeży całą ramkę. Aktualna lista ulubionych po lewej stronie dokładnie odzwierciedla porządek, który jest widoczny tutaj.";
$__information['ticketconfig_updateform_ticketconfig_pre'] = " Konto mailgate to konto, z którego <%program%> pobierze wszystkie emaile, w określonym czasie, a następnie zostaną one przetworzone i dodane do centrum zgłoszeń. Wysyłając emaile, <%program%> wyśle emaile pochodzące z tego adresu, który skonfigurujesz. Adres ma formę [b] konto@domena.pl [/b]. Serwer to serwer POP, z którego zostaną pobrane emaile. [b] serwer.pl [/b] . Jeśli zaznaczysz pole [b] użyj SSL [/b], wtedy poczta zostania pobrana używając pop3-ssl na porcie 995. Jest zawsze zalecane, abyś używał ssl, ale musisz się upewnić, że zdalny serwer poczty wspiera usługę pop3-ssl na porcie 995. ";
$__information['updateform_mysqlpasswordreset_pre'] = "Ta opcja powinna być używana tylko, gdy zgubiłeś hasło roota do bazy danych MySQL. W innych okolicznościach, możesz zmienić hasło klikając <url:a=list&c=dbadmin>tutaj (administrator baz danych)</url>. Pamiętaj o zachowaniu cierpliwości, ponieważ wykonanie tej operacji może zabrać nieco czasu. Ustawi ona nowe hasło roota do bazy danych MySQL uruchamiając je z opcją skip-grant-tables. Jeśli ta funkcja nie zadziała, zaloguj się za pomocą SSH i uruchom komendę ../bin/common/misc/reset-mysql-root-password.php ";
$__information['updateform_pserver_s_pre'] = "Oto pula serwerów dla sprzedawców. Pokazuje ona listę serwerów, których sprzedawcy mogą używać tworząc klienta tzn. tworząc nowego klienta sprzedawca będzie miał możliwość przydzielenia serwerów z listy do niego dla niego.";
$__information['general_updateform_disableper_pre'] = " Oto wartość procentowa zużycia po, której konto zostanie zablokowane. Domyślna wartość to 110%. Otrzymasz ostrzeżenia, gdy zużycie osiągnie odpowiednio 90,100,110%. ";
$__information['updateform_ftp_conf_pre'] = "Jeśli włączyłeś opcję [b] nie przechowuj lokalnej kopii [/b], plik lokalny będzie usunięty. Możesz tego używać jeśli chcesz oszczędzać miejsce na swoim koncie.";
$__information['vv_updateform_skin_logo_pre'] = " Aby wymusić własne logo w panelach klienckich, po prostu wyłącz uprawnienie 'możliwość zmiany loga' w ustawieniach uprawnień. ";
$__information['pserver_updateform_information_pre'] = "FQDN to bardzo ważne pole i powinno zostać ustawione na nazwę domeny, która prawidłowo wskazuje na ten serwer. W momencie ustawienia FQDN, hyperVM używje tej wartości do dalszej komunikacji sieciowej, i jeśli FQDN jest ustawione źle, komunikacja sieciowa pomiędzy serwerem głównym/podrzędnym nie powiedzie się. Jeśli pozostawisz to pole puste, hyperVM użyje pierwsze adresu IP na tym serwerze do komunikacji. Ustaw FQDN na nazwę hosta używaną wszędzie do dostępu do tego serwera.";
$__information['pserver_addform__pre'] = "Jeśli na nowo zainstalowałeś serwer podrzędny, jego hasłem jest admin. Jest zalecane, aby dodać serwery w postaci ich nazw, a nie za pomocą adresu IP. Serwer powinien być dostępny z poziomu serwera głównego używając określonej nazwy wpisanej przez Ciebie tutaj np. serwer.domena.pl. Identyfikator najwyższego stopnia to ciąg, który może być użyty do opisania tego serwera i będzie widoczny na innych serwerach.";
$__information['updateform_upload_logo_pre'] = " Pozostaw pola puste, aby ustawić loga na domyślny obrazek. Aby wymusić własne logo w panelach klienckich, po prostu wyłącz uprawnienie 'możliwość zmiany loga' w ustawieniach uprawnień.  ";
$__information['web_updateform_extra_tag_pre'] = " <b><font color=red> Ostrzeżenie!!!!! </font></b>  Cokolwiek wpiszesz tutaj zostanie to bezpośrednio wpisane do Wirtualnego Hosta. Jeśli pojawi się tutaj błąd składni, może to uniemożliwić ponowne uruchomienie serwera WWW. Ta opcja jest dostępna tylko dla użytkownika admin. Po zapisaniu jej, upewnij się, że serwer działa. ";
$__information['addondomain_list__pre'] = " Wskazówka: <br>* Jeśli chcesz mieć zaparkowaną domenę z pełnym DNS oraz zarządzaniem pocztą, stwórz pełną domenę, która ma taką samą ścieżkę główną jak domena docelowa. <br> * Jeśli chcesz mieć przekierowaną domenę z pełnym DNS oraz zarządzaniem pocztą, stwórz pełną domenę, a następnie przekieruj jej ścieżkę [b] / [/b] do domeny docelowej.";
$__information['redirect_a_list__pre'] = "Ta opcja pozwala na przekierowanie określonej adresu URL w domenie na inną. <url:a=updateform&sa=configure_misc> Kliknij tutaj </url> jeśli chcesz wymusić przekierowanie domeny typu http://domena.pl na http://www.domena.pl, ";
$__information['web_updateform_dirindex_pre'] = "Włączenie [b] indeksowania katalogów [/b] pozwoli Tobie na przeglądanie katalogów Twojej domeny na serwerze WWW. Jeśli indeksowanie katalogów jest wyłączone, i jeśli plik index.xxx nie został znaleziony w katalogu pojawi się komunikat błędu - brak dostępu.";
$__information['updateform_editmx_pre'] = " Jeśli chcesz skonfigurować zdalny serwer poczty, <url:a=updateform&sa=remotelocalmail> Kliknij tutaj </url>. Możesz ustawić Kloxo w taki sposób, aby serwer poczty był konfigurowany zdalnie, dzięki czemu wszystkie lokalne emaile będą od razu przesyłane na ten serwer. Jeśli nie skonfigurowałeś zdalnej poczty, wtedy wszystkie emaile będą dostarczone lokalnie bez wykonywania zapytań DNS. ";
$__information['web_updateform_run_stats_pre'] = "Ta opcja pozwala na wymuszenie uruchomienia programu statystyk, dzięki czemu będziesz mógł zobaczyć najnowsze statystyki swojej strony WWW. Użyj [b] aktualizuj wszystko [/b], aby uruchomić tą opcję na wszystkich domenach widocznych w menu rozwijalnym.";
$__information['server_alias_a_addform__pre'] = "Możesz dodać [b] * [/b] alias, dzięki czemu wszystkie poddomeny będą automatycznie bezpośrednio przekierowywane na tą domenę. Kloxo automatycznie doda wpis DNS dla tego aliasu. Po skonfigurowaniu poddomeny catchall korzystając z '*', możesz dodać właściwą logikę do swojego skryptu, aby wykryć prawidłową poddomenę i podjąć odpowiednie działania.";
$__information['updateform_sesubmit_pre'] = "Twoja domena będzie dodana do wyszukiwarek z listy poniżej. Adres email użyty tutaj powinien być adresem, który nie jest często używany, ponieważ jest niemal pewne, że będzie otrzymał na niego ogromne ilości SPAM'u od momentu wpisania go tutaj";
$__information['mmail_updateform_authentication_pre'] = "Twój podstawowy serwer MX jest automatycznie zawarty w SPF i nie musisz go dodawać osobno. Możesz użyć [b] aktualizuj wszystko [/b], aby wprowadzić te zmiany na wszystkich domenach widocznych w menu rozwijalnym.";
$__information['updateform_preview_config_pre'] = "Domena podglądu to domena główna, na którą zostaniesz przekierowany po naciśnięciu przycisku Podgląd strony. Musisz ręcznie dodać zaparkowaną domenę nazywaną domena.pl.domenapodgladu.pl do tej domeny, a następnie tutaj dodać domenapogladu.pl. Następnie [b] podgląd domeny bez konfiguracji DNS [/b] zostanie przekierowany na domena.pl.domenapodgladu.pl. Jeśli nie jesteś pewien, pozostaw to pole puste.";
$__information['updateform_stats_protect_pre'] = "Zabezpieczenie stron statystyk to hasło, które jest używane do zabezpieczenia strony statystyk dla Twojej domeny. Jeśli hasło nie zostało wpisane, zabezpieczenie zostanie wyłączone i dzięki temu będziesz miał możliwość bezpośredniego dostępu do statystyk.";
$__information['updateform_installatron_pre'] = "Musisz się wylogować z konta danego użytkownika, a następnie zalogować na konto określonego użytkownika, na którym chcesz użyć Installatron. Installatron jest dostępny aktualnie tylko dla użytkownika, który jest bezpośrednio zalogowany.";
$__information['ftpuser_admin'] = "Użyj [b] --bezpośrednio-- [/b], aby dodać użytkownika FTP, który nie zawiera nazwy domeny.";
$__information['updateform_default_domain_pre'] = " Ta opcja ustawia domenę uznawaną jako domena główna na danym koncie. Możesz dostać się do ścieżki głównej domeny wpisując http://IP/~nazwaklienta. Aby skojarzyć adres IP z domeną, musisz <url: a=list&c=ipaddress> kliknąć tutaj </url>, wejdz wewnątrz adresu IP i kliknij tam zakładkę 'konfiguracja domeny'. Jeśli chcesz zobaczyć domenę przed ustawieniem serwerów DNS, najlepszym sposobem jest stworzenie wpisu dla domeny w lokalnym pliku etc/hosts. Ścieżka dla Windows to c:/windows/system32/drivers/etc/hosts . Po prostu dodaj wpis taki jak np. ten: [b] 192.168.1.32 domena.pl [/b] w osobnej linii, a następnie uzyskasz dostęp do domeny wpisując ją polu adresu przeglądarki.";
$__information['updateform_blockip_pre'] = " Dodaj jeden adres IP na linię. Jeśli chcesz dodać zakres adresów IP użyj zapisu .*.* . np. 192.168.*.*. Zauważ jest to jedyny zapis wpspierany przez zakresy adresów IP. Standardowy zapis adresów IP nie jest wspierany. ";
$__information['web_updateform_statsconfig_pre'] = "Każdego dnia, jeśli pliku logu jest większy niż 50 MB, są one przenoszone do katalogu klienta. Jeśli ustawisz opcję usuwania przetworzonych logów, wtedy nie będą one przenoszone, a zostaną usunięte. Przeliczanie Twoich głównych statystyk nie zostanie naruszone.";
$__information['web_updateform_hotlink_protection_pre'] = "Twoja domena i poddomeny będą miały automatycznie dostęp do obrazków i nie będziesz ich musiał osobno wpisywać. *.domena.pl zostanie autoamtycznie dodana do listy dozwolonych domen, które wpiszesz tutaj. [b] Przekierowanie na obrazek [/b]  musi być ścieżką obrazka wewnątrz Twojej domeny i nie pełnym adresem URL. Powinna taką mieć formę (/img/noaccess.gif). Musisz wpisać domeny jako proste nazwy bez żadnych znaków specjalnych np. domena.pl, mojadomena.pl, mojedomeny.pl";
$__information['mailqueue_list__pre'] = "Zniknięcie kolejki zabierze trochę więcej czasu, więc po kliknięciu usuń emaile nadal będą widoczne w kolejce jeszcze przez pewien czas. Po prostu odśwież tę stronę za ok. minutę, aby sprawdzić czy emaile zostały już skasowane czy nie.";
$__information['mailqueue_updateform_update_pre'] = "Aby zobaczyć logi dla emaili, wróć z powrotem do listy, a następnie przeładuj jeden raz kolejkę emaili, ponieważ tylko log z ostatniej godziny został przetworzony.";
$__information['rubyrails_addform__pre'] = "Aplikacja będzie dostępna pod adresem http://domena.pl/nazwaaplikacji. Ścieżką będzie /home/client/ror/domain.com/applicationname. Jeśli ustawisz flagę [b] dostępne bezpośrednio [/b], wtedy aplikacja będzie dostępna przez http://domena.pl.";
$__information['installsoft_addform__pre'] = "Aby zainstalować aplikację w głównej ścieżce, pozostaw [b] Lokalizację [/b] pustą. Aby zainstalować tą samą aplikację dla innej domeny, użyj pola wyboru na górze, a następnie zmień domenę na inną. Będziesz miał możliwość użycia tego samego formularza z nową domeną. Wiadomość z informacjami o nazwie użytkownika i adresie URL zostanie wysłana na email kontaktowy, który wprowadzisz tutaj.";
$__information['mysqldb_updateform_restore_pre'] = "Możesz użyć tej opcji tylko do odtworzenia kopii zapasowych, które zostały wykonane przez same Kloxo używając zakładki [b] Pobierz kopię zapasową [/b]. Aby przywrócić zwykły plik zrzutu MySQL, użyj phpMyAdmin.";
$__information['domainipaddress_updateform_update_pre'] = "Ta opcja pozwala na przydzielenie określonego adresu IP do domeny. Dzięki temu, jeśli ktoś użyje adresu http://ip, wtedy pojawi się ścieżka dokumentu głównego.";
$__information['updateform_search_engine_pre'] = "Niektóre wyszukiwarki mogą wymagać potwierdzenia adresu e-mail w celu dodania strony. Nie wpisuj tutaj swojego głównego adresu e-mail, ponieważ możesz otrzymać wiadomości typu SPAM. Dla najlepszej pozycji potwórz tą operację co  3-4 tygodnie, ale nie wcześniej, ponieważ możesz zostać zbanowany";
$__information['updateform_domainpserver_pre'] = "Oto serwery, na których zostaną skonfigurowane domeny dla tego klienta. Jeśli zmienisz tutaj wartości, automatycznie wszystkie domeny zostaną przeniesione na odpowiednie serwery. Jeśli zmienisz [b] serwer poczty [/b] i klikniesz aktualizuj, wtedy [b] wszystkie [/b] konta pocztowe dla domen dla tego klienta będą przeniesione ze starego serwera na nowy.  [b]  Szablon DNS [/b]  to nowa konfiguracja serwerów DNS, na które wszystkie domeny zostaną przełączone. Upewnij się, że najpierw stworzysz szablon DNS, który odpowiada nowej konfiguracji, a następnie podasz go tutaj Kloxo. Zobacz więcej na dole odnośnie zmiany serwera. Możesz zrobić hurtową zmianę DNS później przechodząc do [b] Zarządzanie DNS -> Przeładuj [/b] i klikając [b] Aktualizuj wszystko [/b], co spowoduje zmiany szablonu DNS dla wszystkich domen na koncie.";
$__information['sslipaddress_updateform_update_pre'] = "Aby ustawić SSL dla adresu internetowego, najpierw wyślij/dodaj certyfikat SSL <url:goback=2&a=list&c=sslcert> stąd </url>";
$__information['domain_addform__pre_docroot'] = "Pozostaw pustą ścieżkę główną dokumentu, a Kloxo automatycznie użyje domena.pl jako dokumentu głównego.";
$__information['sslcert_updateform_update_pre_admin'] = "Aby przydzielić certyfikat SSL dla danego adresu IP, <url:goback=1&l[class]=pserver&l[nname]=localhost&a=list&c=ipaddress> kliknij tutaj </url>, a następnie wejdź do adresu IP i kliknij zakładkę [b] certyfikat SSL [/b] i będziesz mógł ustawić jeden z tych certyfikatów dla danego adresu IP.";
$__information['sslcert_updateform_update_pre'] = "Aby przydzielić certyfikat SSL dla danego adresu IP, <url:goback=2&a=list&c=ipaddress> kliknij tutaj </url> a następnie wejdź do adresu IP i kliknij zakładkę [b] certyfikat SSL [/b] i będziesz mógł ustawić jeden z tych certyfikatów dla danego adresu IP. Administrator będzie musiał przydzielić dodatkowy adres IP dla Ciebie, abyś mógł skorzystać z tej funkcji.";
$__information['domain_not_customer'] = "Aby dodać domenę, utwórz najpierw klienta, a następnie będziesz mógł dodać domeny na jego koncie. Aby dodać klienta, <url:a=addform&c=client&dta[var]=cttype&dta[val]=customer>kliknij tutaj </url>";
$__information['ipaddress_list__pre'] = "Dodatkowo adres IP pozwoli Tobie na kontrolę określonym adresem IP. Jest to użyteczna rzecz dla SSL a także ustawiania adresu IP dla domeny. Dzięki temu określony adres IP będzie wskazywał na domenę. Aby korzystać z dodatkowego adresu IP, administrator musi najpierw dodać ten adres do Twojego konta. Aby ustawić SSL lub przydzelić IP do domeny, kliknij na adres IP, a następnie kliknij na [b] konfiguracja SSL [/b] lub [b] konfiguracja domeny [/b] ";
$__information['clientmail_list__pre'] = "Ta opcja określa ilość e-maili wysyłanych przez Twoich klientów przez serwer WWW lub SMTP w ciągu ostatnich dwóch dni. Jeśli jest to pełna nazwa konta email jak np. [b] uzytkownik@domena.pl [/b], wtedy odpowiada to poczcie wysyłanej przez serwer SMTP. Jeśli jest to prosta nazwa użytkownika, wtedy odpowiada ona poczcie wysyłanej przez serwer WWW. Jeśli chcesz użyć mod_php na Apache wtedy wszystkie aplikacje Web będą uruchamiane jako użytkownik [b] apache [/b] , i tylko [b] apache [/b] będzie wyświetlany tutaj. Użyj suPHP na apache, jeśli planujesz hosting dla osób trzecich. W ten sposób będzie mógł zidentyfikować każdego klienta używającego swojego konta na serwerze.";
$__information['servermail_updateform_update_pre'] = "To bardzo ważna opcja, należy ustawić tutaj prawidłową nazwę hosta, ponieważ wiele publicznych serwerów e-mail jak np. wp.pl będzie odmawiać przyjęcia poczty z Twojego serwera. Możesz mieć dodatkowy port serwera poczty wpisując go tutaj. Pozostaw pole puste, aby wyłączyć dodatkowy port SMTP. Maksymalna liczba wątków SMTP określa liczbę dopuszczalnych procesów SMTP. Powinieneś ustawić ją na pewną liczbę, np. 10, jeśli otrzymujesz dużą ilość SPAM'u. Jeśli pozostawisz pole puste, wartośc ta będzie ustawiona na NIELIMITOWANE, co jest wartością domyślną.";
$__information['updateform_switchprogram_pre'] = "Przełączanie programów zabierze trochę więcej czasu, ponieważ wymagane jest usunięcie starych programów z systemu, następnie instalacja nowych z użyciem yum. Log tej operacji będzie dostępny w pliku shell_exec. Wszystkie Twoje dane zostaną w niewidoczny sposób przeniesione. Będziesz musiał odczekać ok. minuty, aby nowe usługi prawidłowo się uruchomiły.";
$__information['updateform_permalink_pre'] = "Kloxo dostarczane jest z konfiguracją permalink dla wielu aplikacji. Wybierz aplikację i katalog w którym ją zainstalowałeś, Kloxo doda odpowiednią regułę rewrite do konfiguracji Lighttpd. Zauważ, że dla pewnych aplikacji, permalinks są osiągane za pomocą ustawienia strony błędu 404, np. Wordpress.";
$__information['weblastvisit_list__pre'] = "Oto lista ostatnich 50 odwiedzających lub lista odwiedzających w ciągu ostatnich 20 godzin, którakolwiek jest mniejsza. Czas rzeczywisty określa znacz czasu unix, i dzięki temu masz możliwość sortowania według czasu. Dłuższe wpisy są skracane, aby zmieściły się na ekranie. Możesz je zobaczyć w całości najeżdżając myszką na nie.";
$__information['subweb_a_addform__pre'] = "Oto prosta poddomena. Prosta poddomena ma tylko komponenty sieci web i nie możesz dla niej dodać poczty czy zarządzać DNS. Jeśli chcesz dodać pełną poddomenę, użyj [b] przycisku poddomena [/b] na głównej stronie [b] domen [/b]. Ścieżka prostej poddomeny to /home/nazwaklienta/domena/domain.pl/podomeny/nazwapoddomeny";
$__information['updateform_skeleton_pre'] = "Oto archiwum katalogu skeleton, które zostanie skopiowane do Twojego katalogu domowego, po jego utworzeniu. Archiwum będzie rozpakowane do nowego katalogu domeny. Możesz użyć [b] &lt;%domainname%&gt; , &lt;%clientname%&gt; [/b]  wewnątrz pliku index.html, a wszystkie zmienne będą zmieniona na prawidłowe wartości.";
$__information['updateform_lighty_rewrite_pre'] = "Oto niestandardowa reguła rewrite lighttpd, która zostanie bezpośrednio dopisana do pliku konfiguracyjnego bez żadnych zmian. Będzie ona miała formę [b] url.rewrite = ( ... [/b].  ";
$__information['updateform_custom_error_pre'] = "<p> Wskazówka: Wartości, które musisz podać to wirtualne ścieżki do plików, które będą pokazywane w przypadku błędów. Przykład: /pliki_bledow/404.html.</p>";
$__information['domain_updateform_ipaddress_pre'] = "<p> Wskazówka: Upewnij się, że dokonałeś odpowiednich zmian także w konfiguracji serwera nazw.  </p>";
$__information['client_updateform_ipaddress_pre'] = "<p> Wskazówka: Dostępna pula adresów IP jest wybierana z serwerów dostępnych w puli serwerów. </p>";
$__information['domaintemplate_addform__pre'] = "<p> Wskazówka: Maksymalna wartość po prawej wskazuje twój obecny limit zasobów. Możesz utworzyć szablon z wartościami przekraczającymi Twój obecny limit zasobów, ale nie będziesz miał możliwości ich użycia do tworzenia domen/klientów. </p>";
$__information['vv_dns_blank_message'] = "<p> Wpisz '__base__', jeśli chcesz otrzymać bazową domenę. Użyj &lt;%domain&gt; jeśli chcesz nazwę domeny wewnątrz rekordu TXT np. 'v=spf1 include: &lt;%domain &gt;'. [b] FCNAME [/b] odpowiada za pełny CNAME i pozwala wskazać poddomenę na zewnętrzną domenę.";
$__information['spam_updateform_update_pre'] = "<p> Liczba 'punktów', która może mieć wartość 1-10, jest wartością, po której emaile będą oznaczane jako SPAM. Jeśli ustawisz ją na niskie wartości, więcej emaili będzie oznaczane jako SPAM. Zbyt niskie wartości mogą powodować, że właściwe emaile będą klasyfikowane jako SPAM. Zbyt wysokie wartości mogą spowodować przechodzenie wysokiej ilości SPAMu przez filtr. </p>";
$__information['web_updateform_enable_frontpage_flag_pre'] = "<p> Hasło Frontpage będzie takie samo jak użytkownik systemu (główny użytkownik FTP). </p>";
$__information['ffile_show___lx_error_log_pre'] = "Oto log błędów dla Twojej domeny. Ta zawartość pomoże Tobie w rozwiązaniu problemów z domeną.";
$__information['installappsnapshot_list__pre'] = "Zrzuty baz danych to dokładne kopie bazy danych i plików Twojej aplikacji w określonym czasie. Możesz przywrócić Twoją aplikację do dnaego zrzutu bazy danych klikając na przycisk [b] przywracanie [/b].";
$__information['sshclient_updateform_disabled_pre'] = "Administrator nie aktywował dostępu do konsoli (SSH) dla Ciebie. Otwórz złoszenie w centrum zgłoszeń jeśli potrzebujesz dostępu SSH. ";
$__information['sshclient_updateform_warning_pre'] = "Zauważ, że cała aktywność jest monitorowana i każda próba dostępu do plików nienależących do Ciebie spowoduje blokadę Twojego konta hostingowego, dlatego działaj odpowiedzialne.";
$__information['ffile_show___lx_access_log_pre'] = "Ta opcja służy to log dostępu do Twojej domeny. Możesz go pobrać klikając na zakładkę [b] pobierz [/b] po prawej stronie. Ten plik zawiera informacje o każdej odsłonie Twojej strony WWW.";
$__information['updateform_disable_url_pre'] = "Wszyscy Twoi klienci będą automatycznie dziedziczyć Twoje parametry blokad URL. Aby wymusić blokadę URL na nich, po prostu zablokuj im uprawnienie 'Możliwość ustawiania zablokowanych adresów URL' w opcjach uprawnień. Ta opcja to adres URL, na który zostanie przekierowana domena, gdy zostanie ona zablokowana.";
$__information['updateform_dnstemplatelist_pre'] = "Przydzielaj tylko jeden szablon DNS na klienta. Oznacza, to, że Kloxo nie pokaże pola wyboru szablonu DNS podczas dodawania domeny, co będzie mniej dziwne dla klienta.";
$__information['forward_a_addform__pre'] = "Lista przekierowanych adresów emaili to lista adresów email, na które poczta będzie przekierowywana. Jedna kopia takiego emaila będzie zachowywana także na aktualnym koncie pocztowym. Możesz wyłączyć lokalne przechowywanie <url:a=updateform&sa=configuration>klikając tutaj </url>.";
$__emessage['blocked'] = "Twój adres jest zablokowany";
$__emessage['no_server'] = "Nie mogę się połączyć z serwerem.";
$__emessage['set_emailid'] = "Wpisz swój indentyfikator email poprawnie.";
$__emessage['no_socket_connect_to_server'] = "Nie można się połączyć z serwerem [%s]. Jest to najprawdopodobniej spowodowane przez błąd sieci. Upewnij się, że serwer jest dostępny dla tego poszczególnego serwera uruchamiając [b] telnet id-serwera_podrzędnego 7779 [/b]   ";
$__emessage['restarting_backend'] = "Trwa ponowne uruchamianie podsystemu. Spróbuj ponownie za 30 sekund.";
$__emessage['quota_exceeded'] = "Limit zasobów przekroczony dla [%s]";
$__emessage['license_no_ipaddress'] = "Publiczny adres IP [%s] tego serwera nie został znaleziony w respozytorium licencji. Skontaktuj się z działem sprzedaży Lxlabs w celu stworzenia licencji na ten serwer. </a> ";
$__emessage['ssh_root_password_access'] = "Nie zablokowałeś dostęp użytkownika root za pomocą hasła na tym serwerze. Dostęp użytkownika roota za pomocą hasła nie jest wymagany, ponieważ możesz zarządzać autoryzowanymi kluczami SSH za pomocą samego HyperVM. <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=sshconfig> Kliknij tutaj </url>, aby skonfigurować swój serwer SSH.";
$__emessage['already_exists'] = "Nazwa zasobu [%s] już istnieje.";
$__emessage['lxguard_not_configured'] = "Lxguard nie jest skonfigurowany na tym serwerze. <url:k[class]=pserver&k[nname]=localhost&a=show&o=lxguard>Kliknij tutaj, aby skonfigurować Lxguard </url>, ponieważ to bardzo ważne, abyś rozumiał do czego on służy. Lxguard jest krytyczny dla bezpieczeństwa Twojego serwera, w tym samym czasie, może on zablokować dostęp do serwera dla Twojego własnego adresu IP, co może być bardzo frustrujące, jeśli nie będziesz wiedział co się dzieje.";
$__emessage['root_cannot_extract_to_existing_dir'] = "Katalog, który podałeś już istnieje. Użytkownik root nie może być rozpakowany do istniejącego katalogu. Wprowadź nazwę katalogu, który nie istnieje w systemie.";
$__emessage['no_imagemagick'] = "Nie ma rozszerzenia imagemagick w systemie. Możesz zainstalować imagemagick uruchamiając w konsoli serwera polecenie [b] yum -y install imagemagick [/b].";
$__emessage['warn_license_limit'] = "Jesteś bardzo blisko limitu licencji dla [%s]. Jeśli system przekroczy limit dla [%s], interfejs przestanie działać i nie będziesz w stanie zarządzać systemem. Proszę zwiększ ilość licencji na stronie client.lxlabs.com i dokonać aktualizacji <url:o=license&a=show> klikając tutaj </url>";
$__emessage['file_already_exists'] = "Plik [%s] już istnieje.";
$__emessage['contact_set_but_not_correct'] = "Twoje dane kontaktowe nie zawierają prawidłowego adresu email. Kliknij <url:a=updateform&sa=information> tutaj, aby je naprawić.</url> ";
$__emessage['contact_not_set'] = "Twoje dane kontaktowe nie są ustawione prawidłowo. Kliknij <url:a=updateform&sa=information> tutaj, aby je naprawić. </url> ";
$__emessage['you_have_unread_message'] = "Masz [%s] nieprzeczytane wiadomości. Kliknij <burl:a=list&c=smessage> tutaj, aby je odczytać. </burl>";
$__emessage['you_have_unread_ticket'] = "Masz [%s] nieprzeczytanych zgłoszeń. Kliknij <burl:a=list&c=ticket> tutaj, aby je odczytać. </burl>";
$__emessage['security_warning'] = "Twoje hasło jest obecnie ustawione na hasło domyślne, co stanowi poważne zagrożenie bezpieczeństwa. Zmień hasło natychmiastowo <url:a=updateform&sa=password> klikając tutaj. </url> ";
$__emessage['ssh_port_not_configured'] = "Port SSH tego serwera nie jest ustawiony. Jest zalecane, aby zmienić go na port inny niż domyślny 22. <url:a=show&o=sshconfig> Kliknij tutaj, aby go zmienić:</url>. Jeśli chcesz zachować SSH na porcie 22 i uniknąć wyświetlania się tego komunikatu, przejdź do wskazanej strony i ustaw go na stałe na 22, dzięki czemu to ostrzeżenie nie będzie więcej wyświetlane.";
$__emessage['system_is_updating_itself'] = "System w tej chwili uaktualnia się i dlatego nie będziesz miał możliwości dokonywania jakichkolwiek zmian przez kilka minut. Wszystkie akcje nie wymagające zapisywania będą jednak działać poprawnie.";
$__emessage['system_is_locked'] = "Ktoś zainicjował akcję wymagającą modyfikacji systemu na tym określonym obiekcie, która nadal trwa. Nie będziesz miał możliwości dokonywania jakichkolwiek zmian przez kilka minut. Wszystkie akcje nie wymagające zapisywania będą jednak działać poprawnie.";
$__emessage['system_is_locked_by_u'] = "Zainicjowałeś akcję wymagającą modyfikacji systemu na tym określonym obiekcie, która nadal trwa. Nie będziesz miał możliwości dokonywania jakichkolwiek zmian przez kilka minut. Wszystkie akcje nie wymagające zapisywania będą jednak działać poprawnie.";
$__emessage['smtp_server_not_running'] = "hyperVM nie może się połączyć z serwerem SMTP na tym serwerze. Oznacza to, że hyperVM nie będzie w stanie wysłać jakichkolwiek emaili. Jest to bardzo ważna sprawa, ponieważ hyperVM monitoruje poprawność działania całego klastra i wysyła email do administratora, w przypadku stwierdzenia jakichkolwiek błędów. Powinieneś upewnić się czy usługa SMTP działa na tym serwerze. Po ponownym uruchmieniu usługi SMTP, odczekaj 5 minut, aby zniknął ten komunikat błędu, ponieważ hyperVM sprawdza dostępność usług tylko co każde 5 minut.";
$__emessage['template_not_owner'] = "Nie jesteś właścicielem tego szablonu";
$__emessage['ipaddress_changed_amidst_session'] = "Adres IP zmienił się w trakcie trwania sesji. Prawdopodobna próba przechwycenia sesji.";
$__emessage['more_than_one_user'] = "Więcej niż jeden użytkownik jest zalogowany na to konto. Kliknij <burl:a=list&c=ssession>tutaj, aby zobaczyć listę loginów. </burl> ";
$__emessage['login_error'] = "Logowanie nie powiodło się";
$__emessage['file_exists'] = "plik (pliki) [%s] istnieje (istnieją). Wklejanie anulowano...";
$__emessage['cannot_unzip_in_root'] = "Nie możesz rozpakować plików do katalogu root. Wskaż katalog, do którego pliki mają zostać rozpakowane.";
$__emessage['nouser_email'] = "Email nie pokrywa się z emailem kontaktowym użytkownika";
$__emessage['session_expired'] = "Sesja wygasła";
$__emessage['e_password'] = "Nieprawidłow hasło";
$__emessage['is_demo'] = "[%s] jest zablokowany w wersji demo.";
$__emessage['user_create'] = "Użytkownik [%s] nie może zostać stworzony. Spróbuj inną nazwę";
$__emessage['switch_done'] = "Przełączenie serwerów zostało uruchomione w tle. Otrzymasz email, gdy proces przełączania zostanie ukończony.";
$__emessage['mis_changed'] = "Zmiana konfiguracji wyświetlania powiodła się.";
$__emessage['password_sent'] = "Hasło zostało zresetowane i wysłane poprawnie.";
$__emessage['added_successfully'] = "[%s] został prawidłowo dodany.";
$__emessage['backup_has_been_scheduled'] = "Kopia zapasowa wykonuje się obecnie w tle. Otrzymasz email na swój adres kontaktowy po jej zakończeniu.";
$__emessage['update_scheduled'] = "Aktualizacja jest właśnie dokonywana w tle. Możesz odświeżyć tą stronę, aby zobaczyć czy została prawidłowo zakończona.";
$__emessage['restore_has_been_scheduled'] = "Przywracanie wykonuje się obecnie w tle. Otrzymasz email na swój adres kontaktowy po jego zakończeniu.";
$__emessage['same_dns'] = "Serwer główny i podrzędny nie mogą być tym samym serwerem.";
$__emessage['user_exists'] = "Użytkownik [%s] już istnieje.";
$__emessage['mysql_error'] = "Błąd Mysql, baza danych zgłasza: [%s]";
$__emessage['this_domain_does_not_resolve_to_this_ip'] = "Aby adres IP wskazywał na domenę, domena musi wskazywać na ten sam adres IP, inaczej domena przestanie działać. Domena, którą próbujesz przydzielić do tego adresu IP nie wskazuje na ten adres IP, więc nie może zostać ustawiona jako domena domyślna dla tego adresu IP.";
$__emessage['dns_conflict'] = "Domena nie została dodana z powodu błędu w ustawieniach DNS. Sprawdź swój szablon DNS i zweryfikuj go. Komunikat z serwera DNS to [%s]";
$__emessage['add_without_www'] = "Powinieneś dodać tylko domenę główną w formacie domena.pl. Poddomena [b] www [/b] będzie automatycznie dodana do niej. Nie powinieneś dodawać [b] www [/b] tworząc domenę.";
$__emessage['could_not_connect_to_db'] = "Nie można połączyć się z bazą danych: Błąd został zalogowany. Skontaktuj się z administratorem.";
$__emessage['e_no_dbadmin_entries'] = "Nie ma żadnych wpisów baz danych na tym określonym serwerze. Skontaktuj się z administratorem w celu ich ustawienia.";
$__emessage['please_add_one_domain_for_owner_mode'] = "Musisz mieć co najmniej jedną domenę, jeśli chcesz przełączyć się do trybu właściciela domeny. Możesz dodać domenę <url:a=addform&c=domain>klikając tutaj </url>.";
$__emessage['e_no_dbadmin_entries_admin'] = "Nie ma wpisów administratora bazy danych na tym określonym serwerze. Musisz wejść do sekcji serwery na tym serwerze, a następnie kliknąć na ikonę Administrator bazy danych, po czym dodać użytkownika bazy danych i hasło na tym określonym serwerze i typie bazy danych.";
$__emessage['mail_server_name_not_set'] = "Nazwa identyfikacyjna Twojego serwera poczty nie została ustawiona. Oznacza to, że wiele publicznych serwerów poczty takich jak np. wp.pl będzie odrzucać emaile z Twojego serwera. Kliknij <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=servermail> tutaj, aby je ustawić. </url>";
$__emessage['dns_template_inconsistency'] = "Szablon DNS, który wybrałeś nie pokrywa się z wyborem Twoich serwerów np. może tak się zdarzyć, że adres IP w DNS nie został w ogóle znaleziony na tym serwerze. Powróć do poprzedniej strony i utwórz szablon DNS, który ma parametry pokrywające się konfiguracją serwera.";
$__emessage['adding_cron_failed'] = "Dodawanie zadania do harmonogramu zadań (Cron) nie powiodło się z powodu [%s]. Usuń je i spróbuj dodać ponownie.";
$__emessage['se_submit_running_background'] = "Dodawanie do wyszukiwarek jest obecnie uruchomione w tle. Otrzymasz email na swój adres kontaktowy, gdy zostanie ukończone.";
$__emessage['err_no_dns_template'] = "Nie ma szablonów DNS w tym systemie. Musisz dodać co najmniej jeden szablon DNS, aby dodać domenę/klienta. Kliknij <url:a=addform&c=dnstemplate> tutaj, aby dodać szablon DNS. </url></p> ";
$__emessage['certificate_key_file_empty'] = "Certyfikat i plik klucza, który wybrałeś jest pusty. Musisz najpiew stworzyć lub wysłać je przed włączeniem SSL";