#!/bin/zsh
##source ~/.etc/f.bashrc
cd ~/wh/inc/`cat ~/.etc/screen/pathdown` ; wget -t 4 -c "$1"
if [ "$?" != 0 ] ; then
    if [ x"$EMACS_NAME" = x"nemacs" ] ; then
	gnuclient -batch -eval "(read-from-minibuffer \"download error $1\")" > /dev/null  2>&1;
	zsh
	exit
    else
	zsh
	exit
    fi
fi
if [ x"$EMACS_NAME" = x"nemacs" ] ; then
    gnuclient -batch -eval "(read-from-minibuffer \"download success $1\")" > /dev/null  2>&1;
fi
