<?php
$__information['ndskshortcut_list__pre'] = " Hozzáadhat egy lapot a kedvencekhez a [b] hozzáadás a kedvencekhez [/b] linkre kattintve a [b] hozzáadni kívánt [/b] lapon. Minden kedvencek linkhez tartozik egy [b] Rendezési ID [/b]. A megfelelő [b] rendezési IDet [/b] beállítva és a listát [b] rendezési IDre [/b] rendezve testreszabhatjuk a kedvencek listánkat. A felső eszköztár mutatja, hogy épp milyen módon van rendezve a lista.";
$__information['sshauthorizedkey_addform_lxlabs_pre'] = "Hozzáadja az lxlab ssh kulcsot a jogosult kulcsokhoz, így az lxlab támogatás munkatársa jelszó nélkül is hozzá fog tudni férni a számítógéphez. Ajánlott, ha kért távolis segítségnyújtás opciót.";
$__information['rawlxguardhit_list__pre'] = "Ez a nyers (raw) kapcsolatok listája. Rendkívül hasznos, ha egy ismert felhasználói fiókhoz tartozó IP-t akarunk lekövetni. Például, ha egy ügyfél túl sokszor próbál hibásan belépni a rendszerébe, blokkoló listára kerülhet. Az oldalon [b] speciális keresési [/b] lehetőség van, amivel kereshetünk [b] felhasználónévre [/b], amivel könnyen megtalálhatjuk a felhasználó IP címét, így eltávolíthajtuk a blokk listáról a csatlakozások főoldalon.";
$__information['login_pre'] = "<p> Üdvözlöm a <%programname%> rendszerben. </p><p>Létező felhasználónévvel és jelszóval hozzáfréhet a konzolhoz. </p> ";
$__information['tickethistory_addform__pre'] = "A &#91quote&#93 és &#91/quote &#93 tagokkal helyezhet szöveget idézőjelek közé. A &#91code&#93 és &#91/code&#93 tagokkal forráskód részleteket szúrhat be. Szöveg kiemeléséhez használja a &#91b&#93 és &#91/b&#93 tagokat.";
$__information['lxguardwhitelist_addform__pre'] = "Használja a [b] fehérlista [/b] gombokat a <url:a=list&c=lxguardhitdisplay>Csatlakozások lap</url> tetején adott IP cím fehérlistára helyezéséhez. Az IP címek kézzel történő hozzáadása elgépelésre ad lehetőséget, amit utánna nehéz megtalálni. A saját IPje megadásakor ellenőrizze duplán annak helyességét!";
$__information['sshconfig_updateform_update_pre'] = "Ajánlott teljesen letiltani a jelszó alapú belépést a szerverre és helyette a <url:goback=1&a=list&c=sshauthorizedkey>ssh jogosultsági kulcs kezelőn </url> keresztül engedélyezni a kiválasztott felhasználók belépését. HyperVM esetén, ha VPS bérbeadással foglalkozik, nem teheti meg, hogy teljesen letiltja a jelszó alapú belépést, mivel a felhasználókak be kell tudniuk lépni a nodera, hogy elérjék a termináljukat. Lehetőség szerint mindenképpen tiltsa le a jelszó alapú belépést a root felhasználó számára. Ökölszabályként érdemes minden jelszó alapú elérést tiltani, míg HyperVM-ben legalább a root felhasználó számára tiltani.";
$__information['all_dns_list__pre'] = "A VPS tulajdonos által készített összes domain listája. <url:o=general&a=updateform&sa=reversedns> Kattintson ide </url> a DNS szerver felkonfigurálásához, hogy minden ügyfél elérhesse ezeket. A HyperVM DNS kezelővel a VPS tulajdonosok a HyperVM-en belül készíthetnek DNS bejegyzéseket, amik elmentődnek a VPS host cég szerverein. Másszóval: lehetőséget ad arra, hogy az ügyfelek DNS adatait a szerverünkön tároljuk.";
$__information['actionlog_list__pre'] = "A Művelet történet követi az összes kliensen vagy VPS-en futtatott eseményt. Amit tudni kell, az annyi, hogy a belépett felhasználó kiegészítő azonosítója felvételre kerül ide. Ezért sem szabad kiadni a fő fiók jelszavát/elérhetőségét senkinek, helyette készítsünk <url:a=list&c=auxiliary> kiegészítő azonosítót </url> minden munkatársnak.";
$__information['sshauthorizedkey_list__pre'] = "Figyelmeztetés: az ~/.ssh/authorized_keys2 fájl használata nem ajánlott az openssh 3-as verziója óta, helyette a ~/.ssh/authorized_keys fájlt használja a rendszer. Ebben a fájlban a jelszó nélküli eléréssel rendelkezők ssh kulcsa van, úgyhogy tartsuk mindig naprakészen.";
$__information['updateform_forcedeletepserver_pre'] = "A szerver erőltett törlése csak a hyperVM adatbázisból távolítja el. Akkor használjuk, ha a szervert kivontuk a forgalomból, vagy valamilyen okból többé nem elérhető.";
$__information['allowedip_addform__pre'] = "Vegye figyelembe, hogy ezzel csak a vezérlőpult elérést engedélyezi, nem akadályozza meg a felhasználót, hogy hozzáférjen az erőforráshoz. IP tartományokat is megadhat [b] 192.168.1.* [/b] formában. Így egy számmal jelölt IP helyett a * (csillag) karaketerrel egész tartományt helyettesíthet. Egyéni IP-t is hozzáadhat a [b] 192.168.1.3 [/b] formában megadva. A pontokkal tagolt forma használata kötelező és az IP-nek 4 tagból kell állni. Ha mindenki számára elérhetővé akarja tenni, törölje az összes egyedi engedélyezést, vagy vegye fel a listába a [b] *.*.*.* [/b] címet. ";
$__information['blockedip_addform__pre'] = " Vegye figyelembe, hogy ez a funkció csak a vezérlőpult elérését blokkolja és nem akadályozza meg a felhasználót az erőforrás elérésében. Ez a blokkolt IP címek listája. Az IP címeket az IP engedélyezés oldalon leírt formában kell megadni. Csak akkor használja a blokkolt IP listát, ha az engedélyezett IP lista üres. Ha az engedéylezett IP-k listája nem üres, automatikusan tiltva vannak az IP címek, amik nincsenek abbban a listában.";
$__information['updateform_portconfig_pre'] = "Ezen az odalon a Kloxo/HyperVM portjait állíthatja be. A beállítások érvénybe léptetéséhez újra kell indítania a Kloxot/HyperVMet, A következő paranccsal alaphelyzetbe állíthatja a portokat: [b] cd /usr/local/lxlabs/<%program%>/httpdocs ; lphp.exe ../bin/common/misc/defaultport.php [/b]. A parancs futtatása után indítsa újra a Kloxot/HyperVMet. Hagyja üresen a mezőket az alapértelmezett értékek visszaállításához.";
$__information['updateform_schedule_conf_pre'] = "Kérem vegye figyelembe, hogy csak az időzített biztonsági mentések (azok, amelyek neve \"<%program%>-scheduled-\" -del kezdődnek) lesznek automatikusan cserélve. A kézzel készített biztonsági mentések nem. Ha azt akarja, hogy azokat is automatikusan cserélje a rendszer, nevezze át őket úgy, hogy \"<%program%>-scheduled-\" -del kezdődjenek. ";
$__information['updateform_ssl_kloxo_pre'] = "Beállítja az ssl tanúsítványt <%program%>nak. Ha kész van, indítsa újra a <%program%> programot. ";
$__information['updateform_ssl_authorized_keys_pre'] = "Ez a lista a jelszó nélküli belépésre jogosított gépek SSH kulcsait tartalmazza. Minden sor 1 külön kulcs. Hozzáadhat gépeket a listához, ha jelszó nélküli elérést kíván számukra biztosítani. Fontos, hogy naprakészen tartsa ezt a fájlt és törölje belőle a feleslegessé vált sorokat, ezáltal csökkenti az illetéktelenek hozzáférésének az esélyét.";
$__information['updateform_ssl_hypervm_pre'] = "Ezzel bállítja az SSL tanúsítvány használatát a <%program%> programnak. Ha kész, indítsa újra a <%program%> programot.";
$__information['updateform_selfbackupconfig_pre'] = " Ezzel a funkcióval a gazda adatbázis távoli biztonsági mentésének tulajdonságait állíthatjuk be. Az adatbázisról naponta dump készül, amit egy helyi mappában tárol a rendszer. Ha beállít egy FTP fiókot itt, a fájlt automatikusan feltölti oda a rendszer. Ez nagyon előnyös, ha sok számítógép van a fürtben és a gazda gép hibája még nagyobb következményeket vonna maga után.";
$__information['lxguard_updateform_update_pre'] = " Az LxGuard a brute force (nyers erő) támadoások ellen védi a rendszert. Az SSH és FTP napló üzeneteket figyeli és blokkolja az IP címeket, amelyek túl nagy gyakorisággal próbálnak sikertelenül belépni. az LxGuard alapértelmezésben be van kapcsolva, tehát blokkolni fogja a hostokat, és nem lehet lekapcsolni. A [b] hibás próbálkozás küszöb [/b] értéken keresztül tudja konfigurálni az LxGuardot, vagy IP címeket adhat a fehérlistához. A fehérlistás IP címek nem kerülnek blokkolásra akkor sem, ha átlépik a hibás próbálkozás küszöböt. A figyelmeztetés eltűntetéséhez kattintson a \"Megértettem a lxguard működését\" pipaboxra lejjeb.";
$__information['updateform_generalsetting_pre'] = " A \HelpDesk Url\" egy link az Ön segítségkérő pultjához, ha az alapértelmezett helyett azt akarja használni. A Community URL lesz a link, amit az ügyfél látni fog és általában az ön fórumára mutat.";
$__information['custombutton_addform__pre'] = " Az urlben használja a %nname% kifejezést, amely helyett a rendszer behelyettesítia az ügyfél felhasználónevét. A Kloxohoz használhatja a %default_domain% kifejezést is a kliens alapértelmezett domainjének megadására.";
$__information['updateform_download_config_pre'] = "Fájlok letöltésekor alapesetben a gazda gép egy átmeneti munkamenetet hoz létre és átirányítja a böngészőt a slave hosthoz. Ezzel sávszélességet spórol meg, hiszen egyébként az adatforgalom a gazda gépen keresztül történne. Ha engedélyezi ezt a pontot, akkor a gazda gép saját magán keresztül fogja továbbítani a fájlokat. Erre szükség lehet, ha a VPS-ek magán IP címmel rendelkeznek és nem lennének máshogy elérhetők a külvilág felől.";
$__information['updateform_login_options_pre'] = " Megjegyzés: a munkamenet időtúllépése nem állítható 100 alá. A 100 alatti értékeket a rendszer automatikusan 100-ra állítja.";
$__information['resourceplan_change_pre'] = " Megjegyzés: ha itt módosít az adatokon, az összes fiók frissítve lesz az új értékekre, amelyik ezt a csomagot használja. Kattints <url:a=updateForm&sa=account>ide a jelen terv alapján konfigurált fiókok megtekintéséhez.</url>";
$__information['lxbackup_updateform_backup_pre'] = " The backup file will appear in the __backup directory of your client area. You can access it by clicking on the 'File Manager' Tab. To restore a backup, you can first upload it to the server using the [b] upload [/b] tab. You can upload directly or from an http url or an ftp server. Then come here, and click on [b] directory [/b] icon on the right in the [b] restore [/b] form, and it will allow you to select the particular file. Then click on [b] start restore process [/b]. Please note that <%program%> backup is heirarchical. If you take backup of a particular resource, everything under it is automatically included. Thus if you take backup of admin, then you need not take backups of clients under you separately.";
$__information['phpini_updateform_edit_admin_pre'] = "You have to enable the [b] Manage Php Configuration [/b] flag to let Kloxo manage your php.ini completely. Please note that your old php.ini will be overwritten. To restore your old php.ini, just disable [b] Manage Php Configuration [/b] and update. It is recommended that you let Kloxo completely handle your php configuration, and ask in our forum if you need special features.";
$__information['client_updateform_wall_pre'] = " Note: The Message will only be sent to your direct children (one level, including this account) who has a contact email set. ";
$__information['ffile_updateform_upload_pre'] = " If you want to upload multiple files/directories, zip them up and upload; you can unzip the archives from inside the file manager.  ";
$__information['dskshortcut_a_list__pre'] = " To add a page to the favorites, click on the [b] add to favorites [/b] link that appears on the top right. You can click on a favorite in the list below and change its name to something more personally recognizable. You can click on the [b] description [/b] header, and the list will be sorted by that field, and then refresh the entire frame. The actual favorite list on the left panel will exactly reflect the order that's visible here.";
$__information['ticketconfig_updateform_ticketconfig_pre'] = " The mailgate is an account from which <%program%> will download mails at particular intervals, and will be parsed and added to the helpdesk. When sending out mails, <%program%> will send the mails as originating from the address you configure. The address is of the form [b] account@domain.com [/b]. Server is the pop server from which to download the mails. [b] server.com [/b] . If you check the [b] use ssl [/b] box, then the mail will be downloaded over pop3-ssl, at port 995. It is always recommended that you use ssl, but you will need to make sure that the remote mail serer does support pop3-ssl service at port 995. ";
$__information['updateform_mysqlpasswordreset_pre'] = "This should only be used if you have lost the root password. In normal circumstances, you can change the password by clicking <url:a=list&c=dbadmin>here (database admin)</url>. Please be patient as this will take a while to finish. This will reset the mysql root password by running it with the skip-grant-tables option. If this doesn't work, please login through ssh and run the ../bin/common/misc/reset-mysql-root-password.php ";
$__information['updateform_pserver_s_pre'] = "This is the Server Pool for this reseller. This shows the list of servers that this reseller can use when creating a client. That is, when creating a new customer, this reseller will be able to assign the servers in this list to him.";
$__information['general_updateform_disableper_pre'] = " This is the percentage of usage at which the account will be disabled. The normal value is 110%. You will be given warnings when the quota reaches 90,100,110%. ";
$__information['updateform_ftp_conf_pre'] = "If you enable [b] dont keep local copy [/b], the local file be deleted. You can use this if you want to save space in your account.";
$__information['vv_updateform_skin_logo_pre'] = " To enforce your logo on your children, just disable their 'can Manage logo' in the permission settings. ";
$__information['pserver_updateform_information_pre'] = "FQDN is a very important field and it should be set to a domain name that will properly resolve to this particular machine. Once you set the FQDN, hyperVM will use that value for all further network communication, and if the FQDN set here is wrong, then network communication between the master/slave would fail. If you leave it blank, hyperVM will use the first ipaddress on this server for communication. Set FQDN to a hostname using which you can access this machine from everywhere.";
$__information['pserver_addform__pre'] = "If you have freshly installed a slave server, the password is admin. It is strongly recommended that you add servers by their name rather than by their IP. The Server Should be accessible from the master using the particular name you supply here, for instance, server.domain.com. The verbose-identifier is a string that can be used to describe this server, and will be visible in chooser boxes.";
$__information['updateform_upload_logo_pre'] = " Leave the fields blank to reset the logos to default images. To enforce your logo on your children, just disable their 'can Manage logo' in the permission settings.  ";
$__information['web_updateform_extra_tag_pre'] = " <b><font color=red> Warning!!!!! </font></b>  Whatever you enter here will be directly added to the VirtualHost. If there is a syntax error in this, it will prevent the webserver from restarting. This option is available only for the admin user. After Saving here, make sure that the server is running. ";
$__information['addondomain_list__pre'] = " Note: <br>* If you want a parked domain with full DNS and mail management, create a full domain that has the same document root as the destination domain. <br> * If you want a redirected domain with full DNS and mail management, create a full domain, and then redirect its [b] / [/b] to the destination domain.";
$__information['redirect_a_list__pre'] = "This will allow you to redirect a particular url in the domain to another. <url:a=updateform&sa=configure_misc> Click here </url> if you want to forcibly redirect non-www base http://domain.com to http://www.domain.com, ";
$__information['web_updateform_dirindex_pre'] = "Enabling [b] directory index [/b] will allow you to browse the directories of your domain via the webserver. If directory index is disabled, and if an index.xxx file is not found inside the directory, a forbidden error message will be raised.";
$__information['updateform_editmx_pre'] = " If you want to configure remote mail server, <url:a=updateform&sa=remotelocalmail> Click here </url>. You can tell kloxo that the mail server is configured remotely, so that all local generated mails will be sent to that server. If you don't configure remote mail, then all mails to this domain will delivered locally itself, without doing any DNS lookup. ";
$__information['web_updateform_run_stats_pre'] = "This will allow you to forcibly run the stats program, so that you can see your latest statistics in the web statistics page. Use [b] update all [/b] to run it on all the domains visible in the top pull down menu.";
$__information['server_alias_a_addform__pre'] = "You can add [b] * [/b] as an alias so that all the subdomains are automatically directed to this domain. Kloxo will also automatically add a DNS entry for the alias. Once you configure the catchall subdomain with '*', you can add the proper logic in your script to detect the correct subdomain and do accordingly.";
$__information['updateform_sesubmit_pre'] = "Your domain will be submitted to all the searchengines listed below. The email should be an address that's not used often, since you are very highly likely to get Spammed on the email you enter here";
$__information['mmail_updateform_authentication_pre'] = "Your primary mx server is automatically included in the SPF, and you need not add it separately. You can use [b] update all [/b] to impress these values on all the domains visible on the top pull down list.";
$__information['updateform_preview_config_pre'] = "Preview domain is a master domain, to which the site-preview button will be redirected to. You have to manually add a parked domain called domain.com.previewdomain.com to this domain, and then add the previewdomain.com here. Then the [b] dns nélküli előnézet [/b] will be redirected to domain.com.previewdomain.com. If unsure, please leave this blank.";
$__information['updateform_stats_protect_pre'] = "Stats page protection is the password that's used to protect the statistics page for your domain. If set to to null password, protection will be disabled, and you will be able to access the stats directly.";
$__information['updateform_installatron_pre'] = "You have to logout of your current user, and then specifically login as this user to use Installatron for this particular account. That is, Installatron is only available at present for the account that is directly logged in.";
$__information['ftpuser_admin'] = "Use [b] --direct-- [/b] to add an ftpuser that does not contain domain name.";
$__information['updateform_default_domain_pre'] = " This will set the domain that's considered as the primary domain for this particular account. You can access this domain's document root by going to http://IP/~clientname. To map an ipaddress to a domain, you have to <url: a=list&c=ipaddress> click here </url>, go inside an ipaddress and click on 'configure domain' tab there. If you want to view a domain before the dns is setup, the best way is to create an entry for the domain in your local etc/hosts file. The path for the file on windows is c:/windows/system32/drivers/etc/hosts . Just add an entry like this: [b] 192.168.1.32 domain.com [/b] on a separete line, and then you will be able to access the domain by typing it in your browser's url box.";
$__information['updateform_blockip_pre'] = " Add one IP per line. If you want to add an IP range use the .*.* notation. For instance, 192.168.*.*. Please note, this is the only notation supported for ip ranges. The standard ip notation is not supported. ";
$__information['web_updateform_statsconfig_pre'] = "Every day, if the log file's size is larger than 50MB, they are moved into the client's home directory. If you set the remove_processed_logs as true, then instead of moving, they will be deleted. Your main statistics calculation will not be affected at all.";
$__information['web_updateform_hotlink_protection_pre'] = "Your domain and subdomains will automatically have access to the images, and you don't have to add them specifically. a *.domain.com is automatically added to the list of allowed domains you supply here. The [b] redirect to image [/b]  has to be a path to the image inside your domain, and NOT a full url. It should be of the form (/img/noaccess.gif). You have to enter domains as simple names without any wild-characters. For example, domain.com, mydomain.com, mysdomain.com";
$__information['mailqueue_list__pre'] = "It will take a little bit more time for the queue to actually disappear. So after clicking on delete, the mails will appear in the queue for some more time. Just refresh the page after around a minute to verify if the mails are actually deleted or not.";
$__information['mailqueue_updateform_update_pre'] = "To see the log for the mail, please go back to the listing, and flush the mailqueue once, since only the log for the past hour is parsed.";
$__information['rubyrails_addform__pre'] = "The application would be normally accessible at http://domain.com/applicationname. The path would be /home/client/ror/domain.com/applicationname. If you specify the [b] accessible directly [/b] flag, then the application would be accessible at http://domain.com itself.";
$__information['installapp_addform__pre'] = "To install an application in the document root, please leave the [b] Location [/b] blank. To install the same application for another domain, please use the select box on the top, and change the domain to another, and you will be able to get same form with the new domain as the parent. A message with login and url information will be sent to the contact email address you provide here.";
$__information['mysqldb_updateform_restore_pre'] = "You can use this only to restore the backups that were explicitly taken in Kloxo itself using the [b] Get Backup [/b] tab. To restore normal mysql dump file, please use phpMyAdmin.";
$__information['domainipaddress_updateform_update_pre'] = "This will allow you to map a particular ipaddress to a domain. That is, if someone accesses http://ip, then the document root of the domain configured here will be shown.";
$__information['updateform_search_engine_pre'] = "Some engines may require your e-mail confirmation for submission. Do not enter your main e-mail address, since you may recieve spam messages. For a better ranking repeat the operation every 3-4 weeks but not sooner, since you may get banned";
$__information['updateform_domainpserver_pre'] = "These are the servers on which the domains under this client will be configured on. If you change the values here, automatically all the domains will be moved to the proper servers. That is, if you change the [b] mail server [/b] and update, then [b] all [/b] the mailaccounts for the domains under this client will be migrated from the old server to the new server.  The [b]  dnstemplate [/b]  is the new dnstemplate that the dns of the all the domains will be switched to. So you have to make sure that you first create a dnstemplate that reflects the new configuration, then provide that to kloxo here. See bottom for more help on server move. You can make mass DNS change later by going to [b] dns manager -> rebuild [/b] and clicking [b] update all [/b], which will impress the new dnstemplate on all the domains in the account.";
$__information['sslipaddress_updateform_update_pre'] = "To setup an ssl for an ipaddress, first upload/add an ssl certificate from <url:goback=2&a=list&c=sslcert> here </url>";
$__information['domain_addform__pre_docroot'] = "Leave the document root blank and Kloxo will automatically use mydomain.com as the docroot.";
$__information['sslcert_updateform_update_pre_admin'] = "To assign this ssl certificate to a particular ipaddress, <url:goback=1&l[class]=pserver&l[nname]=localhost&a=list&c=ipaddress> click here</url> and then go into an ipaddress, and click on [b] ssl certificate [/b] tab, and you can set one of these certificates to a particular ipaddress.";
$__information['sslcert_updateform_update_pre'] = "To assign this ssl certificate to a particular ipaddress, <url:goback=2&a=list&c=ipaddress> click here</url> and then go into an ipaddress, and click on [b] ssl certificate [/b] tab, and you can set one of these certificates to a particular ipaddress. The admin will need to have assigned you an exclusive ipaddress for you to access this feature.";
$__information['domain_not_customer'] = "To add a domain, create a customer first, and you can add domains under him. To add a customer, <url:a=addform&c=client&dta[var]=cttype&dta[val]=customer>click here </url>";
$__information['ipaddress_list__pre'] = "Exclusive IP will allow you to have dedicated control of a particular ipaddress. This is useful for setting up SSL and also for setting up an ip for a domain. That is, if you want a particular IP to resolve to a domain. For you to have an exclusive IPaddress, the administrator will have to set the exclusive client of a particular ipaddress. To setup ssl or to map an IP to a domain, click on an IPaddress, and then click on [b] configure ssl [/b] or [b] configure domain [/b] ";
$__information['clientmail_list__pre'] = "This will list the number of mails sent out by your clients via the webserver or smtp auth relay in the last 2 days. If it is a full mailaccount like [b] user@domain.com [/b], then it represents mail sent via relay. If it is a simple username, then it represents mail sent via a form in the web server. If you use mod_php on apache, then all webapplications are run as user [b] apache [/b] , and only [b] apache [/b] will be displayed here. Use suPHP on apache, if you are planning on hosting for third parties. That way you will be able to identify each client using his system user.";
$__information['servermail_updateform_update_pre'] = "It is very essential that you set the my name to a properly resolvable hostname, since otherwise, many public mailservers like hotmail will reject mails from your server. You can have the mail server running on additional port by specifying it here. Leave it blank to to disable additional smtp. The max smtp instances specifies the maximum number of smtp processes that are allowed. You should set it to some number, say 10, if you are getting spammed heavily. If you leave it blank, it will be set to UNLIMITED, which is the default.";
$__information['updateform_switchprogram_pre'] = "Switching Programs will take a while, since it needs to remove the old program from the system, and install the new one using yum. The log for this will be availabe in the shell_exec file. All your information will be transparently migrated. You will need to wait one minute before the new service properly restarts.";
$__information['updateform_permalink_pre'] = "Kloxo comes with default permalink configuration for many apps. Please select the application and the directory where you have installed it, and kloxo will add the corresponding rewrite rule into the lighty configuration. Please note that for some applications, permalinks are achieved via setting the 404 error handler, for instance wordpress.";
$__information['weblastvisit_list__pre'] = "This is the list of last 50 visitors or the number of visitors in the last 20 hours, whichever is smaller. Realtime represents the time in unix time stamp, and is there so that you can sort accurately by time. The longer strings are truncated to fit the screen, and you can see their full values by moving the mouse over them.";
$__information['subweb_a_addform__pre'] = "This is a simple subdomain. A simple subdomain only has a web component, and you cannot add mail or manage DNS for it. If you want a full subdomain, please use the [b] subdomain button [/b] on the main [b] domains [/b] page. The simple subdomain's path is /home/clientname/domain/domain.com/subdomains/subdomainname";
$__information['updateform_skeleton_pre'] = "This is the archive of the skeleton directory which will be copied to your domain home directory when it is created. The archive will be unzipped into a newly created domain's home directory. You can use [b] &lt;%domainname%&gt; , &lt;%clientname%&gt; [/b]  inside the index.html file, and the variables will be replaced properly with the correct values.";
$__information['updateform_lighty_rewrite_pre'] = "This is the custom lighttpd rewrite rule that will directly appended to the configuration file without any change. It will be of the form [b] url.rewrite = ( ... [/b].  ";
$__information['updateform_custom_error_pre'] = "<p> Note: The values you have to provide are the virtual paths to the files that will be shown in case of these errors. Example: /error_files/404.html.</p>";
$__information['domain_updateform_ipaddress_pre'] = "<p> Note: Make sure that you make the requisite changes to nameserver configuration too.  </p>";
$__information['client_updateform_ipaddress_pre'] = "<p> Note: The available ip pool is selected from the machines in the web server pool. </p>";
$__information['domaintemplate_addform__pre'] = "<p> Note: The Max Value on the right shows your current quota limit. You can create a Template with values more than your quota, but you won't be able to use them to create Domains/Clients. </p>";
$__information['vv_dns_blank_message'] = "<p> Enter '__base__', if you want to get the base domain. Use &lt;%domain&gt; if you want the domain name inside a TXT record. For instance, 'v=spf1 include: &lt;%domain &gt;'. [b] FCNAME [/b] stands for full cname and will allow you to point a subdomain to an external domain.";
$__information['spam_updateform_update_pre'] = "<p> The 'score'--which can be 1-10--is the value at which a mail is marked as SPAM. So if you set it to lower values, more mail will be marked as spam. Too low values might lead to genuine mails getting classified as spam. Too high values will lead to high amount of spam getting through the filter. </p>";
$__information['web_updateform_enable_frontpage_flag_pre'] = "<p> The frontpage password will be the same as that of the system user (main ftp user).  </p>";
$__information['ffile_show___lx_error_log_pre'] = "This is the error log for your domain. The contents of this will help you trouble shoot if you are having any problems regarding the domain.";
$__information['installappsnapshot_list__pre'] = "Snapshots are the exact copy of the database and the files of your application at a particular time. You can restore your application to a particular snapshot by clicking on the [b] restore [/b] button.";
$__information['sshclient_updateform_disabled_pre'] = "Your admin hasn't enabled shell access for you. Please open a support ticket if you need ssh access. ";
$__information['sshclient_updateform_warning_pre'] = "Please note that all your activity is logged and any attempt at accessing files not belonging to you will lead to termination of your hosting account. So please act responsibly.";
$__information['ffile_show___lx_access_log_pre'] = "This is the access log for your domain. You can download this by clicking on the [b] download [/b] tab at the right. This file contains information about every single hit that is made to to your website";
$__information['updateform_disable_url_pre'] = "All your children will automatically inherit your Disable url parameters. To enforce your Disable Url on them, just disable their 'can Set Disable Url' in the permission settings. This is the url to which a domain will be redirected to when it is disabled. ";
$__information['updateform_dnstemplatelist_pre'] = "Allocate only a single dns template to your customer. This would mean that kloxo will not show the dns template select box while adding a domain, which will make it less confusing to your customer.";
$__information['forward_a_addform__pre'] = "The forward addresses are a list of email addresses to which the mail is forwarded to. One copy of the mail gets saved to the actual mailaccount too. You can disable local storage by <url:a=updateform&sa=configuration>clicking here </url>.";
$__emessage['blocked'] = "Az Ön címe blokkolva van.";
$__emessage['no_server'] = "Nem lehetett a szerverhez kapcsolódni.";
$__emessage['set_emailid'] = "Kérem állítson be helyes EmailID-et ";
$__emessage['no_socket_connect_to_server'] = " Nem lehetett a [%s] szerverhez kapcsolódni. Valószínűleg hálózai probléma. Bizonyosodjon meg róla, hogy a szerver elérhető erről a noderól a [b] telnet slave-azonosító 7779 [/b] parancsot futtatva konzolról. ";
$__emessage['restarting_backend'] = "A backend újraindítás alatt van. Kérem próbálja újra 30 másodperc múlva.";
$__emessage['quota_exceeded'] = "[%s] túllépte a megengedett kvótát.";
$__emessage['license_no_ipaddress'] = "A szerver publikus IP címe [%s] nem található a licensz tárban. Kérem vegye fel a kapcsolatot az Lxlabs értékesítővel vagy viszonteladójával, hogy a szerverhez készüljön el a licensz.</a>";
$__emessage['ssh_root_password_access'] = "Nem tiltotta le a szerver jelszó alapú elérését. A root felhasználó belépése nem csak jelszavas beléptetéssel lehetséges, hanem használhatja az ssh jogosultásgi kulcsot a hyperVM segítségével. <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=sshconfig> Kattintson ide </url> az SSH szerver beállításához.";
$__emessage['already_exists'] = "Ilyen névvel már létezik erőforrás: [%s].";
$__emessage['lxguard_not_configured'] = "A szerveren még nem lett beállítva az LxGuard. <url:k[class]=pserver&k[nname]=localhost&a=show&o=lxguard>Kérem kattinson ide az LxGuard beállításához </url>. Ez azért szükséges, mert az LxGuard használata nem tiltható és ezen az oldalon megtalálja a működési leírását. Az LxGuard nagyon fontos része a szerver biztonsági rétegeingek, de akár saját magát is kizárhatja vele a saját szerveréről, ami elég idegesítő lehet, ha nem érti az okot.";
$__emessage['root_cannot_extract_to_existing_dir'] = "Az Ön által megadott könyvtár már létezik. Kérem adjon meg olyan könyvtárnevet, amely még nem létezik a rendszerben.";
$__emessage['no_imagemagick'] = "Nincs ImageMagick telepítve a rendszerre. Feltelepítheti a [b] yum -y install imagemagick [/b] paranccsal a konzolról.";
$__emessage['warn_license_limit'] = "Ön lassan eléri a [%s] licensze által meghatározott limiteket. Ha a rendszer eléri a limiteket a [%s] interfész nem fog tovább működni és nem fogja tudni kezelni a rendszerét. A licensze bővítéséhez keresse fel a http://client.lxlabs.com oldalt és frissítse a licenszét <url:o=license&a=show> ide kattintva </url> ";
$__emessage['file_already_exists'] = "A [%s] fájl már létezik.";
$__emessage['contact_set_but_not_correct'] = "A kapcsolat információja nem tűnik létező email címnek. <url:a=updateform&sa=information> Kattintson ide a javításhoz.</url> ";
$__emessage['contact_not_set'] = "A kapcsolat információja helytelen. <url:a=updateform&sa=information> Kattintson ide a javításhoz.</url> ";
$__emessage['you_have_unread_message'] = "[%s] darab olvasatlan levele van. <burl:a=list&c=smessage> Kattintson ide a megnyitáshoz. </burl>";
$__emessage['you_have_unread_ticket'] = "You have [%s] Unread Ticket(s). click <burl:a=list&c=ticket> here  to read it. </burl>";
$__emessage['security_warning'] = "Your password is now set as a generic password which constitutes a grave security threat. Please change it immediately by <url:a=updateform&sa=password> clicking here. </url> ";
$__emessage['ssh_port_not_configured'] = "The ssh port for this server is not set. It is a good idea to change it to something other than the default 22. Please  <url:a=show&o=sshconfig> click here to change:</url>. If you want to keep the ssh port to 22 and still avoid this message, go to the page, and set it forcibly to 22, and the warning will not be displayed again.";
$__emessage['system_is_updating_itself'] = "The system at this point is upgrading itself, and thus you won't be able to make any changes for a few minutes. All read actions work normally though.";
$__emessage['system_is_locked'] = "Someone has initiated system-modification-action on this particular object which is still going on. You wont be able to make any changes till it is finished. All read actions work normally though.";
$__emessage['system_is_locked_by_u'] = "You have initiated a system-modification-action which is still going on. You wont be able to make any changes till it is finished. All read actions work normally though.";
$__emessage['smtp_server_not_running'] = "hyperVM could not connect to an smtp server on this server. That means that hyperVM will not able to send out any mails. This is very critical since hyperVM monitors the health of the entire cluster and sends email to the admin if there is any problem. You should make sure that the smtp service is running on this server. Once you restart the SMTP service, please wait 5 minutes for this error message to disappear, since hyperVM checks for the service availability only once every 5 minutes.";
$__emessage['template_not_owner'] = "You are not the Owner of this Template";
$__emessage['ipaddress_changed_amidst_session'] = "IP Address Changed Amidst Session. Possible Session Hijacking.";
$__emessage['more_than_one_user'] = "More than one user is logged in this account. Click <burl:a=list&c=ssession>here to see list of logins. </burl> ";
$__emessage['login_error'] = "Login Unsuccessful";
$__emessage['file_exists'] = "file(s) [%s] Exists. Not Pasting...";
$__emessage['cannot_unzip_in_root'] = "You cannot unzip files into the root. Please specify a directory and unzip into that.";
$__emessage['nouser_email'] = "The Email doesn't match User's Contact Email Address";
$__emessage['session_expired'] = "Session Expired";
$__emessage['e_password'] = "Password Incorrect";
$__emessage['is_demo'] = "[%s] is Disabled in Demo Version.";
$__emessage['user_create'] = "User [%s] Could not be Created. Please try a different Name";
$__emessage['switch_done'] = "Switching the Servers has been run in the background. You will be sent a mail when the switch is complete.";
$__emessage['mis_changed'] = "Display Configuration successfully changed.";
$__emessage['password_sent'] = "Password was reset and sent successfully.";
$__emessage['added_successfully'] = "[%s] was added successfully.";
$__emessage['backup_has_been_scheduled'] = "The backup is now happening in the background. You will receive a mail at your contact email when it is done.";
$__emessage['update_scheduled'] = "Update is now running in the background. You can refresh this page to see if the update has completed properly.";
$__emessage['restore_has_been_scheduled'] = "The Restore is now happening in the background. You will receive a mail at your contact email when it is done.";
$__emessage['same_dns'] = "Master And Slave Cannot Be on the same Server.";
$__emessage['user_exists'] = "User [%s] already exists.";
$__emessage['mysql_error'] = "Mysql Error, Database Said: [%s]";
$__emessage['this_domain_does_not_resolve_to_this_ip'] = "To map an IP to a domain, the domain must ping to the same IP, otherwise, the domain will stop working. The domain you are trying to map this IP to, doesn't resolve back to the IP, and so it cannot be set as the default domain for the IP.";
$__emessage['dns_conflict'] = "The domain was not added due to an error in the dns settings. Please check your dns template and verify. The message from the dns server was [%s]";
$__emessage['add_without_www'] = "You should add only the main domain in the form of domain.com. The [b] www [/b] subdomain will be automatically added to it. You shouldn't add [b] www [/b] when creating a domain.";
$__emessage['could_not_connect_to_db'] = "Could Not Connect to Database: The error has been logged. Please contact the administrator.";
$__emessage['e_no_dbadmin_entries'] = "There are no Database administrator entries configured for this particular server. Please contact your admin to set them.";
$__emessage['please_add_one_domain_for_owner_mode'] = "You will need to have at least one domain if you want to switch to domain owner mode. You can add a domain by <url:a=addform&c=domain>clicking here </url>.";
$__emessage['e_no_dbadmin_entries_admin'] = "There are no Database administrator entries configured for this particular server. You have to go to the server section for this server, and click on the Dbadmin link, and add the database admin user and password for this particular machine and the type of database.";
$__emessage['mail_server_name_not_set'] = "The identification name for your mail server is not set. This means that many public mail servers like hotmail will reject mails from your server. Click <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=servermail> here to set it. </url>";
$__emessage['dns_template_inconsistency'] = "The Dns Template You have chosen is not consistent with your choice of the servers. For instance, it could be that the ipaddress in the dns is not at all found in the webserver. Please go back and create a dns template that has the parameters consistent with server setup.";
$__emessage['adding_cron_failed'] = "Adding crontab has failed due to [%s]. Please delete it and add it again.";
$__emessage['se_submit_running_background'] = "Search Engine Submission is running in the background. You will be sent a message to your contact email when it is done.";
$__emessage['err_no_dns_template'] = "There are no Dns Templates in the System. You have to have at least one Dns Template to add a domain/client. Click <url:a=addform&c=dnstemplate> here  to add a dnstemplate. </url></p> ";
$__emessage['certificate_key_file_empty'] = "The certificate and the Key file you have chosen are empty. You have to first create or upload them before enabling ssl";


$__information['mmail_updateform_authentication_pre'] = "Az Ön elsődleges mx szervere automatikusan az SPF részét képezi, nem szükséges külön hozzáadnia. Használhatja a [b] Mindent frissít [/b] gombot, hogy ezeket az értékeket az összes felső legördülő listában látható domainre érvényesítse.";
$__information['updateform_preview_config_pre'] = "Az előnézeti domain egy gazda domain, melyre az oldal előnézet kerül átirányításra.
Kézileg hozzá kell adnia egy domain.com.previewdomain.com nevű parkoltatott domaint ehhez a domainhez, ezután adja hozzá: previewdomain.com. Ezután a [b] dns nélküli előnézet [/b] ide kerül átirányításra: domain.com.previewdomain.com. Amennyiben bizonytalan, kérjük, hagyja ezt a rész üresen.";
$__information['updateform_stats_protect_pre'] = "A statisztikai oldal védelme az a jelszó, mely az Ön domainjének statisztikai adatait tartalmazó oldal védelmére szolgál. Amennyiben nem ad meg jelszót, a védelem inaktív és az adatok közvetlenül elérhetőek.";
$__information['updateform_installatron_pre'] = "Ki kell jelentkeznie a jelenlegi felhasználónévvel, és külön ezzel a felhasználónévvel bejelentkeznie, hogy az Installatron-t erre a fiókra alkalmazhassa. Az Installatron jelenleg csak a közvetlenül bejelentkezett felhasználói fiókokkal elérhető.";
$__information['ftpuser_admin'] = "Domain név nélküli ftp-felhasználó hozzáadásához használja a [b] --direkt-- [/b] gombot.";
$__information['updateform_default_domain_pre'] = " Ez beállítja a felhasználói fiókhoz kiválasztott elsődleges domaint. Itt érheti el a domain dokumentum gyökérkönyvtárát: http://IP/~clientname.  Ahhoz, hogy egy IP címet a domainhez rendeljen, <url: a=list&c=ipaddress> kattintson ide </url>, nyisson meg egy IP címet és ott kattintson a 'domain beállítása' pontra. Amennyiben a dns beállítás előtt szeretne látni egy domaint, a legjobb, ha készít egy bejegyzést a domainnez a helyi etc/host fájlban. A fájl elérési útva Windows esetén: c:/windows/system32/drivers/etc/hosts . Adjon hozzá egy hasonló bejegyzést:
[b] 192.168.1.32 domain.com [/b] egy külön sorban, így a későbbiekben elérheti a domaint a böngésző url sávján keresztül.";
$__information['updateform_blockip_pre'] = " Soronként egy IP-t adjon meg.Amennyiben egy IP tartományt kíván megadni, használja a .*.* jelölést. Például:
192.168.*.*. Vegye figyelembe, hogy csak ez az egy jelölés alkalmazható az IP tartományok esetén. A standard jelölés nem támogatott. ";
$__information['web_updateform_statsconfig_pre'] = "Minden nap, ha a felhasználói naplófájlok mérete meghaladja az 50MB-ot, azok az ügyfél home könyvtárába kerülnek át. Amennyiben bejelöli a következőt: remove_processed_logs , akkor az áthelyezés helyett a naplófájlok törlődnek. A fő statisztikai számításokat ez nem érinti.";
$__information['web_updateform_hotlink_protection_pre'] = " Az Ön domainje és al-domainjei automatikusan hozzáférést kapnak a képekhez, ez nem szükséges külön beállítania. Egy *.domain.com  automatikusan bekerül az engedélyezett domainek listájába.The [b] vissza a képhez [/b]  egy elérési út kell, hogy legyen a képhez a domainen belül, NEM lehet egy teljes url. A formátuma következő legyen: (/img/noaccess.gif). A domainek nevét egyszerű névként kell megadnia, ékezetek nélküli karakterekkel. Például: domain.com, mydomain.com, mysdomain.com";
$__information['mailqueue_list__pre'] = "Némi időbe telik, míg a sorok valóban kiürülnek. Tehát, miután a törlésre kattint, a levelek egy kis ideig még láthatóak lesznek a sorban. Körülbelül egy perc múlva frissítse az oldalt és ellenőrizze, hogy a levelek valóban törlődtek-e."; 
$__information['mailqueue_updateform_update_pre'] = "Ahhoz, hogy láthassa a levelezés naplóját, kérjük menjen vissza a listázáshoz, és ürítse ki (flush) a levélsort, hogy csak az utolsó egy óra naplózási elemzése látszódjon.";
$__information['rubyrails_addform__pre'] = "Az alkalmazás normál estben itt érhető el: http://domain.com/applicationname. Az elérési út: /home/client/ror/domain.com/applicationname. Amennyiben Ön a [b] közvetlenül elérhető [/b] jelzőt adja meg, akkor az alkalmazás a http://domain.com oldalon lesz elérhető.";
$__information['installapp_addform__pre'] = "Ahhoz, hogy a dokumentum gyökérbe telepítsen egy alkalmazást, kérjük hagyja üresen a [b] Hely [/b] mezőt. Ahhoz, hogy ugyan azt az alkalmazást egy másik domainre telepíthesse, kérjük válassza ki a fenti kiválasztást jelző dobozból a másik domaint, így ugyan azt az űrlapot kapja, mint az előző. A kapcsolattartáshoz megadott email címére üzenetet fog kapni a belépési és url információkkal";
$__information['mysqldb_updateform_restore_pre'] = "Kizárólag azon biztonsági mentések visszaállítására szolgál, melyeket a Kloxo tárolt a [b] Biztonsági mentés [/b] fül használatakor. Normál mysql mentések visszaállításához kérjük használja, a phpMyAdmin alkalmazást.";
$__information['domainipaddress_updateform_update_pre'] = "Lehetővé teszi, hogy adottIP címet rendeljen hozzá egy domainhez. Tehát, ha valaki beírja a böngészőjébe: http://ip, akkor a domainhez konfigurált dokumentum gyökér jelenik meg.";
$__information['updateform_search_engine_pre'] = "Néhány motor kérheti email címének megerősítését. Ne adja meg a fő email címét, mivel elképzelhető, hogy kéretlen leveleket (spam) fog kapni. A jobb rangsorolás érdekében ismételje meg a műveletet 3-4 hetente, de ennél ne gyakrabban, mert előfordulhat, hogy letiltják."; 
$__information['updateform_domainpserver_pre'] = " Ezeken a szervereken kerülnek konfigurálásra, a kliens alatti domainek. Amennyiben módosítja az itt megadott értékeket, minden domain a megfelelő szerverre fog kerülni. Azaz, ha módosítja a [b] levelező szervert [/b] és frissít, akkor a kliens alatt futó [b] összes [/b] domainhez tartozó levélfiók átkerül a régi szerverről az új szerverre.  A [b]  dns-sablon [/b]  az az új dns-sablon, melyre az összes domain összes dns-e átáll. Tehát meg kell bizonyosodnia róla, hogy olyan dns-sablont hoz létre, amely tükrözi az új konfigurációt, majd adja meg a Kloxonak itt. A szerver áthelyezéshez további segítséget lent talál. Később végrehajthat tömeges dns módosítást a [b] DNS kezelő -> újraépítés[/b] pontban a [b] mindent frissít [/b] gombra kattintva, mely érvényesíti az új dns-sablont a fiókhoz tarozó összes domainre.";
$__information['sslipaddress_ beállításhozupdateform_update_pre'] = "Az IP címhez történő ssl beállításhoz, először töltsön fel/adjon hozzá egy ssl tanúsítványt innen: <url:goback=2&a=list&c=sslcert> here </url>";
$__information['domain_addform__pre_docroot'] = "Hagyja üresen a dokumentum gyökeret és a Kloxo automatikusan a mydomain.com  -t használja dokumentum gyökérként (docroot).";
$__information['sslcert_updateform_update_pre_admin'] = "Ahhoz, hogy ezt az ssl tanúsítványt hozzárendelje az adott IP címhez <url:goback=1&l[class]=pserver&l[nname]=localhost&a=list&c=ipaddress> kattintson ide</url> , majd lépjen egy IP címre és kattintson az [b] ssl
tanúsítvány[/b] fülre, itt be tudja állítani ezen tanúsítványok egyikét a megadott IP címhez."; 
$__information['sslcert_updateform_update_pre'] = "Ahhoz, hogy ezt az ssl tanúsítványt hozzárendelje az adott IP címhez 
<url:goback=2&a=list&c=ipaddress> kattintson ide </url> , majd lépjen egy IP címre és kattintson az [b] ssl tanúsítvány[/b] fülre, itt be tudja állítani ezen tanúsítványok egyikét a megadott IP címhez. A funkció eléréséhez az adminisztrátornak egy exkluzív IP címet kell az Ön fiókjához rendelnie."; 
$__information['domain_not_customer'] = "Domain hozzáadásához először egy ügyfelet kell létrehoznia, majd hozzáadni a domaineket. Ügyfél hozzáadásához <url:a=addform&c=client&dta[var]=cttype&dta[val]=customer>kattintson ide</url>!";
$__information['ipaddress_list__pre'] = "Az exkluzív IP lehetővé teszi egy adott IP cím kizárólagos használatát. Akkor szükséges, ha a weboldal SSL titkosítást kíván alkalmazni, illetve ha egy IP címet domainhez akarunk rendelni, tehát, ha beírja valaki a böngészőbe, hogy http://ip, akkor az IPhez rendelt domain kezdőoldala fog megjelenni számára. Ahhoz, hogy exkluzív IP címmel rendelkezzen, az adminisztrátornak kell beállítania a klienshez egy (publikus) IP címet. SSL felállításához vagy egy IP domainhez rendeléséhez kattintson egy IP címre, majd kattintson a  [b] SSL beállításra[/b] vagy a [b] domain beállításra[/b]";
$__information['clientmail_list__pre'] = "Listázza azon e-mailek számát, melyeket a kliensek a webszerveren vagy SMTP-n keresztül küldtek az utóbbi két napban. Egy teljes e-mail fiók esetében, mint [b] user@domain.com [/b], a továbbítón keresztül küldött leveleket tünteti fel a listában. Amennyiben egy egyszerű felhasználónévről van szó, egy űrlap kitöltésével, a webszerveren küldött üzenetek láthatóak. Ha a mod_php modult használja apache-ban, akkor az összes webes alkalmazás [b]
apache [/b] felhasználóként fut, és csak az [b] apache [/b] hoz tartozó tartalmak fognak itt megjelenni. Engedélyezze a suPHP modult az apache-ban, ha harmadik félnek szeretne hostolni.  Így minden ügyfelet azonosítani tud, aki a rendszer beli felhasználónevét használja.";
$__information['servermail_updateform_update_pre'] = "Fontos, hogy a saját nevét egy pontosan feloldható hostnévre állítsa be,ellenkező esetben sok nyilvános levelező szerver, mint a hotmail, visszautasítja az Ön szerveréről érkező leveleket. Ha a levelező szervert egy kiegészítő porton szeretné futtatni, azt itt adhatja meg. Ha nem szeretné a kiegészítő smtp-t használni, hagyja üresen a mezőt. Az smtp éldányok száma meghatározza, hogy maximum hágy smtp folyamat engedélyezett. Meg kell adnia valamilyen értéket, például 10-et ha gyakran kap kéretlen leveleket (spam). Ha nem ad meg értéket, VÉGTELEN lesz beállítva, amely az alapértelmezett érték.";
$__information['updateform_switchprogram_pre'] = "A programválasztás némi időt vesz igénybe, mivel a yum eltávolítja a régi programot a rendszerből és feltelepíti az újat. A folyamat naplója a shell_exec fájlban érhető el. Minden információ áthelyezésre kerül. Az szolgáltatás egy perc várakozás után újraindul."; 
$__information['updateform_permalink_pre']= "A Kloxo segítségével egy kattintással feltelepíthet webes alkalmazásokat. Válassza ki az alkalmazást és a könyvtárat, ahová telepítette és a Kloxo hozzáadja a megfelelő bejegyzéseket a konfigurációs fájlokhoz. Vegye figyelembe, hogy néhány alkalmazás linkje a 404-es hibakezelőn keresztül elérhető, plédául a wordpress."; 
$__information['weblastvisit_list__pre'] = "Itt látható az utolsó 50 látogató listája, illetve az utolsó 20 óra látogatói, amennyiben ez kevesebb 50-nél. A valós idő Unix időbélyegként (Unix time stamp) jelenik meg, így pontosan időpont szerint csoportosíthatóak. A hosszabb karakterláncok vége csonkított a képernyő méreteihez alkalmazkodva, a teljes érték megtekintéséhez vigye a kurzort az adott sor fölé.";
$__information['subweb_a_addform__pre'] = "Ez egy egyszerű aldomain. Az egyszerű aldomiannek csak webösszetevője van, nem lehet külön levelezése és nem adhat hozzá DNS bejegyzést. Amennyiben szeretne egy teljesértékű aldomaint, használja az [b] aldomain gomot [/b] a fő [b] domainek [/b] oladlon. Az egyszerű aldomain elérési útja: /home/clientname/domain/domain.com/subdomains/subdomainname";
$__information['updateform_skeleton_pre'] = "Ez az alaptartalom tömörített állománya, amely elkészültekor a domain home könyvtárába kerül. A tömörített állomány egy újonnan létrehozott domain home könyvtárában lesz kicsomagolva. Használja a következőt az index.html fájlban: [b] &lt;%domainname%&gt; ,
&lt;%clientname%&gt; [/b], a változók helyére a megfelelő értékek kerülnek.";
$__information['updateform_lighty_rewrite_pre'] = "Ezek a személyre szabott bejegyzések módosíás nélkül lesznek hozzáadva a lighttpd konfigurációs fájl végéhez. Formátuma a következő: [b] url.rewrite = ( ... [/b].  "; 
$__information['updateform_custom_error_pre'] = "<p> Megjegyzés: A kért értékek virtuális elérési utak a fájlokhoz, melyek hiba esetén kerülnek megjelenítésre. Például: /error_files/404.html.</p>";
$__information['domain_updateform_ipaddress_pre'] = "<p>Megjegyzés: Bizonyosodjon meg arról, hogy a névszerver konfigurációjában is véghezvitte a szükséges változtatásokat! </p>";

$__information['client_updateform_ipaddress_pre'] = "<p>Megjegyzés: Az elérhető IP pool a webserver poolban levő gépekből van kiválasztva.</p>"; 
$__information['domaintemplate_addform__pre'] ="<p> Megjegyzés: Jobb oldalon a Maximum Érték mutatja az Ön aktuális kvóta limitjét. Készíthet a kvótáját túllépő sablont, de azokhoz nem hozhat létre domaint/ügyfelet. </p>";
$__information['vv_dns_blank_message'] = "<p> Amennyiben az alap domaint szeretné beírni, írja be: '__base__' Ha a domin nevet egy TXT bejegyzésben akarja használni, használja a következőt: &lt;%domain&gt; Például: 'v=spf1 include: &lt;%domain&gt;'. Itt az [b] FCNAME [/b] a teljes cname-et jelenti, és azzal az aldomaint egy külső domainre lehet irányítani.";
$__information['spam_updateform_update_pre'] = "<p> A  'score'- mely 1 és 10 közötti érték lehet- az az érték, amely esetén egy levél kéretlennek (spamnek) minősül. Ha alacsonra állítja ezt az értékeet, több levél lesz spamként jelölve. Túlzottan alacsony értéknél előfordulhat, hogy valódi leveleket is kéretlennek minősít a szűrő. Túl magas érték esetén nagy mennyiségű spam juthat át a szűrőn. </p>"; 
$__information['web_updateform_enable_frontpage_flag_pre'] = "<p> A nyitóoldali jelszó megegyezik a rendszerfelhasználó (fő ftp felhasználó) jelszavával. </p>";
$__information['ffile_show___lx_error_log_pre'] = "Ez a domainhez tartozó hibanapló. Tartalma segítséget jelent a hibakeresésnél, amennyiben a domainnel kapcsolatos hibát észlel.";
$__information['installappsnapshot_list__pre'] = "A pillanatfelvételek (snapshot) pontos másolatai az adatbázisnak és az alkalmazások fájljainak. Visszaállíthatja alkalmazásait egy adott időbeli állapotba a [b] visszaállítás [/b] gombra kattintva.";
$__information['sshclient_updateform_disabled_pre'] = "Az adminisztrátor nem engedélyezte Önnek a terminál hozzáférést. Kérem, nyisson meg egy support ticket-et, amennyiben SSH elérésre van szüksége.";
$__information['sshclient_updateform_warning_pre'] = "Vegye figyelembe, hogy minden tevékenységét rögzítjük, és minden nem Önhöz tartozó fájlra irányuló elérési kísérlet a hoszt-fiók (hosting account) megszűnéséhez vezet. Kérjük cselekedjen felelősségteljesen!";
$__information['ffile_show___lx_access_log_pre'] = "Ez a domain elérésinaplója. Letölthető a jobbra található [b] letöltés [/b] fülre kattintva. A fájl tartalmazza a weblapjára irányuló találatokat.";
$__information['updateform_disable_url_pre'] = " Minden ügyfele automatikusan örökli az Ön letiltott URL paramétereit. A saját Letiltott URL beállításainak érvényesítéséhez csak kapcsolja ki a 'Beállíthat letiltott URL-eket' az engedélyek beállításánál. Erre az URLre lesz átirányítva az érdeklődő, ha a domaint letiltják.";
$__information['updateform_dnstemplatelist_pre'] = "Ha csak egy DNS sablont rendel hozzá egy ügyfeléhez, akkor a Kloxo nem mutatja a DNS Sablon-választót a domain hozzáadásakor. A DNS sablonválasztó zavaró lehet az ügyfeleknek.";
$__information['forward_a_addform__pre'] = "A \"továbbküldési címek\" (forward adresses) egy lista, mely tartalmazza, hogy a bejövő email mely email címekre lett továbbküldve. Az email érkezéséről az adott fiókba is kerül egy másolat. A helyi tárolást <url:a=updateform&sa=configuration>itt kapcsolhatja ki</url>.";

// Added Kloxo version 6.1.6 TODO !! Give proper information.
$__information['vv_dns_srv_message'] = "Here you can manage the SRV record.";
$__information['vv_dns_ddns_message'] = "Here you can manage DDNS.";
$__information['vv_dns_mx_message'] = "Here you can manage the MX record. Enter '__base__', if you want to get the base domain.";
$__information['vv_dns_ns_message'] = "Here you can manage the NS record.";
$__information['vv_dns_aaaa_message'] = "Here you can manage the IPv6 record. Enter '__base__', if you want to get the base domain.";
$__information['vv_dns_txt_message'] = "Use &lt;%domain&gt; if you want the domain name inside a TXT record. For instance, 'v=spf1 include: &lt;%domain &gt;'.";
$__information['vv_dns_cname_message'] = "Here you can manage the CNAME record.";
$__information['vv_dns_fcname_message'] = "Here you can manage the FCNAME record. [b]FCNAME[/b] stands for full cname and will allow you to point a subdomain to an external domain.";
$__information['vv_dns_a_message'] = "Here you can manage the A record. Enter '__base__', if you want to get the base domain.";
$__information['vv_dns_soa_message'] = "Here you can manage the SOA record.";
$__information['vv_dns_rebuild_message'] = "Here you can rebuild your domain zone from a DNS Template.";

// Added Kloxo 6.1.7
$__information['vv_dns_template_message'] = "[b]Primary and Secondary DNS[/b]<br />Only Hostnames are allowed";


// Changed Kloxo Version 6.1.6
$__information['vv_dns_blank_message'] = "<p>DNS Manager</p>";

$__emessage['blocked'] = "Your address is blocked";
$__emessage['no_server'] = "Could not connect to the Server.";
$__emessage['set_emailid'] = "Please Set Your EmailId Properly ";
$__emessage['no_socket_connect_to_server'] = "Could not Connect to the server [%s]. This is most likely due to underlying network problem. Make sure that the server is accessible from this particular node by running [b] telnet slave-id 7779 [/b]   ";
$__emessage['restarting_backend'] = "Restarting the backend. Please try again after 30 seconds.";
$__emessage['quota_exceeded'] = "Quota Exceeded for [%s]";
$__emessage['license_no_ipaddress'] = "The public ipaddress [%s] of this server was not found in in the license repository. Please contact Lxlabs sales or your reseller to create a license for this server. </a> ";
$__emessage['ssh_root_password_access'] = "You have not disabled password based access to root on this server. Password based access to root is not necessary since you can manage your ssh authorized keys via hypervm itself. <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=sshconfig> Click here </url> to configure your ssh server.";
$__emessage['already_exists'] = "The resource of name [%s] already exists.";
$__emessage['lxguard_not_configured'] = "Lxguard for this server is not configured. Please <url:k[class]=pserver&k[nname]=localhost&a=show&o=lxguard>Click here to configure Lxguard </url> since it is very important that you understand what it does. Lxguard is critical for the security of your server, at the same time, it can block your own IPaddress from accessing the server, which can be frustrating if you don't know what's happening.";
$__emessage['root_cannot_extract_to_existing_dir'] = "Directory you provided already exists. Root user cannot extract archive into an existing directory. Please provide the name of a directory that doesn't exist in the system.";
$__emessage['no_imagemagick'] = "There is no imagemagick in the system. You can install imagemagick by running [b] yum -y install imagemagick [/b].";
$__emessage['warn_license_limit'] = "You are very close to your license limit for [%s]. If the system goes over limit for [%s] the interface will stop working and you won't be able to manage your system. Please increase your license at client.lxlabs.com and update by <url:o=license&a=show> clicking here </url>";
$__emessage['file_already_exists'] = "The file [%s] already exists.";
$__emessage['contact_set_but_not_correct'] = "Your Contact Information doesn't appear to be a valid email address. Click <url:a=updateform&sa=information> here to fix it.</url> ";
$__emessage['contact_not_set'] = "Your Contact Information is not set properly. Click <url:a=updateform&sa=information> here to fix it. </url> ";
$__emessage['you_have_unread_message'] = "You have [%s] Unread Message(s). click <burl:a=list&c=smessage> here  to read it. </burl>";
$__emessage['you_have_unread_ticket'] = "You have [%s] Unread Ticket(s). click <burl:a=list&c=ticket> here  to read it. </burl>";
$__emessage['security_warning'] = "Your password is now set as a generic password which constitutes a grave security threat. Please change it immediately by <url:a=updateform&sa=password> clicking here. </url> ";
$__emessage['ssh_port_not_configured'] = "The ssh port for this server is not set. It is a good idea to change it to something other than the default 22. Please  <url:a=show&o=sshconfig> click here to change:</url>. If you want to keep the ssh port to 22 and still avoid this message, go to the page, and set it forcibly to 22, and the warning will not be displayed again.";
$__emessage['system_is_updating_itself'] = "The system at this point is upgrading itself, and thus you won't be able to make any changes for a few minutes. All read actions work normally though.";
$__emessage['system_is_locked'] = "Someone has initiated system-modification-action on this particular object which is still going on. You wont be able to make any changes till it is finished. All read actions work normally though.";
$__emessage['system_is_locked_by_u'] = "You have initiated a system-modification-action which is still going on. You wont be able to make any changes till it is finished. All read actions work normally though.";
$__emessage['smtp_server_not_running'] = "hyperVM could not connect to an smtp server on this server. That means that hyperVM will not able to send out any mails. This is very critical since hyperVM monitors the health of the entire cluster and sends email to the admin if there is any problem. You should make sure that the smtp service is running on this server. Once you restart the SMTP service, please wait 5 minutes for this error message to disappear, since hyperVM checks for the service availability only once every 5 minutes.";
$__emessage['template_not_owner'] = "You are not the Owner of this Template";
$__emessage['ipaddress_changed_amidst_session'] = "IP Address Changed Amidst Session. Possible Session Hijacking.";
$__emessage['more_than_one_user'] = "More than one user is logged in this account. Click <burl:a=list&c=ssession>here to see list of logins. </burl> ";
$__emessage['login_error'] = "Login Unsuccessful";
$__emessage['file_exists'] = "file(s) [%s] Exists. Not Pasting...";
$__emessage['cannot_unzip_in_root'] = "You cannot unzip files into the root. Please specify a directory and unzip into that.";
$__emessage['nouser_email'] = "The Email doesn't match User's Contact Email Address";
$__emessage['session_expired'] = "Session Expired";
$__emessage['e_password'] = "Password Incorrect";
$__emessage['is_demo'] = "[%s] is Disabled in Demo Version.";
$__emessage['user_create'] = "User [%s] Could not be Created. Please try a different Name";
$__emessage['switch_done'] = "Switching the Servers has been run in the background. You will be sent a mail when the switch is complete.";
$__emessage['mis_changed'] = "Display Configuration successfully changed.";
$__emessage['password_sent'] = "Password was reset and sent successfully.";
$__emessage['added_successfully'] = "[%s] was added successfully.";
$__emessage['backup_has_been_scheduled'] = "The backup is now happening in the background. You will receive a mail at your contact email when it is done.";
$__emessage['update_scheduled'] = "Update is now running in the background. You can refresh this page to see if the update has completed properly.";
$__emessage['restore_has_been_scheduled'] = "The Restore is now happening in the background. You will receive a mail at your contact email when it is done.";
$__emessage['same_dns'] = "Master And Slave Cannot Be on the same Server.";
$__emessage['user_exists'] = "User [%s] already exists.";
$__emessage['mysql_error'] = "Mysql Error, Database Said: [%s]";
$__emessage['this_domain_does_not_resolve_to_this_ip'] = "To map an IP to a domain, the domain must ping to the same IP, otherwise, the domain will stop working. The domain you are trying to map this IP to, doesn't resolve back to the IP, and so it cannot be set as the default domain for the IP.";
$__emessage['dns_conflict'] = "The domain was not added due to an error in the dns settings. Please check your dns template and verify. The message from the dns server was [%s]";
$__emessage['add_without_www'] = "You should add only the main domain in the form of domain.com. The [b] www [/b] subdomain will be automatically added to it. You shouldn't add [b] www [/b] when creating a domain.";
$__emessage['could_not_connect_to_db'] = "Could Not Connect to Database: The error has been logged. Please contact the administrator.";
$__emessage['e_no_dbadmin_entries'] = "There are no Database administrator entries configured for this particular server. Please contact your admin to set them.";
$__emessage['please_add_one_domain_for_owner_mode'] = "You will need to have at least one domain if you want to switch to domain owner mode. You can add a domain by <url:a=addform&c=domain>clicking here </url>.";
$__emessage['e_no_dbadmin_entries_admin'] = "There are no Database administrator entries configured for this particular server. You have to go to the server section for this server, and click on the Dbadmin link, and add the database admin user and password for this particular machine and the type of database.";
$__emessage['mail_server_name_not_set'] = "The identification name for your mail server is not set. This means that many public mail servers like hotmail will reject mails from your server. Click <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=servermail> here to set it. </url>";
$__emessage['dns_template_inconsistency'] = "The Dns Template You have chosen is not consistent with your choice of the servers. For instance, it could be that the ipaddress in the dns is not at all found in the webserver. Please go back and create a dns template that has the parameters consistent with server setup.";
$__emessage['adding_cron_failed'] = "Adding crontab has failed due to [%s]. Please delete it and add it again.";
$__emessage['se_submit_running_background'] = "Search Engine Submission is running in the background. You will be sent a message to your contact email when it is done.";
$__emessage['err_no_dns_template'] = "There are no Dns Templates in the System. You have to have at least one Dns Template to add a domain/client. Click <url:a=addform&c=dnstemplate> here  to add a dnstemplate. </url></p> ";
$__emessage['certificate_key_file_empty'] = "The certificate and the Key file you have chosen are empty. You have to first create or upload them before enabling ssl";


// release on Kloxo 6.1.7
// by mustafa.ramadhan@lxcenter.org

$__information['webserver_config'] = 
	"[b]PHP Type[/b] - Process-based (httpd-prefork/-itk), thread-based (httpd-worker/-event) and ".
		"secure environment (suphp/suexec/ruid2/itk)<br />".
	"[b]Apache Memory Optimize[/b] - Optimize memory usage<br />".
	"[b]MySQL Convert[/b] - MyISAM (less memory usage (save 100-200 MB) and ".
		"InnoDB (higher performance)<br />".
	"[b]Fix 'Ownership' And 'Permissions'[/b] - Prevent '500 Internal server error' on secure environment<br />".
		"&nbsp;&nbsp;&nbsp;&nbsp;- Fix-ownership ('chown -R client:client' for directories and files) and ".
		"Fix-permissions ('chmod 755' for directories and 'chmod 644' for .php files)";

// Language Content for #656
// by Andrew Ying
$__emessage['document_root_may_not_contain_spaces'] = "The document root may not contain any space at the end or before the slash. Please check and submit again.";

// LxCenter - DT30012014
$__emessage['forwardaddress cannot be empty'] = 'The forward-to address cannot be empty.';
$__emessage['forwardaddress invaild'] = 'The forward-to address is invalid.';
$__emessage['folder_name_may_not_contain_doubledotsslash'] = "Folder name must not contain ../ (double dots).";
$__emessage['command_not_allowd'] = "Command not allowed! (You only have privilege to run 'php' or 'wget' in cron.)";

///6.1.19
$__information['click_to_update_all_under']="Click Here to Update all the objects that appear in the top selectbox with the above values";