<?php 

$driver['client'] = "sync";
$driver['phpini'] = "sync";
$driver['mysqldb'] = "mysql";
$driver['mysqldbuser'] = "mysql";
$driver['dbadmin'] = "sync";
$driver['sshauthorizedkey'] = "sync";
$driver['installappsnapshot'] = "sync";
$driver['mssqldb'] = "mssql";
$driver['mssqldbuser'] = "mssql";
$driver['sslcert'] = "sync";
$driver['sslipaddress'] = "sync";
$driver['anonftpipaddress'] = "__v_ftpuser";
$driver['ftpsession'] = "__v_ftpuser";
$driver['mailcontent'] = "__v_mmail";

$driver['reversedns'] = '__v_dns';
$driver['servermail'] = '__v_mmail';
$driver['serverftp'] = "__v_ftpuser";
$driver['serverweb'] = '__v_web';
$driver['webhandler'] = '__v_web';
$driver['webmimetype'] = '__v_web';
$driver['mailqueue'] = '__v_mmail';
$driver['process'] = '__v_pserver';
$driver['diskusage'] = '__v_pserver';
$driver['mailaccount'] = '__v_mmail';
$driver['mailalias'] = '__v_mmail';
$driver['listsubscribe'] = '__v_mailinglist';
$driver['autoresponder'] = '__v_mmail';
$driver['mailforward'] = '__v_mmail';
$driver['dirprotect'] = '__v_web';
$driver['watchdog'] = 'sync';
$driver['lxguard'] = 'sync';
$driver['lxguardwhitelist'] = 'sync';

