<?php 

$driver['hostdeny'] = "linux";
$driver['dns'] = array("bind", "djbdns", "powerdns", "nsd");
$driver['spam'] = array("bogofilter", "spamassassin");
$driver['mailinglist'] = "ezmlm";
$driver['ffile'] = "linux";
$driver['installsoft'] = "linux";
$driver['allinstallsoft'] = "linux";
$driver['pserver'] = "linux";
$driver['rubyrails'] = "linux";
$driver['uuser'] = "linux";
$driver['ftpuser'] = "pureftp";
$driver['web'] = array("apache", "lighttpd",  "nginx");
$driver['mmail'] = array("qmail", "postfix");
$driver['cron'] = "linux";
$driver['llog'] = "linux";
$driver['davuser'] = 'lighttpd';
$driver['sshconfig'] = 'linux';
