<?php 
include "common.inc";
$driver['web'] = "iis";
$driver['mmail'] = array("mailenable");
$driver['mailinglist'] = 'mailenable';
$driver['ipaddress'] = "windows";
$driver['pserver'] = "windows";
$driver['odbc'] = "windows";
$driver['service'] = "windows";
$driver['dns'] = "msdns";
$driver['installsoft'] = "windows";
$driver['allinstallsoft'] = "windows";
$driver['llog'] = "windows";
$driver['uuser'] = "windows";
$driver['cron'] = "windows";
$driver['hostdeny'] = "windows";
$driver['spam'] = "mailenable";
$driver['component'] = "windows";
$driver['package'] = "lxup2date";
$driver['ftpuser'] = "iisftp";
$driver['ffile'] = "windows";

