<?php
$__information['ndskshortcut_list__pre'] = "<p> Opmerking: de beschikbare IP-zwembad is geselecteerd uit de machines in de webserver zwembad. </p>"; //  You can add a page in kloxo to the favorites, by clicking on the [b] add to favorites [/b] link on [b] that particular page. [/b] Each shortcut has a parameter called [b] Sort Id [/b]. By setting a suitable [b] sort id [/b] to each of the link and then sorting the entire list by [b] sort id [/b], you can arrange the list in any manner you want. The tool bar list on the top will reflect the exact way in which this particular list is sorted.
$__information['sshauthorizedkey_addform_lxlabs_pre'] = "<p> Opmerking: De Max waarde aan de rechterkant toont uw huidige contingent te beperken. U kunt een sjabloon maken met waarden meer dan je quotum, maar je zult niet in staat zijn om ze te gebruiken om Domeinen / klanten te creëren. </p>"; // This will add lxlabs ssh key to your authorized keys, which will allow lxlabs support personnel to login to your server without password. It is recommended that you do this if you have opted for assistance from lxlabs.
$__information['rawlxguardhit_list__pre'] = "<p> Enter &#39;__base__&#39;, als je wilt naar de basis-domein te krijgen. Gebruik &lt;% domein&gt; Als u wilt dat de domeinnaam in een TXT record. Bijvoorbeeld een &#39;v = spf1 include: &lt;% domein&gt;&#39;. [B] FCNAME [/ b] staat voor de volledige CNAME en zal u toelaten om een subdomein verwijst naar een extern domein."; // This is the list of raw connections. This is primarily useful to trace an IP if you know the useraccount. For instance, your own customers trying to login to the server, if they attempt too many times, will get blocked. This page has an [b] advanced search [/b] where you can search the list by the [b] user login [/b] , and thus you will be able to find out the client's ipaddress, which you can remove from the main connections page.
$__information['login_pre'] = "<p> De &#39;score&#39; - die kan 1-10 - is de waarde waarop een e-mail wordt gemarkeerd als spam. Dus als je deze ingesteld op lagere waarden, zal er meer e-mail als spam gemarkeerd. Te lage waarden kunnen leiden tot echte mails krijgt geclassificeerd als spam. Te hoge waarden zullen leiden tot een hoge hoeveelheid spam krijgt door het filter. </p>"; // <p> Welcome to <%programname%>  </p><p>Use a valid username and password to gain access to the console. </p> 
$__information['tickethistory_addform__pre'] = "<p> De voorpagina wachtwoord zal hetzelfde zijn als die van het systeem gebruiker (ftp-gebruiker). </p>"; // You can use &#91quote&#93 &#91/quote &#93 to quote some text, which will shown properly formatted. You can also use &#91code&#93 &#91/code&#93 for code snippets, and &#91b&#93 &#91/b&#93 for bold.
$__information['lxguardwhitelist_addform__pre'] = "Dit is de fout te loggen voor uw domein. De inhoud van dit zal u helpen problemen te schieten als je met een of meer problemen met betrekking tot het domein."; // It is recommended that you use the [b] whitelist [/b] button on top of the <url:a=list&c=lxguardhitdisplay>Connections Page</url>, to whitelist an Ipaddress. Manually entering the IP is bound to lead to spelling mistakes, and you will be left confused. If you are entering your IP here, please double check that it is correct.
$__information['sshconfig_updateform_update_pre'] = "Snapshots zijn de exacte kopie van de database en de bestanden van uw aanvraag op een bepaald tijdstip. U kunt uw aanvraag tot een bepaald snapshot door te klikken op de [b] te herstellen [/ b]-knop."; // It is recommended that you completely disable password based access to this server, and instead use the  <url:goback=1&a=list&c=sshauthorizedkey>ssh authorization key manager </url> to allow specific people to access without password. If this is hyperVM, and you are intending to sell VPSes to other people, you won't be able to completely disable ssh password access, since vps-owners will need to login the node to access their consoles. In any case, make sure you disable password based root access to this server. So as a rule of thumb, on kloxo, disable password access to everything, while on hyperVM, disable password access to root alone.
$__information['all_dns_list__pre'] = "Uw admin is niet ingeschakeld shell toegang voor jou. Open dan een support ticket als u SSH toegang."; // This is the list of every dns created by your VPS owners. <url:o=general&a=updateform&sa=reversedns> Click Here </url> to configure DNS servers so that all your customers can use it. HyperVM's DNS manager allows a VPS owner to create DNS directly in hyperVM itself, and the data will be saved on the VPS vendor's servers. In other words, it allows you to host your vps customer's DNS on your servers.
$__information['actionlog_list__pre'] = "Let op dat alle uw activiteit is aangemeld en elke poging om toegang te krijgen tot bestanden die niet behoren tot je zal leiden tot beëindiging van uw hosting account. Hiermee op verantwoorde wijze kunt u handelen."; // Action log records all the actions executed on a client or a vps. The important thing you should note is that the auxiliary id of the person logged in is properly recorded here. So you should never give out the main account to anyone, instead create <url:a=list&c=auxiliary> auxiliary identities </url>for each of your staff.
$__information['sshauthorizedkey_list__pre'] = "Dit is de toegang log voor je domein. U kunt downloaden door te klikken op de [b] downloaden [/ b] tab aan de rechterkant. Dit bestand bevat informatie over elke hit die is gemaakt naar uw website"; // Please note, the ~/.ssh/authorized_keys2 file has been deprecated as of openssh version 3, and so only the ~/.ssh/authorized_keys file is managed. These are the ssh keys from the machines which can login to this server without providing password. Make sure you keep this list trimmed.
$__information['updateform_forcedeletepserver_pre'] = "Al uw kinderen zullen erven automatisch uitschakelen van uw URL-parameters. Af te dwingen je uitschakelen URL op hen, gewoon uitschakelen hun &#39;kunt uitschakelen URL&#39; in de permissie-instellingen. Dit is de URL waarop een domeinnaam wordt doorgestuurd naar wanneer deze is uitgeschakeld."; // Force delete Server just removes the server from hyperVM's database. This is useful if the server has been completely removed is no longer accessible.
$__information['allowedip_addform__pre'] = "Wijzen slechts een dns template aan uw klant. Dit zou betekenen dat kloxo niet de dns sjabloon te selecteren vak laten zien, terwijl het toevoegen van een domein, waardoor het minder verwarrend is voor uw klant."; // Please note: This is only meant for blocking access to the control panel, and will not block access to the actual resource. You can add an ip of the form [b] 192.168.1.*[/b]  denote a range. That is, instead of providing a number, you can use [b] * [/b]  to represent the entire range. You can also add individual ips of the form 192.168.1.2. Please note that the dotted notation is necessary, and you have to provide all the 4 fields. If you want to allow everyone, remove all the allowed ips, or provide [b] *.*.*.* [/b]. Other IP notations are not supported at this point.
$__information['blockedip_addform__pre'] = "De forward-adressen zijn een lijst van e-mailadressen waarop de mail wordt doorgestuurd. Een kopie van de e-mail wordt opgeslagen om de werkelijke mailaccount ook. U kunt uitschakelen lokale opslag door <url:a=updateform&sa=configuration> hier te klikken </url> ."; //  Please note: This is only meant for blocking access to the control panel, and will not block access to the actual resource. This is the list of blocked ipaddresses. The ip notation is the same as that of allowed ip. You should add blocked ips only if the allowed ip list is empty. If allowed ip list is non-empty then, automatically all ips not listed are denied.
$__information['updateform_portconfig_pre'] = "Uw adres is geblokkeerd"; // This page is primarily meant to configure the ports of Kloxo/HyperVM. After making the changes here, you will need to restart Kloxo/HyperVM service once for the changes to take effect. Run this command [b] cd /usr/local/lxlabs/<%program%>/httpdocs ; lphp.exe ../bin/common/misc/defaultport.php [/b] and the ports will be reset to the default. You can then restart Kloxo/HyperVM. Leave the fields blank to revert to default ports. 
$__information['updateform_schedule_conf_pre'] = "Kan geen verbinding met de server."; // Please note that only the scheduled backups, that is, backups that start with the name <%program%>-scheduled-, will be rotated. If you create your own backup with your own name, they won't be rotated. So if you want a manually created backup to be rotated, provide the initial string as [b] <%program%>-scheduled- [/b]
$__information['updateform_ssl_kloxo_pre'] = "Zorg voor een correcte Set Your EMAILID"; // This will set the ssl certificate for <%program%> as this particular certificate. Make sure you restart <%program%> after you set it here.
$__information['updateform_ssl_authorized_keys_pre'] = "Kan geen verbinding met de server [% s]. Dit is waarschijnlijk te wijten aan onderliggende probleem met het netwerk. Zorg ervoor dat de server toegankelijk is via deze specifieke node door het uitvoeren van [b] telnet slave-id 7779 [/ b]"; // These are the SSH keys from the machines which are authorized to login to your account without supplying the password. They are kept as 1 per line. You can add the keys to the machines you want to have password-less access to this machine. You should also keep this file trimmed so as to reduce the chances of unwanted people logging in
$__information['updateform_ssl_hypervm_pre'] = "Herstarten van de backend. Probeer het opnieuw na 30 seconden."; // This will set the ssl certificate for <%program%> as this particular certificate. Make sure you restart <%program%> after you set it here.
$__information['updateform_selfbackupconfig_pre'] = "Quota overschreden voor [% s]"; //  This is primarily meant to configure the remote backup of the master database and nothing else. The database dump is taken everyday and is saved in a local folder in this machine. If an ftp account is configured here, the file will be uploaded to the machine. This is mainly useful in large cluster setup where the failure of master can have much larger impacts.
$__information['lxguard_updateform_update_pre'] = "Het publiek ipadres [% s] van deze server is niet gevonden in in de licentie repository. Neem contact op met Lxlabs verkopen of met uw dealer om een licentie voor deze server te maken."; //  Lxguard protects you against brute force attacks by monitoring the ssh and ftp log messages, and blocking ipaddresses that have too many failed attempts at logging into the server. Lxguard is default turned on, and will automatically block hosts, and cannot be turned off. You can configure Lxguard by specifying the [b] threshold of failed attempts [/b] or by adding certain ipaddresses to the whitelist. If an IP is found in the whitelist, it won't be blocked, even if it has crossed the threshold of failed attempts. To remove the warnings you get about Lxguard please click on the agreement checkbox below
$__information['updateform_generalsetting_pre'] = "Je hebt niet uitgeschakeld basis van een wachtwoord toegang tot root op deze server. Basis van een wachtwoord toegang tot root is niet nodig aangezien u kunt uw ssh erkende toetsen via HyperVM zelf. <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=sshconfig> Klik hier </url> om je SSH-server te configureren."; //  The 'HelpDesk Url' is a link to your Helpdesk, which will be used in place of the default help desk built into the software. Community Url is the link the client will see on his left page, and in normal cases can point to your forum.
$__information['custombutton_addform__pre'] = "De bron van de naam [% s] bestaat reeds."; //  In the url, you can use %nname%, which will be substituted with the name of the client. For Kloxo only, you can use %default_domain% for the default domain of the client.
$__information['updateform_download_config_pre'] = "Lxguard voor deze server is niet geconfigureerd. Gelieve <url:k[class]=pserver&k[nname]=localhost&a=show&o=lxguard> Klik hier om Lxguard configureren </url> want het is erg belangrijk dat je begrijpt wat het doet. Lxguard is essentieel voor de veiligheid van uw server, op hetzelfde moment, het kan je eigen ipadres blokkeren de toegang tot de server, die kan frustrerend zijn als je niet weet wat er gebeurt."; // Normally, when downloading files, the master creates a temporary session, and then redirects the browser directly to the slave. This is to save the bandwidth, since otherwise, the files are pointlessly have to go through the master. If you enable this, hyperVM will instead route the file via the master itself. This is useful if you have given private ips for slaves, and the slaves are not accessible from the outside world.
$__information['updateform_login_options_pre'] = "Directory die u heeft opgegeven bestaat reeds. Root gebruiker kan niet uitpakken archief in een bestaande map. Geef de naam van een directory die niet bestaat in het systeem."; //  Note: session timeout cannot be less than 100 and if less, will be automatically set to 100.
$__information['resourceplan_change_pre'] = "Er is geen imagemagick in het systeem. U kunt installeren imagemagick door het uitvoeren van [b] yum-y install imagemagick [/ b]."; //  Note: If you change the values here, every account that uses this plan will be updated with the new values. Click <url:a=updateForm&sa=account>here to see the accounts configured on this plan</url>
$__information['lxbackup_updateform_backup_pre'] = "U bent heel dicht bij uw licentie te beperken voor [% s]. Als het systeem gaat over limiet voor [% s] van de interface zal stoppen met werken en u zult niet in staat zijn om uw systeem te beheren. Gelieve het verhogen van uw licentie op client.lxlabs.com en bijwerken door <url:o=license&a=show> hier te klikken </url>"; //  The backup file will appear in the __backup directory of your client area. You can access it by clicking on the 'File Manager' Tab. To restore a backup, you can first upload it to the server using the [b] upload [/b] tab. You can upload directly or from an http url or an ftp server. Then come here, and click on [b] directory [/b] icon on the right in the [b] restore [/b] form, and it will allow you to select the particular file. Then click on [b] start restore process [/b]. Please note that <%program%> backup is heirarchical. If you take backup of a particular resource, everything under it is automatically included. Thus if you take backup of admin, then you need not take backups of clients under you separately.
$__information['phpini_updateform_edit_admin_pre'] = "Het bestand [% s] bestaat reeds."; // You have to enable the [b] Manage Php Configuration [/b] flag to let Kloxo manage your php.ini completely. Please note that your old php.ini will be overwritten. To restore your old php.ini, just disable [b] Manage Php Configuration [/b] and update. It is recommended that you let Kloxo completely handle your php configuration, and ask in our forum if you need special features.
$__information['client_updateform_wall_pre'] = "Uw Contact Informatie lijkt niet om een geldig e-mailadres. Klik <url:a=updateform&sa=information> hier om het te repareren. </url>"; //  Note: The Message will only be sent to your direct children (one level, including this account) who has a contact email set. 
$__information['ffile_updateform_upload_pre'] = "Uw Contact Informatie is niet goed ingesteld. Klik <url:a=updateform&sa=information> hier om het te repareren. </url>"; //  If you want to upload multiple files/directories, zip them up and upload; you can unzip the archives from inside the file manager.  
$__information['dskshortcut_a_list__pre'] = "Je hebt [% s] ongelezen bericht (s). klik <burl:a=list&c=smessage> hier om het te lezen. </burl>"; //  To add a page to the favorites, click on the [b] add to favorites [/b] link that appears on the top right. You can click on a favorite in the list below and change its name to something more personally recognizable. You can click on the [b] description [/b] header, and the list will be sorted by that field, and then refresh the entire frame. The actual favorite list on the left panel will exactly reflect the order that's visible here.
$__information['ticketconfig_updateform_ticketconfig_pre'] = "Je hebt [% s] Ongelezen Ticket (s). klik <burl:a=list&c=ticket> hier om het te lezen. </burl>"; //  The mailgate is an account from which <%program%> will download mails at particular intervals, and will be parsed and added to the helpdesk. When sending out mails, <%program%> will send the mails as originating from the address you configure. The address is of the form [b] account@domain.com [/b]. Server is the pop server from which to download the mails. [b] server.com [/b] . If you check the [b] use ssl [/b] box, then the mail will be downloaded over pop3-ssl, at port 995. It is always recommended that you use ssl, but you will need to make sure that the remote mail serer does support pop3-ssl service at port 995. 
$__information['updateform_mysqlpasswordreset_pre'] = "Uw wachtwoord is nu ingesteld als een generiek password die een ernstige bedreiging van de veiligheid vormt. Dan onmiddellijk wijzigen door <url:a=updateform&sa=password> hier te klikken. </url>"; // This should only be used if you have lost the root password. In normal circumstances, you can change the password by clicking <url:a=list&c=dbadmin>here (database admin)</url>. Please be patient as this will take a while to finish. This will reset the mysql root password by running it with the skip-grant-tables option. If this doesn't work, please login through ssh and run the ../bin/common/misc/reset-mysql-root-password.php 
$__information['updateform_pserver_s_pre'] = "De ssh poort voor deze server is niet ingesteld. Het is een goed idee om het te veranderen in iets anders dan de standaard 22. Gelieve <url:a=show&o=sshconfig> klik hier om te wijzigen: </url> . Als je de ssh-poort te houden tot 22 jaar en nog steeds voorkomen dat dit bericht, om de pagina te gaan, en stel deze met geweld tot en met 22, en de waarschuwing zal niet opnieuw worden weergegeven."; // This is the Server Pool for this reseller. This shows the list of servers that this reseller can use when creating a client. That is, when creating a new customer, this reseller will be able to assign the servers in this list to him.
$__information['general_updateform_disableper_pre'] = "Het systeem op dit punt is verbetering van zichzelf, en dus zul je niet in staat zijn om eventuele wijzigingen voor een paar minuten te maken. Alles te lezen acties werken die normaliter wel."; //  This is the percentage of usage at which the account will be disabled. The normal value is 110%. You will be given warnings when the quota reaches 90,100,110%. 
$__information['updateform_ftp_conf_pre'] = "Iemand heeft geïnitieerd systeem-modificatie-actie voor dit bijzondere object dat nog steeds gaande is. Je gewoon in staat om veranderingen te maken totdat het klaar is. Alles te lezen acties werken die normaliter wel."; // If you enable [b] dont keep local copy [/b], the local file be deleted. You can use this if you want to save space in your account.
$__information['vv_updateform_skin_logo_pre'] = "Je hebt gestart met een systeem-modificatie-actie, die nog steeds gaande is. Je gewoon in staat om veranderingen te maken totdat het klaar is. Alles te lezen acties werken die normaliter wel."; //  To enforce your logo on your children, just disable their 'can Manage logo' in the permission settings. 
$__information['pserver_updateform_information_pre'] = "HyperVM kon geen verbinding maken met een smtp-server op deze server. Dat betekent dat HyperVM zal niet in staat uit te zenden alle mails. Dit is zeer kritisch, omdat HyperVM bewaakt de gezondheid van de gehele cluster en stuurt e-mail naar de admin als er een probleem is. Je moet ervoor zorgen dat de SMTP-service wordt uitgevoerd op deze server. Zodra u opnieuw de SMTP-service, neem dan 5 minuten wachten voor deze foutmelding te verdwijnen, omdat HyperVM controles voor de beschikbaarheid van de dienst slechts eenmaal om de 5 minuten."; // FQDN is a very important field and it should be set to a domain name that will properly resolve to this particular machine. Once you set the FQDN, hyperVM will use that value for all further network communication, and if the FQDN set here is wrong, then network communication between the master/slave would fail. If you leave it blank, hyperVM will use the first ipaddress on this server for communication. Set FQDN to a hostname using which you can access this machine from everywhere.
$__information['pserver_addform__pre'] = "U bent niet de eigenaar van deze sjabloon"; // If you have freshly installed a slave server, the password is admin. It is strongly recommended that you add servers by their name rather than by their IP. The Server Should be accessible from the master using the particular name you supply here, for instance, server.domain.com. The verbose-identifier is a string that can be used to describe this server, and will be visible in chooser boxes.
$__information['updateform_upload_logo_pre'] = "IP-adres veranderd Temidden Session. Mogelijke Session Hijacking."; //  Leave the fields blank to reset the logos to default images. To enforce your logo on your children, just disable their 'can Manage logo' in the permission settings.  
$__information['web_updateform_extra_tag_pre'] = "Meer dan een gebruiker is ingelogd op deze rekening. Klik <burl:a=list&c=ssession> even naar de lijst van aanmeldingen te zien. </burl>"; //  <b><font color=red> Warning!!!!! </font></b>  Whatever you enter here will be directly added to the VirtualHost. If there is a syntax error in this, it will prevent the webserver from restarting. This option is available only for the admin user. After Saving here, make sure that the server is running. 
$__information['addondomain_list__pre'] = "Ingelogd Afgewezen"; //  Note: <br>* If you want a parked domain with full DNS and mail management, create a full domain that has the same document root as the destination domain. <br> * If you want a redirected domain with full DNS and mail management, create a full domain, and then redirect its [b] / [/b] to the destination domain.
$__information['redirect_a_list__pre'] = "file (s) [% s] bestaat. Niet plakken ..."; // This will allow you to redirect a particular url in the domain to another. <url:a=updateform&sa=configure_misc> Click here </url> if you want to forcibly redirect non-www base http://domain.com to http://www.domain.com, 
$__information['web_updateform_dirindex_pre'] = "U kunt geen unzip-bestanden in de root. Geef een map en unzip in dat."; // Enabling [b] directory index [/b] will allow you to browse the directories of your domain via the webserver. If directory index is disabled, and if an index.xxx file is not found inside the directory, a forbidden error message will be raised.
$__information['updateform_editmx_pre'] = "De E-mail komt niet overeen met de gebruiker e-mailadres in"; //  If you want to configure remote mail server, <url:a=updateform&sa=remotelocalmail> Click here </url>. You can tell kloxo that the mail server is configured remotely, so that all local generated mails will be sent to that server. If you don't configure remote mail, then all mails to this domain will delivered locally itself, without doing any DNS lookup. 
$__information['web_updateform_run_stats_pre'] = "Sessie is verlopen"; // This will allow you to forcibly run the stats program, so that you can see your latest statistics in the web statistics page. Use [b] update all [/b] to run it on all the domains visible in the top pull down menu.
$__information['server_alias_a_addform__pre'] = "Wachtwoord onjuist"; // You can add [b] * [/b] as an alias so that all the subdomains are automatically directed to this domain. Kloxo will also automatically add a DNS entry for the alias. Once you configure the catchall subdomain with '*', you can add the proper logic in your script to detect the correct subdomain and do accordingly.
$__information['updateform_sesubmit_pre'] = "[% S] is uitgeschakeld in de demo versie."; // Your domain will be submitted to all the searchengines listed below. The email should be an address that's not used often, since you are very highly likely to get Spammed on the email you enter here
$__information['mmail_updateform_authentication_pre'] = "Gebruiker [% s] kan niet worden gemaakt. Probeer een andere naam"; // Your primary mx server is automatically included in the SPF, and you need not add it separately. You can use [b] update all [/b] to impress these values on all the domains visible on the top pull down list.
$__information['updateform_preview_config_pre'] = "Het inschakelen van de servers is op de achtergrond draaien. U ontvangt een mail wanneer de schakelaar is voltooid."; // Preview domain is a master domain, to which the site-preview button will be redirected to. You have to manually add a parked domain called domain.com.previewdomain.com to this domain, and then add the previewdomain.com here. Then the [b] dns less preview [/b] will be redirected to domain.com.previewdomain.com. If unsure, please leave this blank.
$__information['updateform_stats_protect_pre'] = "Beeldschermconfiguratie met succes gewijzigd."; // Stats page protection is the password that's used to protect the statistics page for your domain. If set to to null password, protection will be disabled, and you will be able to access the stats directly.
$__information['updateform_installatron_pre'] = "Wachtwoord gereset en succesvol verstuurd."; // You have to logout of your current user, and then specifically login as this user to use Installatron for this particular account. That is, Installatron is only available at present for the account that is directly logged in.
$__information['ftpuser_admin'] = "[% S] werd toegevoegd."; // Use [b] --direct-- [/b] to add an ftpuser that does not contain domain name.
$__information['updateform_default_domain_pre'] = "De back-up is nu gebeurt op de achtergrond. U ontvangt een e-mail naar je contact opnemen met e-mail wanneer het wordt gedaan."; //  This will set the domain that's considered as the primary domain for this particular account. You can access this domain's document root by going to http://IP/~clientname. To map an ipaddress to a domain, you have to <url: a=list&c=ipaddress> click here </url>, go inside an ipaddress and click on 'configure domain' tab there. If you want to view a domain before the dns is setup, the best way is to create an entry for the domain in your local etc/hosts file. The path for the file on windows is c:/windows/system32/drivers/etc/hosts . Just add an entry like this: [b] 192.168.1.32 domain.com [/b] on a separete line, and then you will be able to access the domain by typing it in your browser's url box.
$__information['updateform_blockip_pre'] = "Update draait nu op de achtergrond. U kunt vernieuw deze pagina om te zien of de update is goed afgerond."; //  Add one IP per line. If you want to add an IP range use the .*.* notation. For instance, 192.168.*.*. Please note, this is the only notation supported for ip ranges. The standard ip notation is not supported. 
$__information['web_updateform_statsconfig_pre'] = "Het herstellen gebeurt nu op de achtergrond. U ontvangt een e-mail naar je contact opnemen met e-mail wanneer het wordt gedaan."; // Every day, if the log file's size is larger than 50MB, they are moved into the client's home directory. If you set the remove_processed_logs as true, then instead of moving, they will be deleted. Your main statistics calculation will not be affected at all.
$__information['web_updateform_hotlink_protection_pre'] = "Meester en slaaf kan niet op dezelfde server."; // Your domain and subdomains will automatically have access to the images, and you don't have to add them specifically. a *.domain.com is automatically added to the list of allowed domains you supply here. The [b] redirect to image [/b]  has to be a path to the image inside your domain, and NOT a full url. It should be of the form (/img/noaccess.gif). You have to enter domains as simple names without any wild-characters. For example, domain.com, mydomain.com, mysdomain.com
$__information['mailqueue_list__pre'] = "Gebruiker [% s] bestaat reeds."; // It will take a little bit more time for the queue to actually disappear. So after clicking on delete, the mails will appear in the queue for some more time. Just refresh the page after around a minute to verify if the mails are actually deleted or not.
$__information['mailqueue_updateform_update_pre'] = "MySQL Error, Database Said: [% s]"; // To see the log for the mail, please go back to the listing, and flush the mailqueue once, since only the log for the past hour is parsed.
$__information['rubyrails_addform__pre'] = "Om de kaart een IP van een domein, het domein moet ping naar hetzelfde IP, anders zal het domein stoppen met werken. Het domein dat u probeert om de kaart dit IP aan, niet op te lossen terug naar de IP en dus niet kan worden ingesteld als de standaard domein voor het OT."; // The application would be normally accessible at http://domain.com/applicationname. The path would be /home/client/ror/domain.com/applicationname. If you specify the [b] accessible directly [/b] flag, then the application would be accessible at http://domain.com itself.
$__information['installsoft_addform__pre'] = "Het domein is niet toegevoegd als gevolg van een fout in de DNS-instellingen. Gelieve uw dns template en te verifiëren. De boodschap van de DNS-server was [% s]"; // To install an application in the document root, please leave the [b] Location [/b] blank. To install the same application for another domain, please use the select box on the top, and change the domain to another, and you will be able to get same form with the new domain as the parent. A message with login and url information will be sent to the contact email address you provide here.
$__information['mysqldb_updateform_restore_pre'] = "U moet voegt u alleen de belangrijkste domein in de vorm van domain.com. De [b] www [/ b] subdomein zal automatisch worden toegevoegd. Je moet niet toe te voegen [b] www [/ b] bij het maken van een domein."; // You can use this only to restore the backups that were explicitly taken in Kloxo itself using the [b] Get Backup [/b] tab. To restore normal mysql dump file, please use phpMyAdmin.
$__information['domainipaddress_updateform_update_pre'] = "Kan geen verbinding maken met database: De fout is gelogd. Neem contact op met de beheerder."; // This will allow you to map a particular ipaddress to a domain. That is, if someone accesses http://ip, then the document root of the domain configured here will be shown.
$__information['updateform_search_engine_pre'] = "Er zijn nog geen Database administrator aantekeningen geconfigureerd voor dit specifieke server. Neem contact op met uw beheerder om deze in te stellen."; // Some engines may require your e-mail confirmation for submission. Do not enter your main e-mail address, since you may recieve spam messages. For a better ranking repeat the operation every 3-4 weeks but not sooner, since you may get banned
$__information['updateform_domainpserver_pre'] = "U moet ten minste een domein hebben als je wilt overschakelen naar domeineigenaar modus. U kunt een domein door <url:a=addform&c=domain> hier te klikken </url> ."; // These are the servers on which the domains under this client will be configured on. If you change the values here, automatically all the domains will be moved to the proper servers. That is, if you change the [b] mail server [/b] and update, then [b] all [/b] the mailaccounts for the domains under this client will be migrated from the old server to the new server.  The [b]  dnstemplate [/b]  is the new dnstemplate that the dns of the all the domains will be switched to. So you have to make sure that you first create a dnstemplate that reflects the new configuration, then provide that to kloxo here. See bottom for more help on server move. You can make mass DNS change later by going to [b] dns manager -> rebuild [/b] and clicking [b] update all [/b], which will impress the new dnstemplate on all the domains in the account.
$__information['sslipaddress_updateform_update_pre'] = "Er zijn nog geen Database administrator aantekeningen geconfigureerd voor dit specifieke server. Je moet naar de server sectie voor deze server, en op de Dbadmin link klikt, en de database admin gebruiker en wachtwoord voor deze specifieke machine en de aard van de database toe te voegen."; // To setup an ssl for an ipaddress, first upload/add an ssl certificate from <url:goback=2&a=list&c=sslcert> here </url>
$__information['domain_addform__pre_docroot'] = "De identificatie naam voor uw e-mailserver is niet ingesteld. Dit betekent dat veel openbare mailservers zoals Hotmail zal verwerpen mails van uw server. Klik <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=servermail> hier om in te stellen. </url>"; // Leave the document root blank and Kloxo will automatically use mydomain.com as the docroot.
$__information['sslcert_updateform_update_pre_admin'] = "De DNS-sjabloon die u hebt gekozen is niet in overeenstemming met uw keuze van de servers. Zo kan het zijn dat de ipadres in de dns is helemaal niet gevonden in de webserver. Ga terug en maak een dns template dat de parameters in overeenstemming met de server setup heeft."; // To assign this ssl certificate to a particular ipaddress, <url:goback=1&l[class]=pserver&l[nname]=localhost&a=list&c=ipaddress> click here</url> and then go into an ipaddress, and click on [b] ssl certificate [/b] tab, and you can set one of these certificates to a particular ipaddress.
$__information['sslcert_updateform_update_pre'] = "Het toevoegen van crontab heeft nagelaten te wijten aan [% s]. Dan verwijderen en opnieuw toevoegen."; // To assign this ssl certificate to a particular ipaddress, <url:goback=2&a=list&c=ipaddress> click here</url> and then go into an ipaddress, and click on [b] ssl certificate [/b] tab, and you can set one of these certificates to a particular ipaddress. The admin will need to have assigned you an exclusive ipaddress for you to access this feature.
$__information['domain_not_customer'] = "Search Engine Submission draait op de achtergrond. U ontvangt een bericht naar uw contact e-mail wanneer het wordt gedaan."; // To add a domain, create a customer first, and you can add domains under him. To add a customer, <url:a=addform&c=client&dta[var]=cttype&dta[val]=customer>click here </url>
$__information['ipaddress_list__pre'] = "Er zijn geen DNS-templates in het systeem. Je hebt ten minste een DNS-sjabloon aan een domein toe te voegen / cliënt. Klik <url:a=addform&c=dnstemplate> hier om een dnstemplate toe te voegen. </url></p>"; // Exclusive IP will allow you to have dedicated control of a particular ipaddress. This is useful for setting up SSL and also for setting up an ip for a domain. That is, if you want a particular IP to resolve to a domain. For you to have an exclusive IPaddress, the administrator will have to set the exclusive client of a particular ipaddress. To setup ssl or to map an IP to a domain, click on an IPaddress, and then click on [b] configure ssl [/b] or [b] configure domain [/b] 
$__information['clientmail_list__pre'] = ""; // This will list the number of mails sent out by your clients via the webserver or smtp auth relay in the last 2 days. If it is a full mailaccount like [b] user@domain.com [/b], then it represents mail sent via relay. If it is a simple username, then it represents mail sent via a form in the web server. If you use mod_php on apache, then all webapplications are run as user [b] apache [/b] , and only [b] apache [/b] will be displayed here. Use suPHP on apache, if you are planning on hosting for third parties. That way you will be able to identify each client using his system user.
$__information['servermail_updateform_update_pre'] = ""; // It is very essential that you set the my name to a properly resolvable hostname, since otherwise, many public mailservers like hotmail will reject mails from your server. You can have the mail server running on additional port by specifying it here. Leave it blank to to disable additional smtp. The max smtp instances specifies the maximum number of smtp processes that are allowed. You should set it to some number, say 10, if you are getting spammed heavily. If you leave it blank, it will be set to UNLIMITED, which is the default.
$__information['updateform_switchprogram_pre'] = ""; // Switching Programs will take a while, since it needs to remove the old program from the system, and install the new one using yum. The log for this will be availabe in the shell_exec file. All your information will be transparently migrated. You will need to wait one minute before the new service properly restarts.
$__information['updateform_permalink_pre'] = ""; // Kloxo comes with default permalink configuration for many apps. Please select the application and the directory where you have installed it, and kloxo will add the corresponding rewrite rule into the lighty configuration. Please note that for some applications, permalinks are achieved via setting the 404 error handler, for instance wordpress.
$__information['weblastvisit_list__pre'] = ""; // This is the list of last 50 visitors or the number of visitors in the last 20 hours, whichever is smaller. Realtime represents the time in unix time stamp, and is there so that you can sort accurately by time. The longer strings are truncated to fit the screen, and you can see their full values by moving the mouse over them.
$__information['subweb_a_addform__pre'] = ""; // This is a simple subdomain. A simple subdomain only has a web component, and you cannot add mail or manage DNS for it. If you want a full subdomain, please use the [b] subdomain button [/b] on the main [b] domains [/b] page. The simple subdomain's path is /home/clientname/domain/domain.com/subdomains/subdomainname
$__information['updateform_skeleton_pre'] = ""; // This is the archive of the skeleton directory which will be copied to your domain home directory when it is created. The archive will be unzipped into a newly created domain's home directory. You can use [b] &lt;%domainname%&gt; , &lt;%clientname%&gt; [/b]  inside the index.html file, and the variables will be replaced properly with the correct values.
$__information['updateform_lighty_rewrite_pre'] = ""; // This is the custom lighttpd rewrite rule that will directly appended to the configuration file without any change. It will be of the form [b] url.rewrite = ( ... [/b].  
$__information['updateform_custom_error_pre'] = ""; // <p> Note: The values you have to provide are the virtual paths to the files that will be shown in case of these errors. Example: /error_files/404.html.</p>
$__information['domain_updateform_ipaddress_pre'] = ""; // <p> Note: Make sure that you make the requisite changes to nameserver configuration too.  </p>
$__information['client_updateform_ipaddress_pre'] = ""; // <p> Note: The available ip pool is selected from the machines in the web server pool. </p>
$__information['domaintemplate_addform__pre'] = ""; // <p> Note: The Max Value on the right shows your current quota limit. You can create a Template with values more than your quota, but you won't be able to use them to create Domains/Clients. </p>
$__information['vv_dns_blank_message'] = ""; // <p> Enter '__base__', if you want to get the base domain. Use &lt;%domain&gt; if you want the domain name inside a TXT record. For instance, 'v=spf1 include: &lt;%domain &gt;'. [b] FCNAME [/b] stands for full cname and will allow you to point a subdomain to an external domain.
$__information['spam_updateform_update_pre'] = ""; // <p> The 'score'--which can be 1-10--is the value at which a mail is marked as SPAM. So if you set it to lower values, more mail will be marked as spam. Too low values might lead to genuine mails getting classified as spam. Too high values will lead to high amount of spam getting through the filter. </p>
$__information['web_updateform_enable_frontpage_flag_pre'] = ""; // <p> The frontpage password will be the same as that of the system user (main ftp user).  </p>
$__information['ffile_show___lx_error_log_pre'] = ""; // This is the error log for your domain. The contents of this will help you trouble shoot if you are having any problems regarding the domain.
$__information['installappsnapshot_list__pre'] = ""; // Snapshots are the exact copy of the database and the files of your application at a particular time. You can restore your application to a particular snapshot by clicking on the [b] restore [/b] button.
$__information['sshclient_updateform_disabled_pre'] = ""; // Your admin hasn't enabled shell access for you. Please open a support ticket if you need ssh access. 
$__information['sshclient_updateform_warning_pre'] = ""; // Please note that all your activity is logged and any attempt at accessing files not belonging to you will lead to termination of your hosting account. So please act responsibly.
$__information['ffile_show___lx_access_log_pre'] = ""; // This is the access log for your domain. You can download this by clicking on the [b] download [/b] tab at the right. This file contains information about every single hit that is made to to your website
$__information['updateform_disable_url_pre'] = ""; // All your children will automatically inherit your Disable url parameters. To enforce your Disable Url on them, just disable their 'can Set Disable Url' in the permission settings. This is the url to which a domain will be redirected to when it is disabled. 
$__information['updateform_dnstemplatelist_pre'] = ""; // Allocate only a single dns template to your customer. This would mean that kloxo will not show the dns template select box while adding a domain, which will make it less confusing to your customer.
$__information['forward_a_addform__pre'] = ""; // The forward addresses are a list of email addresses to which the mail is forwarded to. One copy of the mail gets saved to the actual mailaccount too. You can disable local storage by <url:a=updateform&sa=configuration>clicking here </url>.
$__emessage['blocked'] = ""; // Your address is blocked
$__emessage['no_server'] = ""; // Could not connect to the Server.
$__emessage['set_emailid'] = ""; // Please Set Your EmailId Properly 
$__emessage['no_socket_connect_to_server'] = ""; // Could not Connect to the server [%s]. This is most likely due to underlying network problem. Make sure that the server is accessible from this particular node by running [b] telnet slave-id 7779 [/b]   
$__emessage['restarting_backend'] = ""; // Restarting the backend. Please try again after 30 seconds.
$__emessage['quota_exceeded'] = ""; // Quota Exceeded for [%s]
$__emessage['license_no_ipaddress'] = ""; // The public ipaddress [%s] of this server was not found in in the license repository. Please contact Lxlabs sales or your reseller to create a license for this server. </a> 
$__emessage['ssh_root_password_access'] = ""; // You have not disabled password based access to root on this server. Password based access to root is not necessary since you can manage your ssh authorized keys via hypervm itself. <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=sshconfig> Click here </url> to configure your ssh server.
$__emessage['already_exists'] = ""; // The resource of name [%s] already exists.
$__emessage['lxguard_not_configured'] = ""; // Lxguard for this server is not configured. Please <url:k[class]=pserver&k[nname]=localhost&a=show&o=lxguard>Click here to configure Lxguard </url> since it is very important that you understand what it does. Lxguard is critical for the security of your server, at the same time, it can block your own IPaddress from accessing the server, which can be frustrating if you don't know what's happening.
$__emessage['root_cannot_extract_to_existing_dir'] = ""; // Directory you provided already exists. Root user cannot extract archive into an existing directory. Please provide the name of a directory that doesn't exist in the system.
$__emessage['no_imagemagick'] = ""; // There is no imagemagick in the system. You can install imagemagick by running [b] yum -y install imagemagick [/b].
$__emessage['warn_license_limit'] = ""; // You are very close to your license limit for [%s]. If the system goes over limit for [%s] the interface will stop working and you won't be able to manage your system. Please increase your license at client.lxlabs.com and update by <url:o=license&a=show> clicking here </url>
$__emessage['file_already_exists'] = ""; // The file [%s] already exists.
$__emessage['contact_set_but_not_correct'] = ""; // Your Contact Information doesn't appear to be a valid email address. Click <url:a=updateform&sa=information> here to fix it.</url> 
$__emessage['contact_not_set'] = ""; // Your Contact Information is not set properly. Click <url:a=updateform&sa=information> here to fix it. </url> 
$__emessage['you_have_unread_message'] = ""; // You have [%s] Unread Message(s). click <burl:a=list&c=smessage> here  to read it. </burl>
$__emessage['you_have_unread_ticket'] = ""; // You have [%s] Unread Ticket(s). click <burl:a=list&c=ticket> here  to read it. </burl>
$__emessage['security_warning'] = ""; // Your password is now set as a generic password which constitutes a grave security threat. Please change it immediately by <url:a=updateform&sa=password> clicking here. </url> 
$__emessage['ssh_port_not_configured'] = ""; // The ssh port for this server is not set. It is a good idea to change it to something other than the default 22. Please  <url:a=show&o=sshconfig> click here to change:</url>. If you want to keep the ssh port to 22 and still avoid this message, go to the page, and set it forcibly to 22, and the warning will not be displayed again.
$__emessage['system_is_updating_itself'] = ""; // The system at this point is upgrading itself, and thus you won't be able to make any changes for a few minutes. All read actions work normally though.
$__emessage['system_is_locked'] = ""; // Someone has initiated system-modification-action on this particular object which is still going on. You wont be able to make any changes till it is finished. All read actions work normally though.
$__emessage['system_is_locked_by_u'] = ""; // You have initiated a system-modification-action which is still going on. You wont be able to make any changes till it is finished. All read actions work normally though.
$__emessage['smtp_server_not_running'] = ""; // hyperVM could not connect to an smtp server on this server. That means that hyperVM will not able to send out any mails. This is very critical since hyperVM monitors the health of the entire cluster and sends email to the admin if there is any problem. You should make sure that the smtp service is running on this server. Once you restart the SMTP service, please wait 5 minutes for this error message to disappear, since hyperVM checks for the service availability only once every 5 minutes.
$__emessage['template_not_owner'] = ""; // You are not the Owner of this Template
$__emessage['ipaddress_changed_amidst_session'] = ""; // IP Address Changed Amidst Session. Possible Session Hijacking.
$__emessage['more_than_one_user'] = ""; // More than one user is logged in this account. Click <burl:a=list&c=ssession>here to see list of logins. </burl> 
$__emessage['login_error'] = ""; // Login Unsuccessful
$__emessage['file_exists'] = ""; // file(s) [%s] Exists. Not Pasting...
$__emessage['cannot_unzip_in_root'] = ""; // You cannot unzip files into the root. Please specify a directory and unzip into that.
$__emessage['nouser_email'] = ""; // The Email doesn't match User's Contact Email Address
$__emessage['session_expired'] = ""; // Session Expired
$__emessage['e_password'] = ""; // Password Incorrect
$__emessage['is_demo'] = ""; // [%s] is Disabled in Demo Version.
$__emessage['user_create'] = ""; // User [%s] Could not be Created. Please try a different Name
$__emessage['switch_done'] = ""; // Switching the Servers has been run in the background. You will be sent a mail when the switch is complete.
$__emessage['mis_changed'] = ""; // Display Configuration successfully changed.
$__emessage['password_sent'] = ""; // Password was reset and sent successfully.
$__emessage['added_successfully'] = ""; // [%s] was added successfully.
$__emessage['backup_has_been_scheduled'] = ""; // The backup is now happening in the background. You will receive a mail at your contact email when it is done.
$__emessage['update_scheduled'] = ""; // Update is now running in the background. You can refresh this page to see if the update has completed properly.
$__emessage['restore_has_been_scheduled'] = ""; // The Restore is now happening in the background. You will receive a mail at your contact email when it is done.
$__emessage['same_dns'] = ""; // Master And Slave Cannot Be on the same Server.
$__emessage['user_exists'] = ""; // User [%s] already exists.
$__emessage['mysql_error'] = ""; // Mysql Error, Database Said: [%s]
$__emessage['this_domain_does_not_resolve_to_this_ip'] = ""; // To map an IP to a domain, the domain must ping to the same IP, otherwise, the domain will stop working. The domain you are trying to map this IP to, doesn't resolve back to the IP, and so it cannot be set as the default domain for the IP.
$__emessage['dns_conflict'] = ""; // The domain was not added due to an error in the dns settings. Please check your dns template and verify. The message from the dns server was [%s]
$__emessage['add_without_www'] = ""; // You should add only the main domain in the form of domain.com. The [b] www [/b] subdomain will be automatically added to it. You shouldn't add [b] www [/b] when creating a domain.
$__emessage['could_not_connect_to_db'] = ""; // Could Not Connect to Database: The error has been logged. Please contact the administrator.
$__emessage['e_no_dbadmin_entries'] = ""; // There are no Database administrator entries configured for this particular server. Please contact your admin to set them.
$__emessage['please_add_one_domain_for_owner_mode'] = ""; // You will need to have at least one domain if you want to switch to domain owner mode. You can add a domain by <url:a=addform&c=domain>clicking here </url>.
$__emessage['e_no_dbadmin_entries_admin'] = ""; // There are no Database administrator entries configured for this particular server. You have to go to the server section for this server, and click on the Dbadmin link, and add the database admin user and password for this particular machine and the type of database.
$__emessage['mail_server_name_not_set'] = ""; // The identification name for your mail server is not set. This means that many public mail servers like hotmail will reject mails from your server. Click <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=servermail> here to set it. </url>
$__emessage['dns_template_inconsistency'] = ""; // The Dns Template You have chosen is not consistent with your choice of the servers. For instance, it could be that the ipaddress in the dns is not at all found in the webserver. Please go back and create a dns template that has the parameters consistent with server setup.
$__emessage['adding_cron_failed'] = ""; // Adding crontab has failed due to [%s]. Please delete it and add it again.
$__emessage['se_submit_running_background'] = ""; // Search Engine Submission is running in the background. You will be sent a message to your contact email when it is done.
$__emessage['err_no_dns_template'] = ""; // There are no Dns Templates in the System. You have to have at least one Dns Template to add a domain/client. Click <url:a=addform&c=dnstemplate> here  to add a dnstemplate. </url></p> 
$__emessage['certificate_key_file_empty'] = ""; // The certificate and the Key file you have chosen are empty. You have to first create or upload them before enabling ssl
