<?php
// $id: massagelib.php
// $version: Kloxo Dutch (NL) 6.1.X
// $translated by: Gerard van der Vegt
// $last update: 31 maart 2012

$__information['ndskshortcut_list__pre'] = "Het is mogelijk om in Kloxo favorieten toe te voegen door op de link [b] toevoegen aan favorieten [/b] te klikken die rechts bovenaan elke pagina staat. Elke snelkoppeling krijgt de parameter met de naam [b] volgorde-id [/b]. Na het toevoegen van de snelkoppeling kan er bij het [b] bewerken van favorieten [/b] de volgorde worden aangepast. Door op elke snelkoppeling een geschikt [b] volorde-id [/b] toe te passen, kunt u de lijst op elke gewenste manier ordenen. Ook de naam van de link kan aangepast worden naar een meer persoonlijk herkenbare naam. De werkelijke favorieten lijst op het linkerpaneel zal precies de volgorde weerspiegelen die hier zichtbaar is.";
// You can add a page in kloxo to the favorites, by clicking on the [b] add to favorites [/b] link on [b] that particular page. [/b] Each shortcut has a parameter called [b] Sort Id [/b]. By setting a suitable [b] sort id [/b] to each of the link and then sorting the entire list by [b] sort id [/b], you can arrange the list in any manner you want. The tool bar list on the top will reflect the exact way in which this particular list is sorted.
$__information['sshauthorizedkey_addform_lxlabs_pre'] = "Hiermee zal een LXlabs SSH sleutel worden toegevoegd aan je geautoriseerde sleutels, waarmee je LXlabs support personeel toe laat om zonder wachtwoord in te loggen op je server. Het is aangeraden om dit te doen wanneer je hebt aangegeven assistentie te willen van LXlabs"; 
// This will add lxlabs ssh key to your authorized keys, which will allow lxlabs support personnel to login to your server without password. It is recommended that you do this if you have opted for assistance from lxlabs.
$__information['rawlxguardhit_list__pre'] = "Dit is de lijst van ruwe verbindingen. Dit is handig om een ip-adres te traceren als een gebruikers account bekend is. Bijvoorbeeld; wanneer klanten proberen in te loggen op de server en dit te vaak wordt geprobeerd, dan worden ze geblokkeerd. Op deze pagina kan je [b]geavanceerd zoeken[/b] zodat er op [b]gebruikerslogin[/b] gezocht kan worden. Hiermee is het ip-adres van een klant makkelijk te vinden zodat deze verwijderd kan worden van de hoofd verbindingen pagina."; 
// This is the list of raw connections. This is primarily useful to trace an IP if you know the useraccount. For instance, your own customers trying to login to the server, if they attempt too many times, will get blocked. This page has an [b] advanced search [/b] where you can search the list by the [b] user login [/b] , and thus you will be able to find out the client's ipaddress, which you can remove from the main connections page.
$__information['login_pre'] = "<p> Welkom bij <%programname%>  </p><p>Gebruik een geldig gebruikersnaam en wachtwoord om toegang te krijgen tot de console. </p>"; 
// <p> Welcome to <%programname%>  </p><p>Use a valid username and password to gain access to the console. </p> 
$__information['tickethistory_addform__pre'] = "Om tekst te citeren kunt u &#91quote&#93 &#91/quote &#93 gebruiken. U kunt &#91code&#93 &#91/code&#93 gebruiken voor codefragmenten, en &#91b&#93 &#91/b&#93 voor vette tekst."; 
// You can use &#91quote&#93 &#91/quote &#93 to quote some text, which will shown properly formatted. You can also use &#91code&#93 &#91/code&#93 for code snippets, and &#91b&#93 &#91/b&#93 for bold.
$__information['lxguardwhitelist_addform__pre'] = "Het is aanbevolen dat u de knop [b] witte lijst [/b] bovenaan de <url:a=list&c=lxguardhitdisplay>verbindingen pagina</url> gebruikt om een ip-adres aan de witte lijst toe te voegen. Het handmatig invoeren van ip-adressen kan leiden tot spelfouten en verwarring. Doe een dubbele controle wanneer u hier een ip-adres invoert "; 
// It is recommended that you use the [b] whitelist [/b] button on top of the <url:a=list&c=lxguardhitdisplay>Connections Page</url>, to whitelist an Ipaddress. Manually entering the IP is bound to lead to spelling mistakes, and you will be left confused. If you are entering your IP here, please double check that it is correct.
$__information['sshconfig_updateform_update_pre'] = "Het is aanbevolen dat u volledig wachtwoord gebaseerde toegang tot deze server uitschakeld en in plaats daarvan de <url:goback=1&a=list&c=sshauthorizedkey>ssh sleutel verificatiebeheer</url> gebruikt om specifieke mensen toegang te geven zonder wachtwoord. Als dit hyperVM is en u van plan bent om VPS's te verkopen aan andere mensen, dan is het niet mogelijk om SSH wachtwoord toegang uit te schakelen. Dit is omdat vps-eigenaren moeten inloggen met het knooppunt om toegang te krijgen tot hun consoles. Zorg er in ieder geval voor dat wachtwoord gebaseerde toegang tot deze server uitschakeld is.<br> Dus als vaste regel op kloxo; schakel wachtwoord toegang tot alles uit, terwijl op hyperVM alleen wachtwoord toegang tot root wordt uitgeschakeld."; 
// It is recommended that you completely disable password based access to this server, and instead use the  <url:goback=1&a=list&c=sshauthorizedkey>ssh authorization key manager </url> to allow specific people to access without password. If this is hyperVM, and you are intending to sell VPSes to other people, you won't be able to completely disable ssh password access, since vps-owners will need to login the node to access their consoles. In any case, make sure you disable password based root access to this server. So as a rule of thumb, on kloxo, disable password access to everything, while on hyperVM, disable password access to root alone.
$__information['all_dns_list__pre'] = "Dit is de lijst van elke DNS aangemaakt door VP eigenaren. <url:o=general&a=updateform&sa=reversedns>Klik hier</url> om DNS servers te configureren zodat alle klanten hier gebruik van kunnen maken. Het DNS beheer van HyperVm staat toe dat een VPS eigenaar een DNS in HyperVm kan aanmaken. De data wordt opgeslagen op de VPS verkoper server. Met andere woorden; het is toegstaan om de VPS klanten DNS te hosten op uw servers";
// This is the list of every dns created by your VPS owners. <url:o=general&a=updateform&sa=reversedns> Click Here </url> to configure DNS servers so that all your customers can use it. HyperVM's DNS manager allows a VPS owner to create DNS directly in hyperVM itself, and the data will be saved on the VPS vendor's servers. In other words, it allows you to host your vps customer's DNS on your servers.
$__information['actionlog_list__pre'] = "Actie Rapporten registreren alle acties uitgevoerd op een account of VPS. Het belangrijkste dat moet worden opgemerkt is dat de reserve-id van de persoon die is ingelogd hier naar behoren is geregistreerd. Geef dus nooit de inloggegevens van het hoofd account aan iemand. In plaats daarvan maak een <url:a=list&c=auxiliary>reserve identiteit</url> voor elke lid van uw organisatie."; 
// Action log records all the actions executed on a client or a vps. The important thing you should note is that the auxiliary id of the person logged in is properly recorded here. So you should never give out the main account to anyone, instead create <url:a=list&c=auxiliary> auxiliary identities </url>for each of your staff.
$__information['sshauthorizedkey_list__pre'] = "[b]Let op[/b]: Het bestand ~/.ssh/authorized_keys2 is afgekeurd als openssh versie 3, dus wordt alleen het ~/.ssh/authorized_keys bestand beheerd. Dit zijn de ssh sleutels van de machines die op deze server kunnen inloggen zonder wachtwoord. Zorg ervoor dat u deze lijst kort houdt."; 
// Please note, the ~/.ssh/authorized_keys2 file has been deprecated as of openssh version 3, and so only the ~/.ssh/authorized_keys file is managed. These are the ssh keys from the machines which can login to this server without providing password. Make sure you keep this list trimmed.
$__information['updateform_forcedeletepserver_pre'] = "De server geforceerd verwijderen verwijderdt de server van de hyperVM database. Dit is nuttig als de server volledig is verwijderd en niet langer toegankelijk is."; 
// Force delete Server just removes the server from hyperVM's database. This is useful if the server has been completely removed is no longer accessible.
$__information['allowedip_addform__pre'] = "[b]Let op[/b]: Deze blokkering is alleen bedoeld voor het blokkeren van de toegang naar het controle paneel en zal dus niet de toegang blokkeren naar de bron. Een ip-adres kan in de vorm [b] 192.168.1.*[/b] worden ingevoerd om een bereik aan te geven. Dat wil zeggen dat in plaats van een nummer er een [b]*[/b] gebruikt kan worden voor het gehele bereik. Het is ook mogelijk om afzonderlijke ip-adressen in de vorm van 192.168.1.2 toe te voegen. Houd er rekening mee dat de decimale notatie noodzakelijk is en alle vier de velden ingevuld moeten worden. Wanneer iedereen wordt toegestaan verwijder dan alle toegestane ip-adressen of vul de velden in met [b]*. *. *. *[/b]. Andere ip-notaties worden op dit moment niet ondersteund."; 
// Please note: This is only meant for blocking access to the control panel, and will not block access to the actual resource. You can add an ip of the form [b] 192.168.1.*[/b]  denote a range. That is, instead of providing a number, you can use [b] * [/b]  to represent the entire range. You can also add individual ips of the form 192.168.1.2. Please note that the dotted notation is necessary, and you have to provide all the 4 fields. If you want to allow everyone, remove all the allowed ips, or provide [b] *.*.*.* [/b]. Other IP notations are not supported at this point.
$__information['blockedip_addform__pre'] = "[b]Let op[/b]: Deze blokkering is alleen bedoeld voor het blokkeren van de toegang naar het controle paneel en zal dus niet de toegang blokkeren naar de bron. Dit is de lijst van geblokkeerde ip-adressen. De ip-notatie is hetzelfde als dat van toegestane ip. Alleen als de toegestane ip-lijst leeg is zullen de geblokkeerde ip-adressen moeten worden toegevoegd. Als de toegestane ip-lijst niet leeg is dan worden automatisch alle ip-adressen die niet vermeld staan geweigerd."; 
// Please note: This is only meant for blocking access to the control panel, and will not block access to the actual resource. This is the list of blocked ipaddresses. The ip notation is the same as that of allowed ip. You should add blocked ips only if the allowed ip list is empty. If allowed ip list is non-empty then, automatically all ips not listed are denied.
$__information['updateform_portconfig_pre'] = "Deze pagina is voornamelijk bedoeld om de poorten van Kloxo/HyperVM configureren. Na het maken van veranderingen zal Kloxo/HyperVM opnieuw opgestart moeten worden om de wijzigingen door te voeren.<br> Voer deze opdracht uit [b]cd /usr/local/lxlabs/<%program%>/httpdocs; lphp.exe.../bin/common/misc/defaultport.php[/b] om de poorten in te stellen op de standaardwaarde. Vervolgen Kloxo/HyperVm opnieuw opstarten. Laat de velden leeg om terug te keren naar de standaard poorten."; 
// This page is primarily meant to configure the ports of Kloxo/HyperVM. After making the changes here, you will need to restart Kloxo/HyperVM service once for the changes to take effect. Run this command [b] cd /usr/local/lxlabs/<%program%>/httpdocs ; lphp.exe ../bin/common/misc/defaultport.php [/b] and the ports will be reset to the default. You can then restart Kloxo/HyperVM. Leave the fields blank to revert to default ports.
$__information['updateform_schedule_conf_pre'] = "[b]Let op[/b]: Alleen de geplande back-ups die beginnen met de naam <%program%>-scheduled- zullen worden gedraaid. Wanneer er een backup met eigen naam gemaakt wordt dan zal deze niet mee draaien. Gebruik bij het maken van een handmatige backup de eerste tekenreeks als [b] <%program%>-scheduled-[/b] om de backup mee te laten draaien."; 
// Please note that only the scheduled backups, that is, backups that start with the name <%program%>-scheduled-, will be rotated. If you create your own backup with your own name, they won't be rotated. So if you want a manually created backup to be rotated, provide the initial string as [b] <%program%>-scheduled- [/b]
$__information['updateform_ssl_kloxo_pre'] = "Hiermee word het ssl-certificaat voor <%program%> ingesteld als deze bepaald certificaat. Zorg ervoor dat u <%program%> opnieuw opstart nadat het hier ingesteld is."; 
// This will set the ssl certificate for <%program%> as this particular certificate. Make sure you restart <%program%> after you set it here.
$__information['updateform_ssl_authorized_keys_pre'] = "Dit zijn de SSH sleutels van de machines die op uw account mogen inloggen zonder wachtwoord te gebruiken. Er wordt &euml;&eumln sleutel per regel bewaard. Je kan de sleutels toewijzen aan de machines die zonder wachtwoord mogen inloggen. Ook moet je dit bestand kort houden om de kans op ongewenst inloggen te verminderen."; 
// These are the SSH keys from the machines which are authorized to login to your account without supplying the password. They are kept as 1 per line. You can add the keys to the machines you want to have password-less access to this machine. You should also keep this file trimmed so as to reduce the chances of unwanted people logging in
$__information['updateform_ssl_hypervm_pre'] = "Hiermee word het ssl-certificaat voor <%program%> ingesteld als deze bepaald certificaat. Zorg ervoor dat u <%program%> opnieuw opstart nadat het hier ingesteld is."; 
// This will set the ssl certificate for <%program%> as this particular certificate. Make sure you restart <%program%> after you set it here.
$__information['updateform_selfbackupconfig_pre'] = "Dit is voornamelijk bedoeld voor het configureren van de externe back-up van de master-database, en niets anders. De database dump dagelijks wordt genomen en wordt opgeslagen in een lokale map in deze machine. Als een FTP-account hier is geconfigureerd, zal het bestand worden geupload naar de machine. Dit is voornamelijk handig in grote clusterinstallatie waar het falen van meester veel grotere gevolgen kan hebben."; 
// This is primarily meant to configure the remote backup of the master database and nothing else. The database dump is taken everyday and is saved in a local folder in this machine. If an ftp account is configured here, the file will be uploaded to the machine. This is mainly useful in large cluster setup where the failure of master can have much larger impacts.
$__information['lxguard_updateform_update_pre'] = "LXguard zorgt voor bescherming tegen aanvallen van buitenaf door toezicht van de ssh en FTP logboek berichten en door ip-adressen te blokkeren die te veel mislukte inlog pogingen hebben gedaan op de server. LXguard staat standaard ingeschakeld en zal automatisch hosts blokkeren. LXguard kan niet worden uitgeschakeld. Door een drempel [b]van mislukte pogingen[/b] op te geven of door bepaalde ip-adressen aan de witte lijst toe te voegen kan LXguard worden geconfigureerd. Wanneer een IP-adres word gevonden in de witte lijst dan zal het niet worden geblokkeerd. Het ip-adres word dan niet geblokkeerd wanneer het de drempel vanmislukte pogingen heeft overschreden. Om de waarschuwingen niet meer te laten verschijnen verwijderen dient bij onderstaande overeenkomst de checkbox aangevinkt te worden."; 
// Lxguard protects you against brute force attacks by monitoring the ssh and ftp log messages, and blocking ipaddresses that have too many failed attempts at logging into the server. Lxguard is default turned on, and will automatically block hosts, and cannot be turned off. You can configure Lxguard by specifying the [b] threshold of failed attempts [/b] or by adding certain ipaddresses to the whitelist. If an IP is found in the whitelist, it won't be blocked, even if it has crossed the threshold of failed attempts. To remove the warnings you get about Lxguard please click on the agreement checkbox below
$__information['updateform_generalsetting_pre'] = "De 'HelpDesk URL' is een link naar uw Helpdesk die gebruikt word in plaats van de standaard helpdesk die is ingebouwd in de software. De 'gemeenschaps URL' is de link die de klant ziet aan de linker kant op zijn pagina en in normale gevallen kan verwijzen naar uw forum."; 
// The 'HelpDesk Url' is a link to your Helpdesk, which will be used in place of the default help desk built into the software. Community Url is the link the client will see on his left page, and in normal cases can point to your forum.
$__information['custombutton_addform__pre'] = "In de URL kan er %nname% gebruikt worden die dan zal worden vervangen door de naam van de klant. Alleen voor Kloxo kan er %default_domain% gebruikt worden voor het standaarddomein van de klant."; 
// In the url, you can use %nname%, which will be substituted with the name of the client. For Kloxo only, you can use %default_domain% for the default domain of the client.
$__information['updateform_download_config_pre'] = "Normaal gesproken wanneer er bestanden gedownload worden dan maakt de master een tijdelijke sessie aan en wordt de browser vervolgens rechtstreeks omgeleid naar de slave. Dit is om bandbreedte te besparen, omdat anders de bestanden onnodig via de master moeten gaan. Als u dit inschakelt zal hyperVM en meteen voor zorgen in plaats van dat het bestand via de maste gaat. Dit is handig als u prive ip-adressen heeft toegewezen aan de slaves en de slave niet toegankelijk zijn vanaf de buitenwereld."; 
// Normally, when downloading files, the master creates a temporary session, and then redirects the browser directly to the slave. This is to save the bandwidth, since otherwise, the files are pointlessly have to go through the master. If you enable this, hyperVM will instead route the file via the master itself. This is useful if you have given private ips for slaves, and the slaves are not accessible from the outside world.
$__information['updateform_login_options_pre'] = "[b]Let op[/b]: De time-out sessie kan niet minder zijn dan honderd. Wanner lager word ingesteld zal het automatisch ingesteld worden op honderd."; 
// Note: session timeout cannot be less than 100 and if less, will be automatically set to 100.
$__information['resourceplan_change_pre'] = "[b]Let op[/b]: Wanneer hier de waarden worden gewijzigt, dan zal elk account die dit pakket gebruikt worden bijgewerkt met de nieuwe waarden. Klik <url:a=updateForm&sa=account>hier</url> om te zien welke accounts aan dit pakket vast zitten."; 
// Note: If you change the values here, every account that uses this plan will be updated with the new values. Click <url:a=updateForm&sa=account>here to see the accounts configured on this plan</url>
$__information['lxbackup_updateform_backup_pre'] = "Het back-up bestand zal verschijnen in de __backup map van uw klant. Deze kunnen geopend worden door te klikken op het tabblad 'Bestands Beheer'. Om een back-up terug te plaatsen, dan moet deze eerst worden geupload naar de server met behulp van het tabblad [b]uploaden[/b]. Er kan direct,  http-url of een FTP-server geupload worden. Klik daarna op het pictogram van de [b]map[/b] rechts op het [b]herstellen van bestand[/b] kader en selecteer het bestand dat moet worden terug gezet. Klik vervolgens op [b]start restore process[/b]. Houd er rekening mee dat <%program%> back-up een hi&euml;rarchi is. Als er een back-up van een bepaalde bron word gemaakt, dan is alles dooaronder er automatisch bij inbegrepen. Dus als er een back-up van admin gemaakt wordt, dan hoeven er geen back-ups van klanten afzondelijk gemaakt te worden."; 
// The backup file will appear in the __backup directory of your client area. You can access it by clicking on the 'File Manager' Tab. To restore a backup, you can first upload it to the server using the [b] upload [/b] tab. You can upload directly or from an http url or an ftp server. Then come here, and click on [b] directory [/b] icon on the right in the [b] restore [/b] form, and it will allow you to select the particular file. Then click on [b] start restore process [/b]. Please note that <%program%> backup is heirarchical. If you take backup of a particular resource, everything under it is automatically included. Thus if you take backup of admin, then you need not take backups of clients under you separately.
$__information['phpini_updateform_edit_admin_pre'] = "Om Kloxo de php.ini volledig te laten beheren dan zal [b]PHP configuratie[/b] ingeschakeld moeten zijn. Houd er rekening mee dat uw oude php.ini wordt overschreven. Om de oude php.ini te herstellen schakel dan [b]PHP configuratie[/b] uit en doe een update. Het is aanbevolen om de configuratie volledig aan Kloxo over te laten. Wanneer er een speciale functie nodig is stel dan een vraag in het forum."; 
// You have to enable the [b] Manage Php Configuration [/b] flag to let Kloxo manage your php.ini completely. Please note that your old php.ini will be overwritten. To restore your old php.ini, just disable [b] Manage Php Configuration [/b] and update. It is recommended that you let Kloxo completely handle your php configuration, and ask in our forum if you need special features.
$__information['client_updateform_wall_pre'] = "[b]Let op[/b]: Het bericht zal alleen worden verzonden naar uw directe onderliggende klanten (&eacute;&eacute;n niveau, inclusief dit account), die een contact e-mail adres hebben ingesteld."; 
// Note: The Message will only be sent to your direct children (one level, including this account) who has a contact email set.
$__information['ffile_updateform_upload_pre'] = "Wanneer er meerdere bestanden/mappen tegelijk moeten worden geupload, maak er een zip bestand van en upload het zip bestand. In bestands beheer kan het bestand uitgepakt worden naar de desgewenste locatie."; 
// If you want to upload multiple files/directories, zip them up and upload; you can unzip the archives from inside the file manager.
$__information['dskshortcut_a_list__pre'] = "Om een pagina toe te voegen aan favorieten klik op de link [b] toevoegen aan favorieten [/b] die rechts bovenaan elke pagina staat. Elke snelkoppeling krijgt de parameter met de naam [b] volgorde-id [/b]. Na het toevoegen van de snelkoppeling kan er bij het [b] bewerken van favorieten [/b] de volgorde worden aangepast. Door op elke snelkoppeling een geschikt [b] volorde-id [/b] toe te passen, kunt u de lijst op elke gewenste manier ordenen. Ook de naam van de link kan aangepast worden naar een meer persoonlijk herkenbare naam. De werkelijke favorieten lijst op het linkerpaneel zal precies de volgorde weerspiegelen die hier zichtbaar is."; 
// To add a page to the favorites, click on the [b] add to favorites [/b] link that appears on the top right. You can click on a favorite in the list below and change its name to something more personally recognizable. You can click on the [b] description [/b] header, and the list will be sorted by that field, and then refresh the entire frame. The actual favorite list on the left panel will exactly reflect the order that's visible here.
$__information['ticketconfig_updateform_ticketconfig_pre'] = "De mailgate is een account waaruit <%program%> e-mails zal downloaden met een bepaalde interval en zal worden geparseerd en toegevoegd aan de helpdesk. Bij het verzenden van e-mails zal <%program%> het e-mail adres gebruiker dat hiervoor is ingesteld. Het e-mail adres is in de vorm [b]account@domain.com[/b]. De Server is de pop server waarvan de e-mail gedownload worden. [b]server.com[/b]. Wanneer het selectievakje [b]gebruik ssl[/b] is aangevonkt, dan zal de e-mail worden gedownload via pop3-ssl op poort 995. Het is altijd aanbevolen dat er van ssl gebruik wordt gemaakt. Er moet wel voor gezorgd worden dat de externe mail server pop3-ssl ondersteund op poort 995."; 
// The mailgate is an account from which <%program%> will download mails at particular intervals, and will be parsed and added to the helpdesk. When sending out mails, <%program%> will send the mails as originating from the address you configure. The address is of the form [b] account@domain.com [/b]. Server is the pop server from which to download the mails. [b] server.com [/b] . If you check the [b] use ssl [/b] box, then the mail will be downloaded over pop3-ssl, at port 995. It is always recommended that you use ssl, but you will need to make sure that the remote mail serer does support pop3-ssl service at port 995.
$__information['updateform_mysqlpasswordreset_pre'] = "Dit mag alleen worden gebruikt wanneer je het root-wachtwoord kwijt bent. Onder normale omstandigheden is het wachtwoord aan te passen door <url:a=list&c=dbadmin>hier</url> (database admin). Wees geduldig, want dit kan een tijdje duren voordat het is voltooid. Dit zal het mysql root-wachtwoord resetten door de skip-grant-tables uit te voeren. Wanneer dit niet werkt log dan in op ssh en voer de volgende commando in .../bin/common/misc/reset-MySQL-root-password.php"; 
// This should only be used if you have lost the root password. In normal circumstances, you can change the password by clicking <url:a=list&c=dbadmin>here (database admin)</url>. Please be patient as this will take a while to finish. This will reset the mysql root password by running it with the skip-grant-tables option. If this doesn't work, please login through ssh and run the ../bin/common/misc/reset-mysql-root-password.php
$__information['updateform_pserver_s_pre'] = "Dit is de Server groep voor deze doorverkoper. Hier wordt de lijst van servers getoond die de doorverkoper kan gebruiken bij het aanmaken van klant. Dat wil zeggen, dat de doorverkoper uit een lijst van toegewezen servers kan kiezen en een klant daar aan kan toewijzen."; 
// This is the Server Pool for this reseller. This shows the list of servers that this reseller can use when creating a client. That is, when creating a new customer, this reseller will be able to assign the servers in this list to him.
$__information['general_updateform_disableper_pre'] = "Dit is het gebruiks percentage waarop het account wordt uitgeschakeld. De normale waarde is 110%. Er komen waarschuwingen wanneer de quota 90,100 en 110% heeft bereikt."; 
// This is the percentage of usage at which the account will be disabled. The normal value is 110%. You will be given warnings when the quota reaches 90,100,110%.
$__information['updateform_ftp_conf_pre'] = "Wanneer [b]bewaar geen kopie[/b] is ingeschakeld, dan word het lokale bestand verwijderd. Dit kan gebruikt worden wanneer er ruimte bespaard moet worden op het account."; 
// If you enable [b] dont keep local copy [/b], the local file be deleted. You can use this if you want to save space in your account.
$__information['vv_updateform_skin_logo_pre'] = "Om te voorkomen dat ondeliggende account het logo kunnen aanpassen, schakel dan 'kan logo aanpassen' uit in de machtigings instellingen."; 
// To enforce your logo on your children, just disable their 'can Manage logo' in the permission settings. 
$__information['pserver_updateform_information_pre'] = "De FQDN is een zeer belangrijk veld en er moet een domein naam worden ingevoerd die voor de specifieke machine makkelijk op te lossen is. Na het instellen van de FQDN-naam zal hyperVM die waarde gebruiken voor alle verdere netwerk communicatie. Wanneer de FQDN hier four is ingesteld, dan zal de netwerk communicatie tussen master en slave mislukken. Laat het veld leeg om hyperVm het eerste ip-adres op de server te laten gebruiken voor communicatie. Stel de FQDN in op een hostnaam waarop deze machine vanaf overal te bereiken is."; 
// FQDN is a very important field and it should be set to a domain name that will properly resolve to this particular machine. Once you set the FQDN, hyperVM will use that value for all further network communication, and if the FQDN set here is wrong, then network communication between the master/slave would fail. If you leave it blank, hyperVM will use the first ipaddress on this server for communication. Set FQDN to a hostname using which you can access this machine from everywhere.
$__information['pserver_addform__pre'] = "Bij een versie installatie van een slave server is het wachtwoord admin. Het is sterk aanbevolen dat de servers worden toegevoegd met het invoeren van hun naam in plaats van hun ip-adres. De Server moet vanaf de master toegankelijk zijn met behulp van de specifieke naam die die hier is opgegeven; bijvoorbeeld server.domain.com. De uitgebreide beschrijving is een tekenreeks die kan worden gebruikt om deze server te beschrijven en is zichtbaar in chooser vakken."; 
// If you have freshly installed a slave server, the password is admin. It is strongly recommended that you add servers by their name rather than by their IP. The Server Should be accessible from the master using the particular name you supply here, for instance, server.domain.com. The verbose-identifier is a string that can be used to describe this server, and will be visible in chooser boxes.

// Modified for Kloxo 6.1.7
$__information['updateform_upload_logo_pre'] = "- Laat de velden leeg om het huidige logo te verwijderen. Standaard logo's zullen dan weer getoond worden.<br />".
											   "- Schakel 'kan logo aanpassen' uit in de permissies om te voorkomen dat onderliggende klanten het logo aanpassen.<br />".
											   "- Het uploaden van een logo (bv. links boven cp pagina) moet in PNG formaat met een hoogte van 75 pixels. De breedte kan zelf bepaald worden."; 
// - Leave the fields blank to reset the logos to default images.<br />".
//	"- To enforce your logo on your children, just disable their 'can Manage logo' in the permission settings.<br />".
//	"- Upload logo image (example: appear on top-left cp page) should be in PNG format with optimal height 75 pixels, while width is up to user's choice.

$__information['web_updateform_extra_tag_pre'] = "<b><font color=red> Waarschuwing!!!!! </font></b> Alles dat hiet wordt ingevoerd zal meteen worden toegevoegd aan de virtuele host. Als er een syntaxisfout in zit dan is het onmogelijk om de webserver opnieuw op te starten. Deze optie is alleen beschikbaar voor de admin gebruiker. Zorg ervoor dat na het opslaan de server draait."; 
// <b><font color=red> Warning!!!!! </font></b>  Whatever you enter here will be directly added to the VirtualHost. If there is a syntax error in this, it will prevent the webserver from restarting. This option is available only for the admin user. After Saving here, make sure that the server is running. 
$__information['addondomain_list__pre'] = "[b]Let op[/b]:<br> * Is er een geparkeerd domein met volledige DNS en e-mail beheer gewenst, maak dan een volledig domein aan die dezelfde bestands root heeft als de bestemming.<br> * Is er een domein met een omleiding en e-mail beheer gewenst, maak dan een volledig domein aan en leidt zijn [b] / [/b] om naar de bestemming van het domein."; 
// Note: <br>* If you want a parked domain with full DNS and mail management, create a full domain that has the same document root as the destination domain. <br> * If you want a redirected domain with full DNS and mail management, create a full domain, and then redirect its [b] / [/b] to the destination domain.
$__information['redirect_a_list__pre'] = "Het is hier toegestaan om een specifieke URL in het domein om te leiden naar een ander. Klik <url:a=updateform&sa=configure_misc>hier</url> om geforceerd een niet www gebaseerd http://dmein.nl naar http://www.domein.nl om te leiden."; 
// This will allow you to redirect a particular url in the domain to another. <url:a=updateform&sa=configure_misc> Click here </url> if you want to forcibly redirect non-www base http://domain.com to http://www.domain.com, 
$__information['web_updateform_dirindex_pre'] = "Met het inschakelen van [b]index bestanden[/b] is het mogelijk om vie de browser in de bestanden van je domein te bladeren. Is index bestanden uitgeschakeld en er is geen index.xxx gevonden in de map, dan word er een verboden toegang bericht getoond.";
// Enabling [b] directory index [/b] will allow you to browse the directories of your domain via the webserver. If directory index is disabled, and if an index.xxx file is not found inside the directory, a forbidden error message will be raised.
$__information['updateform_editmx_pre'] = "Klik <url:a=updateform&sa=remotelocalmail>hier</url> om de remote server te configureren. Kloxo kan de opdracht gegeven worden om de server remote te configureren. Wordt de remote e-mail niet geconfigureerd dan worden alle e-mails lokaal naar dit domein afgeleverd zonder naar een DNS te zoeken."; 
// If you want to configure remote mail server, <url:a=updateform&sa=remotelocalmail> Click here </url>. You can tell kloxo that the mail server is configured remotely, so that all local generated mails will be sent to that server. If you don't configure remote mail, then all mails to this domain will delivered locally itself, without doing any DNS lookup.
$__information['web_updateform_run_stats_pre'] = "Hier is het mogelijk om de statistieken programma's te laten draaien om de laatste statistieken te kunnen zien op de statistieken web pagina. Gebruik [b]alles updaten[/b] om de statistieken te laten draaien op alle domeinen die terug te vinden zijn in het scroll down menu bovenaan."; 
// This will allow you to forcibly run the stats program, so that you can see your latest statistics in the web statistics page. Use [b] update all [/b] to run it on all the domains visible in the top pull down menu.

$__information['server_alias_a_addform__pre'] = "- Er kunnen wildcards (*) als een schuilnaam toegevoegd worden zoadat alle subdomeinen automatisch worden doorgestuurd naar dit domein. ".
												"Kloxo voegt automatisch een DNS toe voor de schuilnaam.<br />".
												"- Zodra de catchall subdomein is geconfigureerd met wildcards (*), dan kan de juiste logica in het script toegevoegd worden om het correcte subdomein te detecteren en doen overeenkomen. < br / > ".
												"- Lighttpd kan worden verward met de geselecteerde wildcards (*). Toegang tot standaard (standaard, cp, uitschakelen en 'aanpassen') pagina's zullen leiden naar de domein pagina."; 
// - You can add wildcards (*) as an alias so that all the subdomains are automatically directed to this domain. ".
//	"Kloxo will also automatically add a DNS entry for the alias.<br />".
//	"- Once you configure the catchall subdomain with wildcards (*), you can add the proper logic in your script to detect the correct subdomain and do accordingly.<br />".
//	"- Lighttpd may be confused with selected wildcards (*). Access to defaults (default, cp, disable and 'customize') pages will be lead to the domain page

$__information['updateform_sesubmit_pre'] = "Het domein zal aan alle hieronder vermelde zoekmachines worden voorgelegd. Het e-mail adres zou een adres moeten zijn dat niet vaak wordt gebruikt, aangezien u zeer waarschijnlijk spam krijgt op de e-mail die u hier invoert"; 
// Your domain will be submitted to all the searchengines listed below. The email should be an address that's not used often, since you are very highly likely to get Spammed on the email you enter here
$__information['mmail_updateform_authentication_pre'] = "De primaire mx-server is automatisch opgenomen in het SPF en hoeft niet afzonderlijk toegevoegd te worden. Klik op [b]update all[/b] om deze waarden toe te passen op alle domeinen die bovenaan zichtbaar zijin in de scroll down lijst."; 
// Your primary mx server is automatically included in the SPF, and you need not add it separately. You can use [b] update all [/b] to impress these values on all the domains visible on the top pull down list.
$__information['updateform_preview_config_pre'] = "Domein voorvertoning is een master domein naar waar de website voorvertoning naar omgeleid wordt. Er zal handmatig een geparkeerd domein moeten worden toegevoegd met de naam domein.nl.voorvertoningdomein.nl naar dit domein en voeg daarna hier voorvertoningdomein.nl in. Dan zal de [b]dns loze voorvertoning[/b] worden omgeleid naar domein.nl.voorvertoningdomein.nl. Laat het veld leeg bij onzekerheid."; 
// Preview domain is a master domain, to which the site-preview button will be redirected to. You have to manually add a parked domain called domain.com.previewdomain.com to this domain, and then add the previewdomain.com here. Then the [b] dns less preview [/b] will be redirected to domain.com.previewdomain.com. If unsure, please leave this blank.
$__information['updateform_stats_protect_pre'] = "Statistieken pagina bescherming is het wachtwoord dat wordt gebruikt om de statistieken pagina voor een domein te beschermen. Wanneer nul is ingevuld dan wordt de bescherming uitgeschakeld en word de statistieken pagina direct beschikbaar."; 
// Stats page protection is the password that's used to protect the statistics page for your domain. If set to to null password, protection will be disabled, and you will be able to access the stats directly.
$__information['updateform_installatron_pre'] = "Er moet uitgelogd worden van de huidige gebruiker. Log nu dan specifiek in als deze gebruiker om Installatron te grbruiiken voor dit account. login als deze gebruiker te gebruiken Installatron voor deze specifieke account. Installatron is alleen beschikbaar bij aanwezigheid van een account die rechtstreeks is ingelogd."; 
// You have to logout of your current user, and then specifically login as this user to use Installatron for this particular account. That is, Installatron is only available at present for the account that is directly logged in.
$__information['ftpuser_admin'] = "Gebruik [b]--direct--[/b] om een ftp gebruiker zonder domein toe te voegen."; 
// Use [b] --direct-- [/b] to add an ftpuser that does not contain domain name.
$__information['updateform_default_domain_pre'] = "Hier wordt het domein dat beschouwd wordt als het primaire domein ingesteld voor dit specifieke account. Ga naar http://IP/~clientname om toegang te krijgen naar de root map van het domein. Klik <url: a=list&c=ipaddress>hier</url> om een ip-adres toe te wijzen aan een domein. Klik op een ip-adres en dan op het tabblad 'configureer domein'. Om een domein te bekijken voordat de dns is ingesteld kan er het beste een betand gemaakt worden in de lokele etc/hosts map. Het pad voor het bestand in windows is c:/windows/system32/drivers/enz/hosts. Voeg gewoon een vermelding als volgt in: [b]192.168.1.32 domein.com[/b] op een aparte regel. Nu is het mogelijk om toegang te krijgen tot het domein door het op je browser in te tikken."; 
// This will set the domain that's considered as the primary domain for this particular account. You can access this domain's document root by going to http://IP/~clientname. To map an ipaddress to a domain, you have to <url: a=list&c=ipaddress> click here </url>, go inside an ipaddress and click on 'configure domain' tab there. If you want to view a domain before the dns is setup, the best way is to create an entry for the domain in your local etc/hosts file. The path for the file on windows is c:/windows/system32/drivers/etc/hosts . Just add an entry like this: [b] 192.168.1.32 domain.com [/b] on a separete line, and then you will be able to access the domain by typing it in your browser's url box.
$__information['updateform_blockip_pre'] = "Voeg &eacute;&eacute;n ip-adres per regel toe. Gebruik voor het toevoegen van een ip-adres met een bepaald bereik de .*.* notatie. <br />[b]Let op[/b]: Andere ip-notaties worden op dit moment niet ondersteund. De standaard IP-notatie wordt niet ondersteund."; 
// Add one IP per line. If you want to add an IP range use the .*.* notation. For instance, 192.168.*.*. Please note, this is the only notation supported for ip ranges. The standard ip notation is not supported.
$__information['web_updateform_statsconfig_pre'] = "Elke dag wanneer het logboekbestand groter is dan 50 MB dam worden ze verplaatst naar de  home map van de klant. Wanneer de remove_processed_logs als waar ingestelt dan worden ze verwijderd in plaats van verplaatst. De hoofd statistieken berekening wordt hier niet mee be&iuml;nvloed."; 
// Every day, if the log file's size is larger than 50MB, they are moved into the client's home directory. If you set the remove_processed_logs as true, then instead of moving, they will be deleted. Your main statistics calculation will not be affected at all.
$__information['web_updateform_hotlink_protection_pre'] = "Het domein en subdomeinen zullen automatisch toegang hebben tot de afbeeldingen en hoeven niet specifiek te worden toegevoegd. een *. domein.nl wordt automatisch toegevoegd aan de lijst van toegestane domeinen die hier wordt opgegeven. De [b]omleiding naar afbeelding[/b] moet een pad naar de afbeelding zijn binnen het domein en niet een volledige url. Bijvoorbeeld zoiets als (/ img/noaccess.gif). Voer domeinen in zonder aparte karakter. Bijvoorbeeld, domein.nl, mijndomein.nl of jouwdomein.nl"; 
// Your domain and subdomains will automatically have access to the images, and you don't have to add them specifically. a *.domain.com is automatically added to the list of allowed domains you supply here. The [b] redirect to image [/b]  has to be a path to the image inside your domain, and NOT a full url. It should be of the form (/img/noaccess.gif). You have to enter domains as simple names without any wild-characters. For example, domain.com, mydomain.com, mysdomain.com
$__information['mailqueue_list__pre'] = "Het kost wat tijd voordat de wachtrij werkelijk verdwijnd. Dus na het verwijderen zullen de e-mails wat langer in de wachtrij staan. Ververs de pagina na ongeveer een minuut om te verifi&eumlren of de e-mails werkelijk zijn verwijderd of niet."; 
// It will take a little bit more time for the queue to actually disappear. So after clicking on delete, the mails will appear in the queue for some more time. Just refresh the page after around a minute to verify if the mails are actually deleted or not.
$__information['mailqueue_updateform_update_pre'] = "Om het rapport van de e-mail te zien ga dan terug naar de lijst en leeg de e-mailrij, aangezien alleen het logboek voor het afgelopen uur wordt geparseerd."; 
// To see the log for the mail, please go back to the listing, and flush the mailqueue once, since only the log for the past hour is parsed.
$__information['rubyrails_addform__pre'] = "De applicatie zou normaal toegankelijk zijn op http://domain.com/applicationname. Het pad zou /home/client/ror/domain.com/applicationname zijn. Wanneer er opgegeven word dat de [b]direct toegankelijk[/b] vlag, dan zou de applicatie toegankelijk moeten zijn op http://domain.com zelf."; 
// The application would be normally accessible at http://domain.com/applicationname. The path would be /home/client/ror/domain.com/applicationname. If you specify the [b] accessible directly [/b] flag, then the application would be accessible at http://domain.com itself.
$__information['installapp_addform__pre'] = "Om een applicatie in de root map te installeren laat dan de [b] locatie[/b] leeg. Om dezelfde applicatie voor een ander domein te installeren gebruik dan het scrolldown bovenaan en verander van domein. Nu is het moegelijk om voor het gekozen domein de applicatie te installeren.Na installatie zal er een e-mail verzonden worden met de hier opgegeven gegevens."; 
// To install an application in the document root, please leave the [b] Location [/b] blank. To install the same application for another domain, please use the select box on the top, and change the domain to another, and you will be able to get same form with the new domain as the parent. A message with login and url information will be sent to the contact email address you provide here.
$__information['mysqldb_updateform_restore_pre'] = "Dit is alleen te om backups te herstellen die uitsluitend in Kloxo zelf via het tabblad [b]maak back-up[/b] zijn aangemaakt. Gebruik phpMyAdmin om de normale mysql dumpbestand te herstellen."; 
// You can use this only to restore the backups that were explicitly taken in Kloxo itself using the [b] Get Backup [/b] tab. To restore normal mysql dump file, please use phpMyAdmin.
$__information['domainipaddress_updateform_update_pre'] = "Dit laat toe om een specifiek ip-adres toe te wijzen aan een domein. Dat wil zeggen, dat wanneer iemand http://ip benaderd dan word de document root van het geconfigureerde domein hier getoond."; 
// This will allow you to map a particular ipaddress to a domain. That is, if someone accesses http://ip, then the document root of the domain configured here will be shown.
$__information['updateform_search_engine_pre'] = "Sommige engines hebben een e-mail adres nodig ter bevestiging. Voer hier geen hoofd e-mailadres in vanwege het ontvangen van spamberichten. Voor een betere ranking herhaal de handeling om de 3 of 4 weken. Wanneer dit te vaak gedaan word dan kan er een verbod op gegeven worden."; 
// Some engines may require your e-mail confirmation for submission. Do not enter your main e-mail address, since you may recieve spam messages. For a better ranking repeat the operation every 3-4 weeks but not sooner, since you may get banned
$__information['updateform_domainpserver_pre'] = "Dit zijn de servers waarop de domeinen onder deze klant worden geconfigureerd. Wanneer hier de waarden worden aangepast, dan worden automatisch alle domeinen verplaatst naar de juiste servers. Dat wil zeggen wanneer de [b]e-mailserver[/b] en update worden aangepast, dan worden [b]alle[/b] e-mail accounts op het domeinen onder deze klant gemigreerd van de oude server naar de nieuwe server. Het [b]DNS sjabloon[/b] is het nieuwe DNS sjabloon waarnaar alle domeinen worden overgeschakeld. Zorg er dus eerst voor om een DNS sjabloon te maken die overeen komt met de nieuwe configuratie en die dan aan kloxo te verstrekken. Zie onderaan voor hulp over het verplaatsen op een server. Later kan er in het DNS beheer wijzigen worden gemaakt onder de tab opnieuw opbouwen door op [b]update all[/b] te klikken. Dit heeft invloed op de alle domeinen in het account met deze nieuwe DNS sjabloon."; 
// These are the servers on which the domains under this client will be configured on. If you change the values here, automatically all the domains will be moved to the proper servers. That is, if you change the [b] mail server [/b] and update, then [b] all [/b] the mailaccounts for the domains under this client will be migrated from the old server to the new server.  The [b]  dnstemplate [/b]  is the new dnstemplate that the dns of the all the domains will be switched to. So you have to make sure that you first create a dnstemplate that reflects the new configuration, then provide that to kloxo here. See bottom for more help on server move. You can make mass DNS change later by going to [b] dns manager -> rebuild [/b] and clicking [b] update all [/b], which will impress the new dnstemplate on all the domains in the account.
$__information['sslipaddress_updateform_update_pre'] = "Klik <url:goback=2&a=list&c=sslcert>hier</url> voor het uploaden van een SSL certificaat om deze vervolgens in te stellen voor een ip-adres."; 
// To setup an ssl for an ipaddress, first upload/add an ssl certificate from <url:goback=2&a=list&c=sslcert> here </url>
$__information['domain_addform__pre_docroot'] = "Wanneer de document root leeggelaten wordt, dan zal Kloxo automatisch mydomain.com als docroot gebruiken."; 
// Leave the document root blank and Kloxo will automatically use mydomain.com as the docroot.
$__information['sslcert_updateform_update_pre_admin'] = "Klik <url:goback=1&l[class]=pserver&l[nname]=localhost&a=list&c=ipaddress>hier</url> om dit certificaat aan een bepaald ip-adres toe te wijzen. Ga vervolgens naar een ip-adres en klik op het [b]ssl certificaat[/b] tabblad om &euml;&eumln van deze ssl certificaten in te stellen voor een specifiek ip-adres."; 
// To assign this ssl certificate to a particular ipaddress, <url:goback=1&l[class]=pserver&l[nname]=localhost&a=list&c=ipaddress> click here</url> and then go into an ipaddress, and click on [b] ssl certificate [/b] tab, and you can set one of these certificates to a particular ipaddress.
$__information['sslcert_updateform_update_pre'] = "Klik <url:goback=2&a=list&c=ipaddress>hier</url> om dit certificaat aan een bepaald ip-adres toe te wijzen. Ga vervolgens naar een ip-adres en klik op het [b]ssl certificaat[/b] tabblad om &eacute;&eacute;n van deze ssl certificaten in te stellen voor een specifiek IP-adres. De administratie moet wel een exclusiev ip-adres hebben toegewezen voordat er toegang is tot deze functie."; 
// To assign this ssl certificate to a particular ipaddress, <url:goback=2&a=list&c=ipaddress> click here</url> and then go into an ipaddress, and click on [b] ssl certificate [/b] tab, and you can set one of these certificates to a particular ipaddress. The admin will need to have assigned you an exclusive ipaddress for you to access this feature.
$__information['domain_not_customer'] = "Maak eerst een klant aan om een domein toe te voegen, zodat deze onder de klant geplaatst kan worden. Klik <url:a=addform&c=client&dta[var]=cttype&dta[val]=customer>hier</url> voor het toevoegen van een klant."; 
// To add a domain, create a customer first, and you can add domains under him. To add a customer, <url:a=addform&c=client&dta[var]=cttype&dta[val]=customer>click here </url>
$__information['ipaddress_list__pre'] = "Een exclusief ip laat toe om bepaalde controle over een specifiek ip-adres te hebben. Dit is handig voor het instellen van SSL en ook voor het instellen van een ip voor een domein. Dat wil zeggen, wanneer er een bepaalde ip te koppelen aan een domein. Voor het hebben van een exclusief ip-adres, zal de administratie aan het ip-adres een exclusieve klant moeten instellen. Om een ssl of een domein aan een ip te koppelen klik dan op een ip-adres en klik dan op het tabblad [b]ssl configuratie[/b] of [b]configureer domein[/b]."; 
// Exclusive IP will allow you to have dedicated control of a particular ipaddress. This is useful for setting up SSL and also for setting up an ip for a domain. That is, if you want a particular IP to resolve to a domain. For you to have an exclusive IPaddress, the administrator will have to set the exclusive client of a particular ipaddress. To setup ssl or to map an IP to a domain, click on an IPaddress, and then click on [b] configure ssl [/b] or [b] configure domain [/b]
$__information['clientmail_list__pre'] = "Dit zal een lijst laten zien van de verstuurd e-mails van klanten die via de webserver of de smtp auth relay over de laatst twee dagen. Bij een volledig e-mail account zoals [b]gebruiker@domein.com[/b], dan wordt de mail verzonden via relay. Als het een eenvoudige gebruikersnaam, dan wordt de mail verzonden via de webserver. Wanneer mod_php op apache word gebruikt dan worden alle webapplicaties alleen uitgevoerd als gebruiker [b]apache[/b]. Er wordt dan ook alleen een list getoond van [b]apache[/b] gebruiker. Gebruik SuPHP op apache wanneer er gehost gaat worden voor derden. Op deze manier kan elke klant ge&iuml;dentificeerd worden met behulp van zijn systeem gebruiker."; 
// This will list the number of mails sent out by your clients via the webserver or smtp auth relay in the last 2 days. If it is a full mailaccount like [b] user@domain.com [/b], then it represents mail sent via relay. If it is a simple username, then it represents mail sent via a form in the web server. If you use mod_php on apache, then all webapplications are run as user [b] apache [/b] , and only [b] apache [/b] will be displayed here. Use suPHP on apache, if you are planning on hosting for third parties. That way you will be able to identify each client using his system user.
$__information['servermail_updateform_update_pre'] = "Het is van essentieel belang dat het instellen van mijn naam een goed omzetbare host naam is, omdat anders vele openbare mailservers zoals hotmail de e-mails zal verwerpen van de server. Er kan een extra poort voor de e-mailserver opgegeven worden door dat hier te specificeren. Laat het veld leeg om extra smtp uit te schakelen. De max smtp exemplaren specificeren het maximaal aantal SMTP-processen aan die zijn toegestaan. Er moet een waarde opgegeven worden, bijvoorbeeld 10 wannner er zware spam aanvallen zijn. Wanneerr dit veld word leeg gelaten dan word de waarde ingesteld op onbeperkt. Dit is ook de standaard waarde.";
//It is very essential that you set the my name to a properly resolvable hostname, since otherwise, many public mailservers like hotmail will reject mails from your server. You can have the mail server running on additional port by specifying it here. Leave it blank to to disable additional smtp. The max smtp instances specifies the maximum number of smtp processes that are allowed. You should set it to some number, say 10, if you are getting spammed heavily. If you leave it blank, it will be set to UNLIMITED, which is the default.
$__information['updateform_switchprogram_pre'] = "Van programma wisselen kost tijd omdat de oude programma's eerste verwijderd moeten worden en de nieuwe programma's vervolgens met yum worden ge&iuml;nstalleerrd. Het rapport hiervoor zullen beschikbaar zijn in de shell_exec bestand. Alle informatie wordt op transparante wijze gemigreerd. Het duurt een minuut voordat de nieuwe service naar behoren is opgestart."; 
// Switching Programs will take a while, since it needs to remove the old program from the system, and install the new one using yum. The log for this will be availabe in the shell_exec file. All your information will be transparently migrated. You will need to wait one minute before the new service properly restarts.
$__information['updateform_permalink_pre'] = "Kloxo wordt standaard geleverd met permalink configuratie voor veel applicaties. Selecteer de applicatie en de map waar u het hebt ge&iuml;nstalleerd. Kloxo zal dan de overeenkomstige herschrijfregel toevoegen in de lighty configuratie. Houd er rekening mee dat sommige applicaties permalinks worden gearchiveerd via het instellen van de 404 error handler, bijvoorbeeld wordpress."; 
// Kloxo comes with default permalink configuration for many apps. Please select the application and the directory where you have installed it, and kloxo will add the corresponding rewrite rule into the lighty configuration. Please note that for some applications, permalinks are achieved via setting the 404 error handler, for instance wordpress.
$__information['weblastvisit_list__pre'] = "Dit is een lijst van de laatste vijftig bezoekers of in de laatste twintig uur. De re&euml;le tijd vertegenwoordigt in unix time stamp en er is zodat er nauwkeurig op tijd gesorteerd kan worden. De langere tekenreeksen worden afgekapt om in het scherm te kunnen passen. Beweeg met de muis over de tekenreeksen om de voledige te kunnen zien."; 
// This is the list of last 50 visitors or the number of visitors in the last 20 hours, whichever is smaller. Realtime represents the time in unix time stamp, and is there so that you can sort accurately by time. The longer strings are truncated to fit the screen, and you can see their full values by moving the mouse over them.
$__information['subweb_a_addform__pre'] = "Dit is een eenvoudig subdomein. Een eenvoudig subdomein heeft alleen een web component waarvoor geen e-mail of dns beheerd kan worden. Voor een volledig subdomein gebruik dan de [b]subdomein[/b] knop op de domein hoofd pagina. Het pad naar envoudige subdomeinen is /home/clientname/domain/domain.com/subdomains/subdomainname"; 
// This is a simple subdomain. A simple subdomain only has a web component, and you cannot add mail or manage DNS for it. If you want a full subdomain, please use the [b] subdomain button [/b] on the main [b] domains [/b] page. The simple subdomain's path is /home/clientname/domain/domain.com/subdomains/subdomainname
$__information['updateform_skeleton_pre'] = "Dit is het archief van de skeleton map die naar de home map van het domein zal worden gekopieerd wanneer deze wordt aangemaakt. Het archief zal uitgepakt worden in de home map van het zojuist aangemaakte domein. Om de variabelen te vervangen met de juiste waarden kan er [b] &lt;%domainname%&gt; , &lt;%clientname%&gt;[/b]gebruikt worden in het index.html bestand ."; 
// This is the archive of the skeleton directory which will be copied to your domain home directory when it is created. The archive will be unzipped into a newly created domain's home directory. You can use [b] &lt;%domainname%&gt; , &lt;%clientname%&gt; [/b]  inside the index.html file, and the variables will be replaced properly with the correct values.
$__information['updateform_lighty_rewrite_pre'] = "Dit is de aangepaste lighttpd rewrite rule dat direct word toegevoegd aan het configuratie bestand zonder enige verandering. Het zal er als volgt uitzien [b]url.rewrite = (... [/b]."; 
// This is the custom lighttpd rewrite rule that will directly appended to the configuration file without any change. It will be of the form [b] url.rewrite = ( ... [/b].
$__information['updateform_custom_error_pre'] = "<p>[b]Let op[/b]: De waarden die opgegeven moeten worden zijn de virtuele paden naar de bestanden die worden getoond in het geval van deze fouten. Bijvoorbeeld: /error_files/404.html.</p>"; 
// <p> Note: The values you have to provide are the virtual paths to the files that will be shown in case of these errors. Example: /error_files/404.html.</p>
$__information['domain_updateform_ipaddress_pre'] = "<p>[b]Let op[/b]: Zorg ervoor dat de nodige wijzigingen ook zijn aangebracht in de nameserver configuratie."; 
// <p> Note: Make sure that you make the requisite changes to nameserver configuration too.  </p>
$__information['client_updateform_ipaddress_pre'] = "<p>[b]Let op[/b]: De beschikbare ip-adresgroep is geselecteerd van de machine in de web server-groep.</p>"; 
// <p> Note: The available ip pool is selected from the machines in the web server pool. </p>
$__information['domaintemplate_addform__pre'] = "<p>[b]Let op[/b]: Aan de rechterkant staan de maximale waarden van de huidige quotum limiet. Het is mogelijk om een sjabloon te maken die de waarde overschrijden, maar deze is dan niet te gebruiken bij het aan maken van klanten of domeinen.</p>"; 
// <p> Note: The Max Value on the right shows your current quota limit. You can create a Template with values more than your quota, but you won't be able to use them to create Domains/Clients. </p>
$__information['spam_updateform_update_pre'] = "<p>De 'score' (van 1 tot 10) is de waarde die op een mail wordt gemarkeerd als SPAM. Wanneer de waarde lager wordt ingesteld, dan wordt meer mail gemarkeerd als spam. Een te lage waarde kan leiden dat echte e-mails worden geclassificeerd als spam. Een te hoge waarde kan leiden dat er een te hoge hoeveelheid spam door het filter komt.</p>"; 
// <p> The 'score'--which can be 1-10--is the value at which a mail is marked as SPAM. So if you set it to lower values, more mail will be marked as spam. Too low values might lead to genuine mails getting classified as spam. Too high values will lead to high amount of spam getting through the filter. </p>
$__information['web_updateform_enable_frontpage_flag_pre'] = "<p>Het frontpage wachtwoord is het zelfde als die van de systeemgebruiker (hoofd FTP gebruiker).</p>"; 
// <p> The frontpage password will be the same as that of the system user (main ftp user).  </p>
$__information['ffile_show___lx_error_log_pre'] = "Dit is het fouten rapport voor een domein. De inhoud van dit rapport kan gebruikt worden om problemen te vinden die zich voor doen op een domein."; 
// This is the error log for your domain. The contents of this will help you trouble shoot if you are having any problems regarding the domain.
$__information['installappsnapshot_list__pre'] = "<p>Een moment opnamen is een exacte kopie van de database en de bestanden van een applicatie op een bepaald moment. Het is mogelijk om een bepaalde moment opname terug te zetten door te klikken op de knop [b]herstellen[/b].</p>"; 
// Snapshots are the exact copy of the database and the files of your application at a particular time. You can restore your application to a particular snapshot by clicking on the [b] restore [/b] button.
$__information['sshclient_updateform_disabled_pre'] = "De administratie heeft geen shell toegang ingeschakeld. Wanneer shell toegang vereist is neem dan contact op met het beginnen van een ticket."; 
// Your admin hasn't enabled shell access for you. Please open a support ticket if you need ssh access.
$__information['sshclient_updateform_warning_pre'] = "Houd er rekening mee dat alle activiteit wordt vastgelegd en elke poging tot verboden bestanden kan leiden tot een be&euml;indiging van een hosting account. Dus werk op een verantwoordelijke manier."; 
// Please note that all your activity is logged and any attempt at accessing files not belonging to you will lead to termination of your hosting account. So please act responsibly.
$__information['ffile_show___lx_access_log_pre'] = "Dit is het toegangs rapport voor het domein. Dit is te downloaden door aa de rechterkant op het tabblad [b]downloaden[/b] te klikken. Dit bestand bevat informatie over elke hit die is gemaakt op de website"; 
// This is the access log for your domain. You can download this by clicking on the [b] download [/b] tab at the right. This file contains information about every single hit that is made to to your website
$__information['updateform_disable_url_pre'] = "Alle onderliggende accounts erven automatisch de url bij uitschakeling parameters. Bij de permissie instellingen kaningesteld worden dat klanten 'url bij uitschakeling' niet kunnen gebruiken. Dit is de url waarnaar een domein wordt doorgestuurd wanneer deze is uitgeschakeld."; 
// All your children will automatically inherit your Disable url parameters. To enforce your Disable Url on them, just disable their 'can Set Disable Url' in the permission settings. This is the url to which a domain will be redirected to when it is disabled.
$__information['updateform_dnstemplatelist_pre'] = "Wijs slechts &eacute;&eacute;n enkel dns-sjabloon toe aan een klant. Dit betekent dat kloxo niet het vak dns-sjablonen selecteren toont tijdens het toevoegen van een domein, waardoor het minder verwarrend is voor een klant."; 
// Allocate only a single dns template to your customer. This would mean that kloxo will not show the dns template select box while adding a domain, which will make it less confusing to your customer.
$__information['forward_a_addform__pre'] = "De doorstuur adressen is een lijst van e-mail adressen waarnaar de e-mail wordt gestuurd. Er word ook een kopie ogeslagen op het werkelijke e-account. Schakel lokale opslag uit door <url:a=updateform&sa=configuration>hier</url> te klikken."; 
// The forward addresses are a list of email addresses to which the mail is forwarded to. One copy of the mail gets saved to the actual mailaccount too. You can disable local storage by <url:a=updateform&sa=configuration>clicking here </url>.

// Added Kloxo version 6.1.6 TODO !! Give proper information.
$__information['vv_dns_srv_message'] = "Hier kan je het SRV register beheren."; 
// Here you can manage the SRV record.
$__information['vv_dns_ddns_message'] = "Hier kan je de DDNS beheren."; 
// Here you can manage DDNS.
$__information['vv_dns_mx_message'] = "Hier kan je het MX register beheren. Vul '__base__' in voor het krijgen van het basis domein."; 
// Here you can manage the MX record. Enter '__base__', if you want to get the base domain.
$__information['vv_dns_ns_message'] = "Hier kan je het NS register beheren."; 
// Here you can manage the NS record.
$__information['vv_dns_aaaa_message'] = "Hier kan je het IPv6 register beheren. Vul '__base__' in voor het krijgen van het basis domein."; 
// Here you can manage the IPv6 record. Enter '__base__', if you want to get the base domain.
$__information['vv_dns_txt_message'] = "Gebruik &lt;%domain&gt; als je het domein naam in een TXT register wil hebben. Bijvoorbeeld, 'v=spf1 include: &lt;%domain &gt;'."; 
// Use &lt;%domain&gt; if you want the domain name inside a TXT record. For instance, 'v=spf1 include: &lt;%domain &gt;'.
$__information['vv_dns_cname_message'] = "Hier kan je het CNAME register beheren."; 
// Here you can manage the CNAME record.
$__information['vv_dns_fcname_message'] = "Hier kan je het FCNAME register beheren. [b]FCNAME[/b] staat voor volledige CNAME- en zal toestaan een subdomein door te verwijzen naar een extern domein."; 
// Here you can manage the FCNAME record. [b]FCNAME[/b] stands for full cname and will allow you to point a subdomain to an external domain.
$__information['vv_dns_a_message'] = "Hier kan je het A register beheren. Vul '__base__' in voor het krijgen van het basis domein."; 
// Here you can manage the A record. Enter '__base__', if you want to get the base domain.
$__information['vv_dns_soa_message'] = "Hier kan je het SOA register beheren."; 
// Here you can manage the SOA record.
$__information['vv_dns_rebuild_message'] = "Hier kan je een domein herbouwen vanaf een DNS sjabloon."; 
// Here you can rebuild your domain zone from a DNS Template.

// Added Kloxo 6.1.7
$__information['vv_dns_template_message'] = "[b]Primaire en Secundaire DNS[/b]<br />Host namen zijn toegestaan."; 
// [b]Primary and Secondary DNS[/b]<br />Only Hostnames are allowed

// Changed Kloxo Version 6.1.6
$__information['vv_dns_blank_message'] = "<p>DNS Beheer</p>"; 
// <p>DNS Manager</p>

$__emessage['blocked'] = "Uw adres is geblokkeerd."; 
// Your address is blocked
$__emessage['no_server'] = "Kan geen verbinding maken met de Server."; 
// Could not connect to the Server.
$__emessage['set_emailid'] = "Stel uw E-mail ID correct in "; 
// Please Set Your EmailId Properly
$__emessage['no_socket_connect_to_server'] = "Kan geen verbinding maken met de server [%s]. Dit is hoogst waarschijnlijk te wijten aan onderliggende netwerk probleem. Zorg ervoor dat de server toegankelijk is vanaf dit bepaalde knooppunt door [b] telnet slave-id 7779 [/b] te laten draaien.";
//Could not Connect to the server [%s]. This is most likely due to underlying network problem. Make sure that the server is accessible from this particular node by running [b] telnet slave-id 7779 [/b]
$__emessage['restarting_backend'] = "De backend word opnieuw opgestart. Probeer over 30 seconden nog een keer."; 
// Restarting the backend. Please try again after 30 seconds.
$__emessage['quota_exceeded'] = "Quotum overschreden voor [%s]"; 
// Quota Exceeded for [%s]
$__emessage['license_no_ipaddress'] = "Het openbare ip-adres [%s] van deze server is niet gevonden in de licentie repository. Neem contact op met Lxlabs verkoop of de verkoper om een licentie te maken voor deze server. "; 
// The public ipaddress [%s] of this server was not found in in the license repository. Please contact Lxlabs sales or your reseller to create a license for this server. </a>
$__emessage['ssh_root_password_access'] = "U heeft de wachtwoord gebaseerde toegang tot root op deze server niet uitgeschakeld. Wachtwoord gebaseerd toegang tot de root is niet nodig aangezien u ssh gemachtigd sleutels via uw hypervm zelf kan beheren. Klik <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=sshconfig>hier</url> voor het configureren van uw ssh server."; 
// You have not disabled password based access to root on this server. Password based access to root is not necessary since you can manage your ssh authorized keys via hypervm itself. <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=sshconfig> Click here </url> to configure your ssh server.
$__emessage['already_exists'] = "De bron van naam [%s] bestaat al."; 
// The resource of name [%s] already exists.
$__emessage['lxguard_not_configured'] = "Lxguard voor deze server is niet geconfigureerd. Klik <url:k[class]=pserver&k[nname]=localhost&a=show&o=lxguard>hier</url> om LXguard te configureren. Het is belangrijk dat er begrepen wordt wat het doet. Lxguard is van cruciaal belang voor de beveiliging van de server. Het kan op hetzelfde moment ook een eigen IP-adres blokkeren zodat er geen toegang tot de server verkregen kan worden. Dit kan zeer frustrerend zijn wanneer niet bekend is wat er gebeurt."; 
// Lxguard for this server is not configured. Please <url:k[class]=pserver&k[nname]=localhost&a=show&o=lxguard>Click here to configure Lxguard </url> since it is very important that you understand what it does. Lxguard is critical for the security of your server, at the same time, it can block your own IPaddress from accessing the server, which can be frustrating if you don't know what's happening.
$__emessage['root_cannot_extract_to_existing_dir'] = "De naam van de opgegeven locatie bestaat al. De root gebruiker kan geen bestand uitpakken naar een bestaande map. Geef de naam op van een map die niet in het systeem bestaat."; 
// Directory you provided already exists. Root user cannot extract archive into an existing directory. Please provide the name of a directory that doesn't exist in the system.
$__emessage['no_imagemagick'] = "Er is geen imagemagick aanwezig in het systeem. Imagemagick kan ge&iuml;nstalleerd worden door [b] yum -y install imagemagick [/b] in een terminal venster in te voeren.";
//There is no imagemagick in the system. You can install imagemagick by running [b] yum -y install imagemagick [/b].
$__emessage['warn_license_limit'] = "De licentielimiet voor [%s] is bijna bereikt. Wanner het systeem [%s] over zijn limiet gaat dan zal de interface stoppen met werken en kan het systeem niet meer beheerd worden. Klik <url:o=license&a=show>hier</url> om de licentie bij client.lxlabs.com te updaten."; 
// You are very close to your license limit for [%s]. If the system goes over limit for [%s] the interface will stop working and you won't be able to manage your system. Please increase your license at client.lxlabs.com and update by <url:o=license&a=show> clicking here </url>
$__emessage['file_already_exists'] = "Het bestand [%s] bestaat al."; 
// The file [%s] already exists.
$__emessage['contact_set_but_not_correct'] = "De contact informatie lijkt geen geldig e-mailadres te zijn. Klik <url:a=updateform&sa=information>hier</url> om het aan te passen."; 
// Your Contact Information doesn't appear to be a valid email address. Click <url:a=updateform&sa=information> here to fix it.</url>
$__emessage['contact_not_set'] = "De contact informatie is niet goed ingesteld. Klik <url:a=updateform&sa=information>hier</url> om het aan te passen. "; 
// Your Contact Information is not set properly. Click <url:a=updateform&sa=information> here to fix it. </url>
$__emessage['you_have_unread_message'] = "er zijn [%s] ongelezen bericht(en). Klik <burl:a=list&c=smessage>hier</burl> om ze te lezen."; 
// You have [%s] Unread Message(s). click <burl:a=list&c=smessage> here  to read it. </burl>
$__emessage['you_have_unread_ticket'] = "Er zijn [%s] ongelezen ticket(s). Klik <burl:a=list&c=ticket>hier</burl> om ze te lezen."; 
// You have [%s] Unread Ticket(s). click <burl:a=list&c=ticket> here  to read it. </burl>
$__emessage['security_warning'] = "Het wachtwoord is nu ingesteld als een automatisch gegenereerd wachtwoord dat een ernstige bedreiging vormt. Wijzig deze onmiddellijk door <url:a=updateform&sa=password>hier</url> te klikken. "; 
// Your password is now set as a generic password which constitutes a grave security threat. Please change it immediately by <url:a=updateform&sa=password> clicking here. </url>
$__emessage['ssh_port_not_configured'] = "De ssh port voor deze server is niet ingesteld. Het is een goed idee om het te veranderen naar iets anders dan de standaard 22. Klik <url:a=show&o=sshconfig>hier</url> om het aan te passen. Wanneer poort 22 wel behouden moet worden, maar niet steeds dit bericht krijgen ga dan naar de pagina en stel poort 22 geforceerd in. De waarschuwing wordt dan niet opnieuw weergegeven."; 
// The ssh port for this server is not set. It is a good idea to change it to something other than the default 22. Please  <url:a=show&o=sshconfig> click here to change:</url>. If you want to keep the ssh port to 22 and still avoid this message, go to the page, and set it forcibly to 22, and the warning will not be displayed again.
$__emessage['system_is_updating_itself'] = "Het systeem is op dit moment zichzelf aan het upgraden, daarom kunnen er nu voor een paar minuten geen wijzigingen worden aangebracht. Alle lees acties werken wel normaal."; 
// The system at this point is upgrading itself, and thus you won't be able to make any changes for a few minutes. All read actions work normally though.
$__emessage['system_is_locked'] = "Iemand is een systeem-modificatie-actie op dit bepaald object gestart en die draait nog steeds. Er kunnen pas wijzigingen worden aangebracht nadat de actie is afgerond. Alle lees acties werken wel normaal."; 
// Someone has initiated system-modification-action on this particular object which is still going on. You wont be able to make any changes till it is finished. All read actions work normally though.
$__emessage['system_is_locked_by_u'] = "Er is een systeem-wijziging-actie gestart die nog steeds draait. Er kunnen pas wijzigingen worden aangebracht nadat de actie is afgerond. Alle lees acties werken wel normaal."; 
// You have initiated a system-modification-action which is still going on. You wont be able to make any changes till it is finished. All read actions work normally though.
$__emessage['smtp_server_not_running'] = "HyperVM kan geen verbinding maken met een SMTP-server op deze server. Dat betekent dat HyperVM niet in staat is in het verzenden van e-mails. Dit is zeer kritisch aangezien HyperVM de gezondheid controleert van de hele cluster en een e-mail naar de admin verstuurd wanneer er problemen ontstaan. Er moet voor gezorgd worden dat de SMTP-service wordt uitgevoerd op deze server. Zodra de SMTP-service opnieuw is opgestart zal het vijf minuten duren voordat dit foutbericht verdwenen is. Dit is omdat HyperVM &eacute;&eacute;n keer per minuten controleert of deze dienst aanwezig is."; 
// hyperVM could not connect to an smtp server on this server. That means that hyperVM will not able to send out any mails. This is very critical since hyperVM monitors the health of the entire cluster and sends email to the admin if there is any problem. You should make sure that the smtp service is running on this server. Once you restart the SMTP service, please wait 5 minutes for this error message to disappear, since hyperVM checks for the service availability only once every 5 minutes.
$__emessage['template_not_owner'] = "U bent niet de eigenaar van deze sjabloon."; 
// You are not the Owner of this Template
$__emessage['ipaddress_changed_amidst_session'] = "IP-adres is gewijzigd tijdens een sessie. Dit is mogelijk sessie kaping."; 
// IP Address Changed Amidst Session. Possible Session Hijacking.
$__emessage['more_than_one_user'] = "Meer dan &eacute;&eacute;n gebruiker is ingelogd op dit account. Klik <burl:a=list&c=ssession>hier</burl> voor een overzicht van aangemelde gebruikers. "; 
// More than one user is logged in this account. Click <burl:a=list&c=ssession>here to see list of logins. </burl>
$__emessage['login_error'] = "Inloggen is mislukt!"; 
// Login Unsuccessful
$__emessage['file_exists'] = "bestand(en) [%s] bestaat reeds. Niet overschrijven..."; 
// file(s) [%s] Exists. Not Pasting...
$__emessage['cannot_unzip_in_root'] = "Er kunnen geen zip bestanden uitgepakt worden naar de root map. Gelieve een andere naam op te geven voor de map waarnaar het bestand uitgepakt dient te worden."; 
// You cannot unzip files into the root. Please specify a directory and unzip into that.
$__emessage['nouser_email'] = "De e-mail komt niet overeen met de gebruikers contact e-mail adres."; 
// The Email doesn't match User's Contact Email Address
$__emessage['session_expired'] = "Sessie is verlopen"; 
// Session Expired
$__emessage['e_password'] = "Onjuist Wachtwoord."; 
// Password Incorrect
$__emessage['is_demo'] = "[%s] is uitgeschakeld in de demo versie."; 
// [%s] is Disabled in Demo Version.
$__emessage['user_create'] = "Gebruiker [%s] kon niet aangemaakt worden. Probeer een andere naam."; 
// User [%s] Could not be Created. Please try a different Name
$__emessage['switch_done'] = "Schakelen tussen de servers is uitgevoerd op de achtergrond. U ontvangt een mail wanneer de overstap voltooid is."; 
// Switching the Servers has been run in the background. You will be sent a mail when the switch is complete.
$__emessage['mis_changed'] = "Weergave configuratie is succesvol gewijzigd."; 
// Display Configuration successfully changed.
$__emessage['password_sent'] = "Wachtwoord is opnieuw ingesteld en succesvol verzonden."; 
// Password was reset and sent successfully.
$__emessage['added_successfully'] = "[%s] is succesvol toegevoegd."; 
// [%s] was added successfully.
$__emessage['backup_has_been_scheduled'] = "De backup gebeurt nu op de achtergrond. U ontvangt een mail aan uw contact e-mail wanneer de backup voltooid is."; 
// The backup is now happening in the background. You will receive a mail at your contact email when it is done.
$__emessage['update_scheduled'] = "Update wordt nu op de achtergrond uitgevoerd. U kunt deze pagina vernieuwen om te zien of de update correct is voltooid.";
// Update is now running in the background. You can refresh this page to see if the update has completed properly.
$__emessage['restore_has_been_scheduled'] = "Het opnieuw opslaan gebeurt nu op de achtergrond. U ontvangt een mail op uw contact e-mail wanneer het opslaan is voltooid."; 
// The Restore is now happening in the background. You will receive a mail at your contact email when it is done.
$__emessage['same_dns'] = "Master en Slave kunnen zich niet op dezelfde server bevinden"; 
// Master And Slave Cannot Be on the same Server.
$__emessage['user_exists'] = "Er bestaat al een gebruiker met de naam [%s]."; 
// User [%s] already exists.
$__emessage['mysql_error'] = "MySQL fout. Database zei: [%s]"; 
// Mysql Error, Database Said: [%s]
$__emessage['this_domain_does_not_resolve_to_this_ip'] = "Om een IP toe te wijzen aan een domein, dan moet het domein pingen naar hetzelfde IP anders zal het domein stoppen met werken. Het domein waarvan het IP in kaart moet worden gebracht komt niet terug naar de IP die het oplost en dus kan het niet worden ingesteld als het standaarddomein voor de IP."; 
// To map an IP to a domain, the domain must ping to the same IP, otherwise, the domain will stop working. The domain you are trying to map this IP to, doesn't resolve back to the IP, and so it cannot be set as the default domain for the IP.
$__emessage['dns_conflict'] = "Het domein is niet toegevoegd vanwege en fout in de DNS instellingen. Gelieve het DNS-sjabloon te controleren en te verifi&euml;ren. Het bericht van de DNS-server was [%s]"; 
// The domain was not added due to an error in the dns settings. Please check your dns template and verify. The message from the dns server was [%s]
$__emessage['add_without_www'] = "Alleen het hoofd domein zou in de vorm van domein.com moetn worden toegevoegd. De [b]www[/b] subdomein zal daar automatisch aan worden toegevoegd. Er moet alleen niet [b]www[/b] worden toegevoegd wanneer er een domein wordt aangemaakt."; 
// You should add only the main domain in the form of domain.com. The [b] www [/b] subdomain will be automatically added to it. You shouldn't add [b] www [/b] when creating a domain.
$__emessage['could_not_connect_to_db'] = "Kon geen verbinding maken met Database. De fout is geregistreerd. Neem contact op met de beheerder."; 
// Could Not Connect to Database: The error has been logged. Please contact the administrator.
$__emessage['e_no_dbadmin_entries'] = "Er zijn geen items in de database geconfigureerd voor deze bepaalde server. Neem contact op met uw admin om deze in te stellen."; 
// There are no Database administrator entries configured for this particular server. Please contact your admin to set them.
$__emessage['please_add_one_domain_for_owner_mode'] = "Er zal ten minste &eacute;&eacute;n domein aanwezig moeten zijn als het domein van eigenaar moet veranderen.  Klik <url:a=addform&c=domain>hier</url> om een domein toe te voegen."; 
// You will need to have at least one domain if you want to switch to domain owner mode. You can add a domain by <url:a=addform&c=domain>clicking here </url>.
$__emessage['e_no_dbadmin_entries_admin'] = "Er zijn in de database beheerder items geconfigureerd voor deze bepaalde server. Ga naar de server sectie van deze server en klik op de DBadmin link. Voeg hier de database admin gebruiker en wachtwoord in voor deze machine en type database."; 
// There are no Database administrator entries configured for this particular server. You have to go to the server section for this server, and click on the Dbadmin link, and add the database admin user and password for this particular machine and the type of database.
$__emessage['mail_server_name_not_set'] = "De indentificatie naam voor de mailserver is niet ingesteld. Dit betekent dat veel openbare e-mail servers zoals hotmail e-mails van de server zullen verwerpen. Klik <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=servermail>hier</url> om het in te stellen. ";
// The identification name for your mail server is not set. This means that many public mail servers like hotmail will reject mails from your server. Click <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=servermail> here to set it. </url>"
$__emessage['dns_template_inconsistency'] = "De DNS sjabloon die is gekozen komt niet overeen met de keuze van de servers. Bijvoorbeeld; Het zou kunnen zijn dat het ip-adres in de DNS helemaal niet is gevonden op de webserver. Ga terug en maak een DNS sjabloon die de parameters consistentie heeft met server setup."; 
// The Dns Template You have chosen is not consistent with your choice of the servers. For instance, it could be that the ipaddress in the dns is not at all found in the webserver. Please go back and create a dns template that has the parameters consistent with server setup.
$__emessage['adding_cron_failed'] = "Het toevoegen van een Crontab is mislukt vanwege [%s]. Verwijder de Crontab en probeer het opnieuw."; 
// Adding crontab has failed due to [%s]. Please delete it and add it again.
$__emessage['se_submit_running_background'] = "Zoek machine submissie draait op de achtergrond. U ontvangt een bericht naar uw contact e-mail na afronding."; 
// Search Engine Submission is running in the background. You will be sent a message to your contact email when it is done.
$__emessage['err_no_dns_template'] = "Er zijn geen DNS sjablonen in het systeem aanwezig. Er moet ten minste &eacute;&eacute;n DNS-sjabloon aanwezig zijn om een domein of klant toe te kunnen voegen. Klik <url:a=addform&c=dnstemplate>hier</url> om een DNS sjabloon toe te voegen.</p>"; 
// There are no Dns Templates in the System. You have to have at least one Dns Template to add a domain/client. Click <url:a=addform&c=dnstemplate> here to add a dnstemplate. </url></p>
$__emessage['certificate_key_file_empty'] = "Het certificaat en het sleutel bestand dat u heeft gekozen zijn leeg. Er moet eerst &eacute;&eacute;n aangemaakt of &eacute;&eacute;n upgeload worden voordat ze worden ingeschakeld."; 
// The certificate and the Key file you have chosen are empty. You have to first create or upload them before enabling ssl

// release on Kloxo 6.1.7
// by mustafa.ramadhan@lxcenter.org

$__information['webserver_config'] = "[b]PHP Type[/b] - Process-based (httpd-prefork/-itk), thread-based (httpd-worker/-event) and ".
	"secure environment (suphp/suexec/ruid2/itk)<br />".
	"[b]Apache Memory Optimize[/b] - Optimize memory usage<br />".
	"[b]MySQL Convert[/b] - MyISAM (less memory usage (save 100-200 MB) and ".
	"InnoDB (higher performance)<br />".
	"[b]Fix 'Ownership' And 'Permissions'[/b] - Prevent '500 Internal server error' on secure environment<br />".
	"&nbsp;&nbsp;&nbsp;&nbsp;- Fix-ownership ('chown -R client:client' for directories and files) and ".
	"Fix-permissions ('chmod 755' for directories and 'chmod 644' for .php files)"; 
// [b]PHP Type[/b] - Process-based (httpd-prefork/-itk), thread-based (httpd-worker/-event) and ".
//	"secure environment (suphp/suexec/ruid2/itk)<br />".
//	"[b]Apache Memory Optimize[/b] - Optimize memory usage<br />".
//	"[b]MySQL Convert[/b] - MyISAM (less memory usage (save 100-200 MB) and ".
//	"InnoDB (higher performance)<br />".
//	"[b]Fix 'Ownership' And 'Permissions'[/b] - Prevent '500 Internal server error' on secure environment<br />".
//	"&nbsp;&nbsp;&nbsp;&nbsp;- Fix-ownership ('chown -R client:client' for directories and files) and ".
//	"Fix-permissions ('chmod 755' for directories and 'chmod 644' for .php files)

// Language Content for #656
// by Andrew Ying
$__emessage['document_root_may_not_contain_spaces'] = "De document root mag geen spatie bevatten voor of na de slash. Controleer en verzend opnieuw."; 
// The document root may not contain any space at the end or before the slash. Please check and submit again.
