#!/bin/sh

# release on Kloxo 6.1.7
# by mustafa.ramadhan@lxcenter.org

if [ "$#" == 0 ] ; then
	echo
	echo " ------------------------------------------------------------"
	echo "  format: sh $0 --select=chown/chmod/all"
	echo " ------------------------------------------------------------"
	echo " --select -"
	echo "   chown: ownership only"
	echo "   chmod: permissions only (for php*)"
	echo
	echo " * important for secure environment like suphp on Apache"
	echo
	exit;
fi

. /script/directory
lphp.exe ../bin/fix/fix-chownchmod.php $*