#!/bin/sh

#!/bin/bash
# mysql skip-innodb

# ENVIRONMENT VARIABLE PRIMER FOR REFERENCE
# $0 script invoked
# $1, $2, $3 are the command line arguments
# $# Number of command line arguments 
# $@ all command line arguments - white space is preserved
# $* all command line arguments - white space striped 

if [ "$#" == 0 ] ; then
	echo
	echo "------------------------------------------------------------------------------"
	echo " format: sh $0 --innodb=status/skip"
	echo "------------------------------------------------------------------------------"
	echo
	exit;
fi

. /script/directory
lphp.exe ../bin/fix/mysql-skipinnodb.php $*
