#!/bin/sh

# release on Kloxo 6.1.7
# by mustafa.ramadhan@lxcenter.org

# ENVIRONMENT VARIABLE PRIMER FOR REFERENCE
# $0 script invoked
# $1, $2, $3 are the command line arguments
# $# Number of command line arguments 
# $@ all command line arguments - white space is preserved
# $* all command line arguments - white space striped 

if [ "$#" == 0 ] ; then
	echo
	echo " ------------------------------------------------------------------------------"
	echo "  format: sh $0 --select=repair/optimize --database=[]"
	echo " ------------------------------------------------------------------------------"
	echo "  --database - database name; default: all databases"
	echo
	exit;
fi

. /script/directory
lphp.exe ../bin/fix/mysql-optimize.php $*
