<?php 
include_once "htmllib/lib/definecore.php";

$gl_class_array["pserver"] = "lib/pserver/pserverlib.php";
$gl_class_array["domaind"] = "lib/domain/domainlib.php";
$gl_class_array["subdomain"] = "lib/domain/domainlib.php";
$gl_class_array["domain"] = "lib/domain/domainlib.php";
$gl_class_array["dirindexlist_a"] = "lib/genlistlib.php";
$gl_class_array["genlist"] = "lib/genlistlib.php";
$gl_class_array["domaina"] = "lib/domain/domainlib.php";
$gl_class_array["domaindefault"] = "lib/domain/domaindefault.php";
$gl_class_array["all_domaina"] = "lib/domain/domainlib.php";
$gl_class_array["all_domain"] = "lib/domain/domainlib.php";
$gl_class_array["maindomain"] = "lib/domain/domainlib.php";
$gl_class_array["all_mailaccount"] = "lib/domain/mmail/mailaccountlib.php";
$gl_class_array["all_cron"] = "htmllib/lib/pserver/ddatabaselib.php";
$gl_class_array["mailaccountd"] = "lib/domain/mmail/mailaccountlib.php";
$gl_class_array["installappsnapshot"] = "lib/domain/web/installappsnapshot.phps";
$gl_class_array["domaintemplate"] = "lib/domain/domaintemplatelib.php";
$gl_class_array["domaintraffic"] = "lib/domain/domaintrafficlib.php";
$gl_class_array["mailaccount"] = "lib/domain/mmail/mailaccountlib.php";
$gl_class_array["mailforward"] = "lib/domain/mmail/mailforwardlib.php";
$gl_class_array["mailinglist"] = "lib/domain/mmail/mailinglistlib.phps";
$gl_class_array["listsubscribe"] = "lib/domain/mmail/listsubscribelib.php";
//$gl_class_array["phpmailer"] = "lib/extra/class.phpmailer.php";
//$gl_class_array["smtp"] = "lib/extra/class.smtp.php";
$gl_class_array["autoresponder"] = "lib/domain/mmail/autoresponderlib.php";
$gl_class_array["installapp"] = "lib/domain/web/installapplib.phps";
$gl_class_array["allinstallapp"] = "lib/domain/web/allinstallapplib.phps";
$gl_class_array["domaintraffichistory"] = "lib/domain/domaintraffichistorylib.php";
$gl_class_array["mmail"] = "lib/domain/mmail/mmaillib.php";
$gl_class_array["clientmail"] = "lib/domain/clientmail.php";
$gl_class_array["spam"] = "lib/domain/mmail/spamlib.php";
$gl_class_array["webmimetype"] = "lib/domain/web/mimehandler.php";
$gl_class_array["webhandler"] = "lib/domain/web/mimehandler.php";
$gl_class_array["web"] = "lib/domain/web/weblib.php";
$gl_class_array["dirprotect"] = "lib/domain/web/dirprotectlib.php";
//$gl_class_array["clientskel"] = "lib/client/clientskellib.php";
$gl_class_array["resourcecore"] = "lib/resourcecorelib.php";
$gl_class_array["client"] = "lib/client/clientlib.php";
$gl_class_array["clienttemplate"] = "lib/client/clienttemplatelib.php";
$gl_class_array["phpini"] = "htmllib/lib/pserver/phpinilib.php";
$gl_class_array["phpini__sync"] = "htmllib/lib/pserver/driver/phpini__synclib.php";
$gl_class_array["domainbase"] = "lib/domain/domainbaselib.php";
$gl_class_array["webtraffic"] = "lib/domain/web/webtrafficlib.php";
$gl_class_array["mailtraffic"] = "lib/domain/mmail/mailtrafficlib.php";
$gl_class_array["davuser"] = "lib/domain/web/davuserlib.php";
$gl_class_array["domaincore"] = "lib/domain/domaincorelib.php";
//$gl_class_array["node"] = "lib/client/nodelib.php";
//$gl_class_array["slave"] = "lib/client/slavelib.php";
//$gl_class_array["superclient"] = "lib/client/superclientlib.php";
$gl_class_array["blockedip"] = "htmllib/phplib/lib/blockediplib.php";
$gl_class_array["mailcontent"] = "lib/domain/mmail/mailcontentlib.php";
$gl_class_array["mailqueue"] = "htmllib/lib/pserver/mailqueuelib.php";
$gl_class_array["addondomain"] = "lib/domain/addondomainlib.php";
$gl_class_array["all_addondomain"] = "lib/domain/addondomainlib.php";
$gl_class_array["weblastvisit"] = "lib/domain/web/weblastvisitlib.php";
$gl_class_array["serverweb"] = "lib/serverweblib.php";
$gl_class_array["rubyrails"] = "lib/domain/web/rubyrailslib.php";



