<?php 
$__emessage['same_dns']  = "Master And Slave Cannot Be on the same Server.";
$__emessage['user_exists']  = "User [%s] already exists.";
$__emessage['mysql_error'] = "Mysql Error, Database Said: [%s]";
$__emessage['this_domain_does_not_resolve_to_this_ip'] = "To map an IP to a domain, the domain must ping to the same IP, otherwise, the domain will stop working. The domain you are trying to map this IP to, doesn't resolve back to the IP, and so it cannot be set as the default domain for the IP.";
$__emessage['dns_conflict'] ="The domain was not added due to an error in the dns settings. Please check your dns template and verify. The message from the dns server was [%s]";
$__emessage['add_without_www'] ="You should add only the main domain in the form of domain.com. The [b] www [/b] subdomain will be automatically added to it. You shouldn't add [b] www [/b] when creating a domain.";
$__emessage['could_not_connect_to_db'] = "Could Not Connect to Database: The error has been logged. Please contact the administrator.";
$__emessage['e_no_dbadmin_entries'] ="There are no Database administrator entries configured for this particular server. Please contact your admin to set them.";
$__emessage['please_add_one_domain_for_owner_mode'] ="You will need to have at least one domain if you want to switch to domain owner mode. You can add a domain by <url:a=addform&c=domain>clicking here </url>.";
$__emessage['e_no_dbadmin_entries_admin'] ="There are no Database administrator entries configured for this particular server. You have to go to the server section for this server, and click on the Dbadmin link, and add the database admin user and password for this particular machine and the type of database.";
$__emessage['mail_server_name_not_set'] ="The identification name for your mail server is not set. This means that many public mail servers like hotmail will reject mails from your server. Click <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=servermail> here to set it. </url>";

$__information['web_updateform_extra_tag_pre'] = " <b><font color=red> Warning!!!!! </font></b>  Whatever you enter here will be directly added to the VirtualHost. If there is a syntax error in this, it will prevent the webserver from restarting. This option is available only for the admin user. After Saving here, make sure that the server is running. ";
$__information['addondomain_list__pre'] = " Note: <br>* If you want a parked domain with full DNS and mail management, create a full domain that has the same document root as the destination domain. <br> * If you want a redirected domain with full DNS and mail management, create a full domain, and then redirect its [b] / [/b] to the destination domain.";
$__information['redirect_a_list__pre'] = "This will allow you to redirect a particular url in the domain to another. <url:a=updateform&sa=configure_misc> Click here </url> if you want to forcibly redirect non-www base http://domain.com to http://www.domain.com, ";


$__information['web_updateform_dirindex_pre'] = "Enabling [b] directory index [/b] will allow you to browse the directories of your domain via the webserver. If directory index is disabled, and if an index.xxx file is not found inside the directory, a forbidden error message will be raised.";
$__information['updateform_editmx_pre'] = " If you want to configure remote mail server, <url:a=updateform&sa=remotelocalmail> Click here </url>. You can tell kloxo that the mail server is configured remotely, so that all local generated mails will be sent to that server. If you don't configure remote mail, then all mails to this domain will delivered locally itself, without doing any DNS lookup. ";
$__information['web_updateform_run_stats_pre'] = "This will allow you to forcibly run the stats program, so that you can see your latest statistics in the web statistics page. Use [b] update all [/b] to run it on all the domains visible in the top pull down menu.";
$__information['server_alias_a_addform__pre'] = "You can add [b] * [/b] as an alias so that all the subdomains are automatically directed to this domain. Kloxo will also automatically add a DNS entry for the alias. Once you configure the catchall subdomain with '*', you can add the proper logic in your script to detect the correct subdomain and do accordingly.";

$__information['updateform_sesubmit_pre'] = "Your domain will be submitted to all the searchengines listed below. The email should be an address that's not used often, since you are very highly likely to get Spammed on the email you enter here";
$__information['mmail_updateform_authentication_pre'] = "Your primary mx server is automatically included in the SPF, and you need not add it separately. You can use [b] update all [/b] to impress these values on all the domains visible on the top pull down list.";
$__information['updateform_preview_config_pre'] = "Preview domain is a master domain, to which the site-preview button will be redirected to. You have to manually add a parked domain called domain.com.previewdomain.com to this domain, and then add the previewdomain.com here. Then the [b] dns less preview [/b] will be redirected to domain.com.previewdomain.com. If unsure, please leave this blank.";

$__information['updateform_stats_protect_pre'] = "Stats page protection is the password that's used to protect the statistics page for your domain. If set to to null password, protection will be disabled, and you will be able to access the stats directly.";
$__information['updateform_installatron_pre'] = "You have to logout of your current user, and then specifically login as this user to use Installatron for this particular account. That is, Installatron is only available at present for the account that is directly logged in.";

$__information['ftpuser_admin'] = "Use [b] --direct-- [/b] to add an ftpuser that does not contain domain name.";
$__information['updateform_default_domain_pre'] = " This will set the domain that's considered as the primary domain for this particular account. You can access this domain's document root by going to http://IP/~clientname. To map an ipaddress to a domain, you have to <url: a=list&c=ipaddress> click here </url>, go inside an ipaddress and click on 'configure domain' tab there. If you want to view a domain before the dns is setup, the best way is to create an entry for the domain in your local etc/hosts file. The path for the file on windows is c:/windows/system32/drivers/etc/hosts . Just add an entry like this: [b] 192.168.1.32 domain.com [/b] on a separete line, and then you will be able to access the domain by typing it in your browser's url box.";

$__information['updateform_blockip_pre'] = " Add one IP per line. If you want to add an IP range use the .*.* notation. For instance, 192.168.*.*. Please note, this is the only notation supported for ip ranges. The standard ip notation is not supported. ";

$__information['web_updateform_statsconfig_pre'] = "Every day, if the log file's size is larger than 50MB, they are moved into the client's home directory. If you set the remove_processed_logs as true, then instead of moving, they will be deleted. Your main statistics calculation will not be affected at all.";
$__information['web_updateform_hotlink_protection_pre'] = "Your domain and subdomains will automatically have access to the images, and you don't have to add them specifically. a *.domain.com is automatically added to the list of allowed domains you supply here. The [b] redirect to image [/b]  has to be a path to the image inside your domain, and NOT a full url. It should be of the form (/img/noaccess.gif). You have to enter domains as simple names without any wild-characters. For example, domain.com, mydomain.com, mysdomain.com";
$__information['mailqueue_list__pre'] = "It will take a little bit more time for the queue to actually disappear. So after clicking on delete, the mails will appear in the queue for some more time. Just refresh the page after around a minute to verify if the mails are actually deleted or not.";
$__information['mailqueue_updateform_update_pre'] = "To see the log for the mail, please go back to the listing, and flush the mailqueue once, since only the log for the past hour is parsed.";

$__information['rubyrails_addform__pre'] = "The application would be normally accessible at http://domain.com/applicationname. The path would be /home/client/ror/domain.com/applicationname. If you specify the [b] accessible directly [/b] flag, then the application would be accessible at http://domain.com itself.";
$__information['installapp_addform__pre'] = "To install an application in the document root, please leave the [b] Location [/b] blank. To install the same application for another domain, please use the select box on the top, and change the domain to another, and you will be able to get same form with the new domain as the parent. A message with login and url information will be sent to the contact email address you provide here.";
$__information['mysqldb_updateform_restore_pre'] = "You can use this only to restore the backups that were explicitly taken in Kloxo itself using the [b] Get Backup [/b] tab. To restore normal mysql dump file, please use phpMyAdmin.";
$__information['domainipaddress_updateform_update_pre'] = "This will allow you to map a particular ipaddress to a domain. That is, if someone accesses http://ip, then the document root of the domain configured here will be shown.";
$__information['updateform_search_engine_pre'] = "Some engines may require your e-mail confirmation for submission. Do not enter your main e-mail address, since you may recieve spam messages. For a better ranking repeat the operation every 3-4 weeks but not sooner, since you may get banned";

$__information['updateform_domainpserver_pre'] = "These are the servers on which the domains under this client will be configured on. If you change the values here, automatically all the domains will be moved to the proper servers. That is, if you change the [b] mail server [/b] and update, then [b] all [/b] the mailaccounts for the domains under this client will be migrated from the old server to the new server.  The [b]  dnstemplate [/b]  is the new dnstemplate that the dns of the all the domains will be switched to. So you have to make sure that you first create a dnstemplate that reflects the new configuration, then provide that to kloxo here. See bottom for more help on server move. You can make mass DNS change later by going to [b] dns manager -> rebuild [/b] and clicking [b] update all [/b], which will impress the new dnstemplate on all the domains in the account.";

//$__information['sslipaddress_updateform_update_pre_ipaddress'] = "To setup an ssl for an ipaddress, first upload/add an ssl certificate from <url:goback=3&a=list&c=sslcert> here </url>";
$__information['sslipaddress_updateform_update_pre'] = "To setup an ssl for an ipaddress, first upload/add an ssl certificate from <url:goback=2&a=list&c=sslcert> here </url>";
$__information['domain_addform__pre_docroot'] = "Leave the document root blank and Kloxo will automatically use mydomain.com as the docroot.";

$__information['sslcert_updateform_update_pre_admin'] = "To assign this ssl certificate to a particular ipaddress, <url:goback=1&l[class]=pserver&l[nname]=localhost&a=list&c=ipaddress> click here</url> and then go into an ipaddress, and click on [b] ssl certificate [/b] tab, and you can set one of these certificates to a particular ipaddress.";

$__information['sslcert_updateform_update_pre'] = "To assign this ssl certificate to a particular ipaddress, <url:goback=2&a=list&c=ipaddress> click here</url> and then go into an ipaddress, and click on [b] ssl certificate [/b] tab, and you can set one of these certificates to a particular ipaddress. The admin will need to have assigned you an exclusive ipaddress for you to access this feature.";
$__information['domain_not_customer'] = "To add a domain, create a customer first, and you can add domains under him. To add a customer, <url:a=addform&c=client&dta[var]=cttype&dta[val]=customer>click here </url>";

$__information['ipaddress_list__pre'] = "Exclusive IP will allow you to have dedicated control of a particular ipaddress. This is useful for setting up SSL and also for setting up an ip for a domain. That is, if you want a particular IP to resolve to a domain. For you to have an exclusive IPaddress, the administrator will have to set the exclusive client of a particular ipaddress. To setup ssl or to map an IP to a domain, click on an IPaddress, and then click on [b] configure ssl [/b] or [b] configure domain [/b] ";
$__information['clientmail_list__pre'] = "This will list the number of mails sent out by your clients via the webserver or smtp auth relay in the last 2 days. If it is a full mailaccount like [b] user@domain.com [/b], then it represents mail sent via relay. If it is a simple username, then it represents mail sent via a form in the web server. If you use mod_php on apache, then all webapplications are run as user [b] apache [/b] , and only [b] apache [/b] will be displayed here. Use suPHP on apache, if you are planning on hosting for third parties. That way you will be able to identify each client using his system user.";
$__information['servermail_updateform_update_pre'] = "It is very essential that you set the my name to a properly resolvable hostname, since otherwise, many public mailservers like hotmail will reject mails from your server. You can have the mail server running on additional port by specifying it here. Leave it blank to to disable additional smtp. The max smtp instances specifies the maximum number of smtp processes that are allowed. You should set it to some number, say 10, if you are getting spammed heavily. If you leave it blank, it will be set to UNLIMITED, which is the default.";
$__information['updateform_switchprogram_pre'] = "Switching Programs will take a while, since it needs to remove the old program from the system, and install the new one using yum. The log for this will be availabe in the shell_exec file. All your information will be transparently migrated. You will need to wait one minute before the new service properly restarts.";
$__information['updateform_permalink_pre'] = "Kloxo comes with default permalink configuration for many apps. Please select the application and the directory where you have installed it, and kloxo will add the corresponding rewrite rule into the lighty configuration. Please note that for some applications, permalinks are achieved via setting the 404 error handler, for instance wordpress.";
$__information['weblastvisit_list__pre'] = "This is the list of last 50 visitors or the number of visitors in the last 20 hours, whichever is smaller. Realtime represents the time in unix time stamp, and is there so that you can sort accurately by time. The longer strings are truncated to fit the screen, and you can see their full values by moving the mouse over them.";
$__information['subweb_a_addform__pre'] = "This is a simple subdomain. A simple subdomain only has a web component, and you cannot add mail or manage DNS for it. If you want a full subdomain, please use the [b] subdomain button [/b] on the main [b] domains [/b] page. The simple subdomain's path is /home/clientname/domain/domain.com/subdomains/subdomainname";


$__information['updateform_skeleton_pre'] = "This is the archive of the skeleton directory which will be copied to your domain home directory when it is created. The archive will be unzipped into a newly created domain's home directory. You can use [b] &lt;%domainname%&gt; , &lt;%clientname%&gt; [/b]  inside the index.html file, and the variables will be replaced properly with the correct values.";

$__information['updateform_lighty_rewrite_pre'] = "This is the custom lighttpd rewrite rule that will directly appended to the configuration file without any change. It will be of the form [b] url.rewrite = ( ... [/b].  ";
$__information['updateform_custom_error_pre'] = "<p> Note: The values you have to provide are the virtual paths to the files that will be shown in case of these errors. Example: /error_files/404.html.</p>";
$__information['domain_updateform_ipaddress_pre'] = "<p> Note: Make sure that you make the requisite changes to nameserver configuration too.  </p>";
$__information['client_updateform_ipaddress_pre'] = "<p> Note: The available ip pool is selected from the machines in the web server pool. </p>";
$__information['domaintemplate_addform__pre'] = "<p> Note: The Max Value on the right shows your current quota limit. You can create a Template with values more than your quota, but you won't be able to use them to create Domains/Clients. </p>";
$__information['vv_dns_blank_message'] = "<p> Enter '__base__', if you want to get the base domain. Use &lt;%domain&gt; if you want the domain name inside a TXT record. For instance, 'v=spf1 include: &lt;%domain &gt;'. [b] FCNAME [/b] stands for full cname and will allow you to point a subdomain to an external domain.";
$__information['spam_updateform_update_pre'] = "<p> The 'score'--which can be 1-10--is the value at which a mail is marked as SPAM. So if you set it to lower values, more mail will be marked as spam. Too low values might lead to genuine mails getting classified as spam. Too high values will lead to high amount of spam getting through the filter. </p>";
$__information['web_updateform_enable_frontpage_flag_pre'] = "<p> The frontpage password will be the same as that of the system user (main ftp user).  </p>";
//$__information['web_updateform_redirect_domain_pre'] = "<p> The url should not contain the initial 'http://', for example. 'sample.com/redirected.html'. </p> ";
$__emessage['dns_template_inconsistency'] = "The Dns Template You have chosen is not consistent with your choice of the servers. For instance, it could be that the ipaddress in the dns is not at all found in the webserver. Please go back and create a dns template that has the parameters consistent with server setup.";
$__emessage['adding_cron_failed'] = "Adding crontab has failed due to [%s]. Please delete it and add it again.";
$__emessage['se_submit_running_background'] = "Search Engine Submission is running in the background. You will be sent a message to your contact email when it is done.";
$__emessage['err_no_dns_template'] = "There are no Dns Templates in the System. You have to have at least one Dns Template to add a domain/client. Click <url:a=addform&c=dnstemplate> here  to add a dnstemplate. </url></p> ";

$__emessage['certificate_key_file_empty'] = "The certificate and the Key file you have chosen are empty. You have to first create or upload them before enabling ssl";

$__information['ffile_show___lx_error_log_pre'] = 'This is the error log for your domain. The contents of this will help you trouble shoot if you are having any problems regarding the domain.';
$__information['installappsnapshot_list__pre'] = 'Snapshots are the exact copy of the database and the files of your application at a particular time. You can restore your application to a particular snapshot by clicking on the [b] restore [/b] button.';

$__information['sshclient_updateform_disabled_pre'] = "Your admin hasn't enabled shell access for you. Please open a support ticket if you need ssh access. ";
$__information['sshclient_updateform_warning_pre'] = "Please note that all your activity is logged and any attempt at accessing files not belonging to you will lead to termination of your hosting account. So please act responsibly.";

$__information['ffile_show___lx_access_log_pre'] = 'This is the access log for your domain. You can download this by clicking on the [b] download [/b] tab at the right. This file contains information about every single hit that is made to to your website';

$__information['updateform_disable_url_pre'] = "All your children will automatically inherit your Disable url parameters. To enforce your Disable Url on them, just disable their 'can Set Disable Url' in the permission settings. This is the url to which a domain will be redirected to when it is disabled. ";

$__information['updateform_dnstemplatelist_pre'] = "Allocate only a single dns template to your customer. This would mean that kloxo will not show the dns template select box while adding a domain, which will make it less confusing to your customer.";
$__information['forward_a_addform__pre'] = "The forward addresses are a list of email addresses to which the mail is forwarded to. One copy of the mail gets saved to the actual mailaccount too. You can disable local storage by <url:a=updateform&sa=configuration>clicking here </url>.";
